In [1]:
import json
import pandas as pd

In [3]:
from openai import OpenAI
from time import sleep


with open('openai-api-key.txt', 'r') as f:
    openai_api_key = f.read().strip()

openai_client = OpenAI(api_key=openai_api_key)

In [4]:
# separate the translation from other questions
with open('../data/structured/certamen_1996_2009.json', 'r') as f:
    questions = json.load(f)

question_df = pd.DataFrame(questions)

In [5]:
ids = question_df['question_id'].value_counts().index.tolist()
id_dict = {id: 0 for id in ids}

new_ids = []
for id_ in question_df['question_id']:
    new_id = id_ + '_' + str(id_dict[id_])
    new_ids.append(new_id)
    id_dict[id_] += 1

question_df['question_id'] = new_ids

In [6]:
# filtering:
# only questions where answers list is len 1 

filtered_df = question_df[question_df['answers'].apply(len) == 1]

# answers is single word (no whitespace)
filtered_df = filtered_df[filtered_df['answers'].apply(lambda x: ' ' not in x[0])]

# no reading comp questions
filtered_df = filtered_df[filtered_df['question_content'].apply(lambda x: 'reading' not in x.lower())]

In [2]:
translation_df = question_df[question_df['question_content'] == 'translation']
translation_df

NameError: name 'question_df' is not defined

short answer:
re-categorize question_content. Only 1 label allowed.
check question and answer language
filter out unanswerable (not enough info)

add scansion as a "question_content" option

In [8]:
short_answer = filtered_df.to_dict(orient='records')
short_answer

[{'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1a_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What name was given to the large agricultural estates which resulted from the distribution of the ager publicus in the 2nd century B.C.?',
  'multiple_choice_options': [],
  'answers': ['LATIFUNDIA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1b_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What was the manager or overseer of a latifundia called?',
  'multiple_choice_options': [],
  'answers': ['VILICUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4a_0',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'latin',
  'answer_language': 'latin',
  'question': 'Quod animal facit mel?',
  'multiple_choice_options': [],
  'answers': ['APIS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6b_0',
  'question_format': 'short_answer',
  'question_content': 'literature',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': "Who was Odysseus' long-suffering wife?",
  'multiple_choice_options': [],
  'answers': ['Penelope']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7a_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Give the first person singular, present passive subjunctive of vehō.',
  'multiple_choice_options': [],
  'answers': ['VEHAR']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7b_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Change vehar to imperfect.',
  'multiple_choice_options': [],
  'answers': ['VEHERER']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7c_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Change veherer to pluperfect active.',
  'multiple_choice_options': [],
  'answers': ['VEXISSEM']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7d_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What tense is iaciēs?',
  'multiple_choice_options': [],
  'answers': ['FUTURE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7e_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What tense is iaciās?',
  'multiple_choice_options': [],
  'answers': ['PRESENT']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7f_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What tense is iacēs?',
  'multiple_choice_options': [],
  'answers': ['PRESENT']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10a_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who was the Greek god of prophecy?',
  'multiple_choice_options': [],
  'answers': ['APOLLO']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10b_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Where did Apollo establish his main oracle in Greece?',
  'multiple_choice_options': [],
  'answers': ['DELPHI']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who was the father of Iphicles?',
  'multiple_choice_options': [],
  'answers': ['AMPHITRYON']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who forbade the memory of his brother and ordered the erasure of his name from all inscriptions in AD 212?',
  'multiple_choice_options': [],
  'answers': ['CARACALLA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15b_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Name the brother whom Caracalla had murdered.',
  'multiple_choice_options': [],
  'answers': ['GETA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_16a_0',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate into Latin the relative pronoun for the following English sentence: Julia, whose mother is rich, is the daughter of a senator.',
  'multiple_choice_options': [],
  'answers': ['CUIUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_16b_0',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate into Latin the relative pronoun for the following English sentence: The soldier did not like the others with whom he was traveling.',
  'multiple_choice_options': [],
  'answers': ['QUIBUS(CUM)']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_16c_0',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate into Latin the relative pronoun for the following English sentence: The farm, of which Horace was in charge, is burning to the ground.',
  'multiple_choice_options': [],
  'answers': ['CUĪ']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17a_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which centaur tried to kidnap Deianira, the wife of Hercules?',
  'multiple_choice_options': [],
  'answers': ['NESSUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17b_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'According to Ovid, who was the father of Nessus?',
  'multiple_choice_options': [],
  'answers': ['IXION']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_18a_0',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Latin is an inflected language. What is the meaning of the verb at the root of “inflected”?',
  'multiple_choice_options': [],
  'answers': ['BEND']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_18c_0',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'In Latin, as in English, there are three degrees of comparison. What is the meaning of the adjective at the root of “comparison”?',
  'multiple_choice_options': [],
  'answers': ['EQUAL']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_19a_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who gave shelter to Danae and her son Perseus?',
  'multiple_choice_options': [],
  'answers': ['Dictys']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_19b_0',
  'question_format': 'short_answer',
  'question_content': 'geography',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'On what island did Dictys live?',
  'multiple_choice_options': [],
  'answers': ['Seriphus']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_19c_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': "Name Dictys' brother who wanted to marry Danae.",
  'multiple_choice_options': [],
  'answers': ['Polydectes']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What foreign enemy general campaigned in Italy for 16 years, but was unable to capture Rome?',
  'multiple_choice_options': [],
  'answers': ['HANNIBAL']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3b_1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What household cooking substance is derived from ācer?',
  'multiple_choice_options': [],
  'answers': ['VINEGAR']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3c_1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What is the Latin word for vinegar?',
  'multiple_choice_options': [],
  'answers': ['ACĒTUM']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4a_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What great Trojan hero was the husband of Andromache?',
  'multiple_choice_options': [],
  'answers': ['HECTOR']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4b_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Greek hero killed Hector?',
  'multiple_choice_options': [],
  'answers': ['ACHILLES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5a_1',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who was the oldest of the four emperors proclaimed in A. D. 69?',
  'multiple_choice_options': [],
  'answers': ['Galba']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5b_1',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who urged Galba to take the imperial throne from Nero?',
  'multiple_choice_options': [],
  'answers': ['Vindex']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6a_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What daughter of Cadmus was the wife of Athamas?',
  'multiple_choice_options': [],
  'answers': ['INO']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7c_1',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the genitive case is found in the following sentence: Senatōrum togae sunt sordidae.',
  'multiple_choice_options': ['POSSESSIVE'],
  'answers': ['POSSESSIVE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7d_1',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who ruled Italy after the deposition of the boy emperor Romulus Augustulus?',
  'multiple_choice_options': [],
  'answers': ['ODO(V)ACER']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7e_1',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'To what Germanic tribe did Odo(v)acer belong?',
  'multiple_choice_options': [],
  'answers': ['OSTROGOTHS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7f_1',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who was the emperor in the eastern empire at this time?',
  'multiple_choice_options': [],
  'answers': ['ZENO']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_1',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin preposition is the root of “country”?',
  'multiple_choice_options': ['CONTRA', 'CUM', 'ULTRA'],
  'answers': ['CONTRA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9b_1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin adjective is the root of “farm”?',
  'multiple_choice_options': [],
  'answers': ['FIRMUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9c_1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin noun is the root of “salvage”?',
  'multiple_choice_options': [],
  'answers': ['SALŪS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10b_1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Using the verb volō, velle translate “want” into Latin for the following sentence:\nJulia, I don’t know why you want to go to the zoo to see those silly animals.',
  'multiple_choice_options': [],
  'answers': ['VELĪS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10c_1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Using the verb volō, velle translate “want” into Latin for the following sentence:\nI think I want to stay home.',
  'multiple_choice_options': [],
  'answers': ['VELLE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11a_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Name the son of Zeus and Hera who was the god of war.',
  'multiple_choice_options': [],
  'answers': ['ARES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11b_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What other deity appreciated Ares because he increased the inhabitants of his kingdom?',
  'multiple_choice_options': [],
  'answers': ['HADES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12a_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': "Who was Odysseus' father, for whom Penelope was supposedly weaving a shroud?",
  'multiple_choice_options': [],
  'answers': ['LAERTES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which father of one of the suitors was killed by the elderly Laertes?',
  'multiple_choice_options': [],
  'answers': ['EUPITHES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13a_1',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Change aggrediēbantur to subjunctive.',
  'multiple_choice_options': [],
  'answers': ['aggrederentur']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13b_1',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Change aggrederentur to present.',
  'multiple_choice_options': [],
  'answers': ['aggrediuntur']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_1',
  'question_format': 'short_answer',
  'question_content': 'geography',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'In what modern country would all or most of the imperial province of Asia have been located?',
  'multiple_choice_options': [],
  'answers': ['Turkey']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,

In [9]:
len(short_answer)

5201

In [36]:
filtered_df.to_json('../data/structured/certamen_short_answer_unfiltered.json', orient='records', lines=True)

In [37]:
translation_df.to_json('../data/structured/certamen_translation_unfiltered.json', orient='records', lines=True)

1: is question answerable? can context help?

In [19]:
answerable_prompt='''I will give you a question and its answer.
Please decide if the question is answerable based on the given answer, and the added context that the question is related to Roman and Greek history, mythology, and geography, and Latin language and grammar.
Unanswerable questions don't have enough information. For example, if the question references a diagram, map, or table that is not provided, the question is unanswerable.

Please respond simply with "answerable" or "unanswerable".
'''

In [44]:
i = 50

question = short_answer[i]['question']
answer = short_answer[i]['answers'][0]
multiple_choice = short_answer[i]['multiple_choice_options']

question = 'In this diagram of a Greek theater, what is the term for the area indicated by the number 1?'
answer = 'orchestra'
multiple_choice = []

prompt = answerable_prompt 
prompt += f"\nHere is the question: {question}\n"
if multiple_choice:
    choice_str = '\n'.join(multiple_choice)
    prompt += f"Here are the multiple choice options: {choice_str}\n"
prompt += f"Answer: {answer}\n"
print(prompt)

I will give you a question and its answer.
Please decide if the question is answerable based on the given answer, and the added context that the question is related to Roman and Greek history, mythology, and geography, and Latin language and grammar.
Unanswerable questions don't have enough information. For example, if the question references a diagram, map, or table that is not provided, the question is unanswerable.

Please respond simply with "answerable" or "unanswerable".

Here is the question: In this diagram of a Greek theater, what is the term for the area indicated by the number 1?
Answer: orchestra

In [15]:
response = openai_client.responses.create(
    model="gpt-4o",
    input=prompt
)
resp = response.output[0].content[0].text

In [45]:
response = openai_client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )
resp = response.choices[0].message.content

In [46]:
resp

'unanswerable'

In [42]:
# load previous responses
with open('../data/structured/certamen_answerable_responses.json', 'r') as f:
    responses = json.load(f)

In [43]:
len(responses)

1501

In [45]:
len(short_answer)

5201

In [48]:
responses = []

In [ ]:
N = len(short_answer)

# continue from where we left off, or from first error response
for i in range(len(short_answer)):
    #if i < len(responses) and responses[i] != 'error':
    #    continue
    print(i, end=' ')

    q_id = short_answer[i]['question_id']
    question = short_answer[i]['question']
    answer = short_answer[i]['answers'][0]
    multiple_choice = short_answer[i]['multiple_choice_options']

    prompt = answerable_prompt 
    prompt += f"\nHere is the question: {question}\n"
    if multiple_choice:
        choice_str = '\n'.join(multiple_choice)
        prompt += f"Here are the multiple choice options: {choice_str}\n"
    prompt += f"Answer: {answer}\n"
    
    try:
        response = openai_client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant."},
                    {"role": "user", "content": prompt}
                ]
            )
        resp = response.choices[0].message.content
    except Exception as e:
        print(f"Error on question {i}: {e}")
        resp = 'error'
    
    #if responses[i] == 'error':
    #    responses[i] = resp
    #elif i < len(responses):
    responses.append(resp)

    if i % 50 == 0:
        print(f"{i+1}/{N}")
        # dump to json
        with open('../data/structured/certamen_answerable_responses.json', 'w') as f:
            json.dump(responses, f, indent=4)

    sleep(.01)

In [50]:
# dump final responses
with open('../data/structured/certamen_answerable_responses.json', 'w') as f:
    json.dump(responses, f, indent=4)

In [51]:
len(responses)

5201

In [54]:
from collections import Counter
lower_resp = [r.lower() for r in responses]
lower_resp = [r.replace('.', '') for r in lower_resp]
count_resp = Counter(lower_resp)
count_resp

Counter({'answerable': 4643, 'unanswerable': 558})

In [55]:
for i in range(len(short_answer)):
    short_answer[i]['answerable'] = responses[i]

short_answer_df = pd.DataFrame(short_answer)
short_answer_df[short_answer_df['answerable'] == 'unanswerable']

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,answerable
4,NJCL-Certamen,1996,NJCL-Certamen_1996_7a_0,short_answer,grammar,unknown,english,latin,"Give the first person singular, present passiv...",[],[VEHAR],unanswerable
5,NJCL-Certamen,1996,NJCL-Certamen_1996_7b_0,short_answer,grammar,unknown,english,latin,Change vehar to imperfect.,[],[VEHERER],unanswerable
17,NJCL-Certamen,1996,NJCL-Certamen_1996_16c_0,short_answer,translation,unknown,english,latin,Translate into Latin the relative pronoun for ...,[],[CUĪ],unanswerable
35,NJCL-Certamen,1996,NJCL-Certamen_1996_7e_1,short_answer,history,unknown,english,latin,To what Germanic tribe did Odo(v)acer belong?,[],[OSTROGOTHS],unanswerable
36,NJCL-Certamen,1996,NJCL-Certamen_1996_7f_1,short_answer,history,unknown,english,latin,Who was the emperor in the eastern empire at t...,[],[ZENO],unanswerable
...,...,...,...,...,...,...,...,...,...,...,...,...
5167,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_877,short_answer,vocabulary,advanced,english,latin,When this consultant reads an email from his o...,[],[RĒ],unanswerable
5173,NJCL-Certamen,2002,NJCL-Certamen_2002_10_71,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[sojourn, conjure, meridian, circadian, diary]",[CONJURE],unanswerable
5174,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_870,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[vintner, vinyl, vicious, vignette, vinegar]",[VICIOUS],unanswerable
5183,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_878,short_answer,literature,unknown,english,latin,Who had issued this decree?,[],[CREON],unanswerable
5200,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_889,short_answer,mythology,unknown,english,latin,"Identify ""This Guy"" in the visual.",[],[MORPHEUS],unanswerable

In [56]:
unanswerable_df = short_answer_df[short_answer_df['answerable'] == 'unanswerable']

In [57]:
unanswerable_df['question_content'].value_counts()

question_content
vocabulary          143
mythology           109
grammar              86
history              84
geography            40
literature           37
literary_devices     14
translation           7
Name: count, dtype: int64

In [58]:
unanswerable_df[unanswerable_df['question_content'] == 'translation']

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,answerable
17,NJCL-Certamen,1996,NJCL-Certamen_1996_16c_0,short_answer,translation,unknown,english,latin,Translate into Latin the relative pronoun for ...,[],[CUĪ],unanswerable
41,NJCL-Certamen,1996,NJCL-Certamen_1996_10c_1,short_answer,translation,unknown,english,latin,"Using the verb volō, velle translate “want” in...",[],[VELLE],unanswerable
103,NJCL-Certamen,1996,NJCL-Certamen_1996_19c_3,short_answer,translation,unknown,english,latin,"Using cēnō, cēnāre, translate into Latin the v...",[],[CĒNĀRE],unanswerable
237,NJCL-Certamen,1996,NJCL-Certamen_1996_6c_6,short_answer,translation,unknown,english,latin,Translate “yourself’ in this sentence: Quintus...,[],[TIBI],unanswerable
1012,NJCL-Certamen,1996,NJCL-Certamen_1996_8a_31,short_answer,translation,unknown,english,latin,Translate into Latin the word “fly” for the se...,[],[VOLĀVISSE],unanswerable
2142,NJCL-Certamen,2000,NJCL-Certamen_2000_20a_8,short_answer,translation,unknown,english,english,How should one translate the verb form amābō i...,[],[PLEASE],unanswerable
4050,NJCL-Certamen,2002,NJCL-Certamen_2002_13b_50,short_answer,translation,advanced,english,english,The seal also contains the year in which the u...,[],[1820],unanswerable

In [59]:
unanswerable_df[unanswerable_df['question_content'] == 'grammar']

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,answerable
4,NJCL-Certamen,1996,NJCL-Certamen_1996_7a_0,short_answer,grammar,unknown,english,latin,"Give the first person singular, present passiv...",[],[VEHAR],unanswerable
5,NJCL-Certamen,1996,NJCL-Certamen_1996_7b_0,short_answer,grammar,unknown,english,latin,Change vehar to imperfect.,[],[VEHERER],unanswerable
53,NJCL-Certamen,1996,NJCL-Certamen_1996_20b_0,short_answer,grammar,unknown,english,latin,"Give the present active participle of dlrigō, ...",[],[dīrigēns],unanswerable
307,NJCL-Certamen,1996,NJCL-Certamen_1996_19a_8,short_answer,grammar,unknown,english,latin,Give the comparative form of levis.,[],[LEVISSIMUS],unanswerable
308,NJCL-Certamen,1996,NJCL-Certamen_1996_19b_8,short_answer,grammar,unknown,english,latin,Give the superlative form of levis.,[],[LEVIOR],unanswerable
...,...,...,...,...,...,...,...,...,...,...,...,...
4983,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_774,short_answer,grammar,unknown,english,english,You are looking at an inscription that was ori...,[],[Cause],unanswerable
5011,NJCL-Certamen,2002,NJCL-Certamen_2002_4b_50,short_answer,grammar,unknown,english,latin,Make that form fuerim imperfect.,[],[ESSEM],unanswerable
5054,NJCL-Certamen,2002,NJCL-Certamen_2002_18_73,short_answer,grammar,unknown,english,latin,"For the verb gerō, give the singular form of t...",[],[GERERE],unanswerable
5067,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_822,short_answer,grammar,advanced,english,latin,Give the correct form of the adjective prūdēns...,[],[PRŪDENTIA],unanswerable
5080,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_826,short_answer,grammar,unknown,english,english,What one use of the subjunctive mood is found ...,[],[RESULT],unanswerable

In [61]:
# dump unanswerable questions to json
with open('../data/structured/certamen_unanswerable_questions.tsv', 'w') as f:
    unanswerable_df.to_csv(f, sep='\t')
#unanswerable_df.to_json('../data/structured/certamen_unanswerable_questions.json', orient='records', lines=True)

In [63]:
# load edited unanswerable questions
with open('../data/structured/certamen_unanswerable_edits.tsv', 'r') as f:
    unanswerable_df = pd.read_csv(f, sep='\t')

# drop col "unnamed: 0"
unanswerable_df = unanswerable_df.drop(columns=['Unnamed: 0'])
unanswerable_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,answerable,edits
0,NJCL-Certamen,1996,NJCL-Certamen_1996_7a_0,short_answer,grammar,unknown,english,latin,"Give the first person singular, present passiv...",[],['VEHAR'],1,NaN
1,NJCL-Certamen,1996,NJCL-Certamen_1996_7b_0,short_answer,grammar,unknown,english,latin,Change vehar to imperfect.,[],['VEHERER'],1,NaN
2,NJCL-Certamen,1996,NJCL-Certamen_1996_16c_0,short_answer,translation,unknown,english,latin,Translate into Latin the relative pronoun for ...,[],['CUĪ'],1,NaN
3,NJCL-Certamen,1996,NJCL-Certamen_1996_7e_1,short_answer,history,unknown,english,latin,To what Germanic tribe did Odo(v)acer belong?,[],['OSTROGOTHS'],0,NaN
4,NJCL-Certamen,1996,NJCL-Certamen_1996_7f_1,short_answer,history,unknown,english,latin,Who was the emperor in the eastern empire at t...,[],['ZENO'],0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_877,short_answer,vocabulary,advanced,english,latin,When this consultant reads an email from his o...,[],['RĒ'],1,NaN
516,NJCL-Certamen,2002,NJCL-Certamen_2002_10_71,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...",[],['CONJURE'],1,1.0
517,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_870,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...",[],['VICIOUS'],1,1.0
518,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_878,short_answer,literature,unknown,english,latin,Who had issued this decree?,[],['CREON'],0,NaN
519,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_889,short_answer,mythology,unknown,english,latin,"Identify ""This Guy"" in the visual.",[],['MORPHEUS'],0,NaN

In [64]:
# what q ids are unanswerable?
# ids where answerable = 0
unanswerable_ids = unanswerable_df[unanswerable_df['answerable'] == 0]['question_id'].tolist()
unanswerable_ids

['NJCL-Certamen_1996_7e_1',
 'NJCL-Certamen_1996_7f_1',
 'NJCL-Certamen_1996_20b_0',
 'NJCL-Certamen_1996_2a_4',
 'NJCL-Certamen_1996_2b_4',
 'NJCL-Certamen_1996_17c_4',
 'NJCL-Certamen_1996_20c_4',
 'NJCL-Certamen_1996_1a_8',
 'NJCL-Certamen_1996_1b_8',
 'NJCL-Certamen_1996_20c_10',
 'NJCL-Certamen_1996_7c_12',
 'NJCL-Certamen_1996_19b_11',
 'NJCL-Certamen_1996_6c_11',
 'NJCL-Certamen_1996_19b_13',
 'NJCL-Certamen_1996_1a_20',
 'NJCL-Certamen_1996_1b_20',
 'NJCL-Certamen_1996_6c_15',
 'NJCL-Certamen_1996_17a_17',
 'NJCL-Certamen_1996_11_2',
 'NJCL-Certamen_1996_12_2',
 'NJCL-Certamen_1996_12c_17',
 'NJCL-Certamen_1996_14b_19',
 'NJCL-Certamen_1996_11c_22',
 'NJCL-Certamen_1996_10d_0',
 'NJCL-Certamen_1996_5b_33',
 'NJCL-Certamen_1996_8a_17',
 'NJCL-Certamen_1996_8c_17',
 'NJCL-Certamen_1996_1b_39',
 'NJCL-Certamen_1996_7b_31',
 'NJCL-Certamen_1996_13b_29',
 'NJCL-Certamen_1996_15b_30',
 'NJCL-Certamen_1996_15c_30',
 'NJCL-Certamen_1996_7a_42',
 'NJCL-Certamen_1996_7b_41',
 'NJCL-Certamen_1996_10b_31',
 'NJCL-Certamen_1996_16c_29',
 'NJCL-Certamen_1996_19c_30',
 'NJCL-Certamen_1996_20b_30',
 'NJCL-Certamen_1996_20c_28',
 'NJCL-Certamen_1996_16c_31',
 'NJCL-Certamen_1996_20a_31',
 'NJCL-Certamen_1996_10b_34',
 'NJCL-Certamen_1996_11c_34',
 'NJCL-Certamen_1996_16c_32',
 'NJCL-Certamen_1996_9b_40',
 'NJCL-Certamen_1996_16a_34',
 'NJCL-Certamen_1996_16b_34',
 'NJCL-Certamen_1996_7c_41',
 'NJCL-Certamen_1996_19b_34',
 'NJCL-Certamen_1996_6b_43',
 'NJCL-Certamen_1996_18a_36',
 'NJCL-Certamen_1996_18b_36',
 'NJCL-Certamen_1996_1a_56',
 'NJCL-Certamen_1996_1b_56',
 'NJCL-Certamen_1996_1c_54',
 'NJCL-Certamen_1996_11a_41',
 'NJCL-Certamen_1996_11b_41',
 'NJCL-Certamen_1996_11c_39',
 'NJCL-Certamen_1996_17b_40',
 'NJCL-Certamen_1996_2_7',
 'NJCL-Certamen_1996_9c_46',
 'NJCL-Certamen_1996_16a_42',
 'NJCL-Certamen_1996_16b_42',
 'NJCL-Certamen_1996_16c_40',
 'NJCL-Certamen_1996_3b_63',
 'NJCL-Certamen_1996_8b_44',
 'NJCL-Certamen_1996_18b_45',
 'NJCL-Certamen_1996_3a_64',
 'NJCL-Certamen_1996_3b_64',
 'NJCL-Certamen_1996_10a_47',
 'NJCL-Certamen_1996_6a_54',
 'NJCL-Certamen_1996_6b_53',
 'NJCL-Certamen_1996_6c_51',
 'NJCL-Certamen_1996_19b_46',
 'NJCL-Certamen_1996_3b_68',
 'NJCL-Certamen_1996_19b_47',
 'NJCL-Certamen_1996_2_10',
 'NJCL-Certamen_1996_10b_50',
 'NJCL-Certamen_1996_20_9',
 'NJCL-Certamen_1996_22_3',
 'NJCL-Certamen_1996_7_13',
 'NJCL-Certamen_1996_6c_54',
 'NJCL-Certamen_1996_21b_3',
 'NJCL-Certamen_1996_14a_54',
 'NJCL-Certamen_1996_14b_54',
 'NJCL-Certamen_1996_14c_52',
 'NJCL-Certamen_1996_18a_55',
 'NJCL-Certamen_1996_18b_55',
 'NJCL-Certamen_1996_9b_61',
 'NJCL-Certamen_1996_9c_61',
 'NJCL-Certamen_1996_16c_53',
 'NJCL-Certamen_1996_3b_76',
 'NJCL-Certamen_1996_20b_53',
 'NJCL-Certamen_1996_20c_49',
 'NJCL-Certamen_1996_9b_63',
 'NJCL-Certamen_1999_3b_1',
 'NJCL-Certamen_1999_3c_1',
 'NJCL-Certamen_1999_6b_1',
 'NJCL-Certamen_1999_7b_4',
 'NJCL-Certamen_1999_16a_4',
 'NJCL-Certamen_2000_4c_1',
 'NJCL-Certamen_2000_5_2',
 'NJCL-Certamen_2000_5a_3',
 'NJCL-Certamen_2000_5b_3',
 'NJCL-Certamen_2000_11a_2',
 'NJCL-Certamen_2000_11b_2',
 'NJCL-Certamen_2000_6b_4',
 'NJCL-Certamen_2000_7b_4',
 'NJCL-Certamen_2000_9b_7',
 'NJCL-Certamen_2000_9c_6',
 'NJCL-Certamen_2000_14a_5',
 'NJCL-Certamen_2000_14b_5',
 'NJCL-Certamen_2000_10b_9',
 'NJCL-Certamen_2000_5_4',
 'NJCL-Certamen_2000_12b_10',
 'NJCL-Certamen_2000_8_5',
 'NJCL-Certamen_2000_3b_20',
 'NJCL-Certamen_2000_16b_9',
 'NJCL-Certamen_2000_1c_20',
 'NJCL-Certamen_2000_10b_15',
 'NJCL-Certamen_2000_7c_17',
 'NJCL-Certamen_2000_3b_27',
 'NJCL-Certamen_2000_4c_22',
 'NJCL-Certamen_2000_6c_18',
 'NJCL-Certamen_2000_9a_19',
 'NJCL-Certamen_2000_11b_22',
 'NJCL-Certamen_2000_15b_20',
 'NJCL-Certamen_2000_20d_0',
 'NJCL-Certamen_2000_16d_0',
 'NJCL-Certamen_2000_6b_28',
 'NJCL-Certamen_2000_14c_18',
 'NJCL-Certamen_2000_19b_20',
 'NJCL-Certamen_2000_6a_30',
 'NJCL-Certamen_2000_16c_22',
 'NJCL-Certamen_2002_2b_0',
 'NJCL-Certamen_2002_11c_0',
 'NJCL-Certamen_2002_18a_0',
 'NJCL-Certamen_2002_6b_2',
 'NJCL-Certamen_2002_6c_2',
 'NJCL-Certamen_2002_15b_1',
 'NJCL-Certamen_2002_11a_3',
 'NJCL-Certamen_2002_11c_3',
 'NJCL-Certamen_2002_11b_4',
 'NJCL-Certamen_2002_11c_4',
 'NJCL-Certamen_2002_5_2',
 'NJCL-Certamen_2002_17b_6',
 'NJCL-Certamen_2002_17c_6',
 'NJCL-Certamen_2002_11a_6',
 'NJCL-Certamen_2002_4a_7',
 'NJCL-Certamen_2002_4b_7',
 'NJCL-Certamen_2002_7b_8',
 'NJCL-Certamen_2002_11b_9',
 'NJCL-Certamen_2002_11c_9',
 'NJCL-Certamen_2002_15a_9',
 'NJCL-Certamen_2002_15b_9',
 'NJCL-Certamen_2002_15c_9',
 'NJCL-Certamen_2002_17c_10',
 'NJCL-Certamen_2002_15c_10',
 'NJCL-Certamen_2002_14a_13',
 'NJCL-Certamen_2002_14b_13',
 'NJCL-Certamen_2002_18b_14',
 'NJCL-Certamen_2002_12a_14',
 'NJCL-Certamen_2002_12b_14',
 'NJCL-Certamen_2002_14b_18',
 'NJCL-Certamen_2002_14c_17',
 'NJCL-Certamen_2002_17_4',
 'NJCL-Certamen_2002_17b_18',
 'NJCL-Certamen_2002_16a_17',
 'NJCL-Certamen_2002_16b_17',
 'NJCL-Certamen_2002_16c_16',
 'NJCL-Certamen_2002_11a_23',
 'NJCL-Certamen_2002_11b_23',
 'NJCL-Certamen_2002_11c_20',
 'NJCL-Certamen_2002_8b_21',
 'NJCL-Certamen_2002_8c_20',
 'NJCL-Certamen_2002_5c_26',
 'NJCL-Certamen_2002_5_5',
 'NJCL-Certamen_2002_13a_27',
 'NJCL-Certamen_2002_7b_28',
 'NJCL-Certamen_2002_9b_33',
 'NJCL-Certamen_2002_11a_32',
 'NJCL-Certamen_2002_2a_32',
 'NJCL-Certamen_2002_1c_33',
 'NJCL-Certamen_2002_17a_34',
 'NJCL-Certamen_2002_17b_33',
 'NJCL-Certamen_2002_19b_33',
 'NJCL-Certamen_2002_B1a_0',
 'NJCL-Certamen_2002_B1b_0',
 'NJCL-Certamen_2002_B1c_0',
 'NJCL-Certamen_2002_B1d_0',
 'NJCL-Certamen_2002_B1_21',
 'NJCL-Certamen_2002_9b_41',
 'NJCL-Certamen_2002_11_15',
 'NJCL-Certamen_2002_B2_105',
 'NJCL-Certamen_2002_B2_112',
 'NJCL-Certamen_2002_B1_128',
 'NJCL-Certamen_2002_B2_129',
 'NJCL-Certamen_2002_B1_131',
 'NJCL-Certamen_2002_B2_132',
 'NJCL-Certamen_2002_B1_196',
 'NJCL-Certamen_2002_B1_240',
 'NJCL-Certamen_2002_13a_49',
 'NJCL-Certamen_2002_10_28',
 'NJCL-Certamen_2002_21b_2',
 'NJCL-Certamen_2002_15_26',
 'NJCL-Certamen_2002_B2_278',
 'NJCL-Certamen_2002_B1_279',
 'NJCL-Certamen_2002_B2_297',
 'NJCL-Certamen_2002_B1_297',
 'NJCL-Certamen_2002_6b_45',
 'NJCL-Certamen_2002_18a_49',
 'NJCL-Certamen_2002_6_34',
 'NJCL-Certamen_2002_B1_368',
 'NJCL-Certamen_2002_B2_373',
 'NJCL-Certamen_2002_B1_404',
 'NJCL-Certamen_2002_B2_433',
 'NJCL-Certamen_2002_11c_35',
 'NJCL-Certamen_2002_B1_459',
 'NJCL-Certamen_2002_B2_465',
 'NJCL-Certamen_2002_B2_477',
 'NJCL-Certamen_2002_15a_50',
 'NJCL-Certamen_2002_5a_54',
 'NJCL-Certamen_2002_B2_506',
 'NJCL-Certamen_2002_B2_518',
 'NJCL-Certamen_2002_8_53',
 'NJCL-Certamen_2002_B2_529',
 'NJCL-Certamen_2002_B1_529',
 'NJCL-Certamen_2002_B1_548',
 'NJCL-Certamen_2002_B2_556',
 'NJCL-Certamen_2002_B1_565',
 'NJCL-Certamen_2002_B1_594',
 'NJCL-Certamen_2002_6a_50',
 'NJCL-Certamen_2002_12_57',
 'NJCL-Certamen_2002_B1_609',
 'NJCL-Certamen_2002_B2_619',
 'NJCL-Certamen_2002_B1_649',
 'NJCL-Certamen_2002_B2_663',
 'NJCL-Certamen_2002_1c_64',
 'NJCL-Certamen_2002_11_60',
 'NJCL-Certamen_2002_B2a_2',
 'NJCL-Certamen_2002_B2b_5',
 'NJCL-Certamen_2002_11b_55',
 'NJCL-Certamen_2002_B1_701',
 'NJCL-Certamen_2002_B2_715',
 'NJCL-Certamen_2002_B2_721',
 'NJCL-Certamen_2002_11_66',
 'NJCL-Certamen_2002_B1_759',
 'NJCL-Certamen_2002_B2_768',
 'NJCL-Certamen_2002_15a_56',
 'NJCL-Certamen_2002_B2_773',
 'NJCL-Certamen_2002_14b_62',
 'NJCL-Certamen_2002_B1_774',
 'NJCL-Certamen_2002_B1_809',
 'NJCL-Certamen_2002_B2_818',
 'NJCL-Certamen_2002_B2_827',
 'NJCL-Certamen_2002_B1_826',
 'NJCL-Certamen_2002_B1_837',
 'NJCL-Certamen_2002_B2_846',
 'NJCL-Certamen_2002_B1_878',
 'NJCL-Certamen_2002_B1_889']

In [65]:
len(unanswerable_ids)

260

In [67]:
# ids where edit = 1
update_ids = unanswerable_df[unanswerable_df['edits'] == 1]['question_id'].tolist()
update_ids

30

In [68]:
len(short_answer_df)

5201

In [69]:
# drop unanswerable from short_answer_df
short_answer_df = short_answer_df[~short_answer_df['question_id'].isin(unanswerable_ids)]
len(short_answer_df)

4941

In [72]:
short_answer_dict = short_answer_df.to_dict(orient='records')
for i, dict_ in enumerate(short_answer_dict):
    this_id = dict_['question_id']
    if this_id in update_ids:
        # find the row in unanswerable_df
        new_row = unanswerable_df[unanswerable_df['question_id'] == this_id]
        # drop the "edits" column
        new_row = new_row.drop(columns=['edits'])
        # turn into dict
        new_row = new_row.to_dict(orient='records')[0]
        # update the row
        short_answer_dict[i] = new_row
    # delete the "answerable" key 
    del short_answer_dict[i]['answerable']

short_answer_dict

[{'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1a_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What name was given to the large agricultural estates which resulted from the distribution of the ager publicus in the 2nd century B.C.?',
  'multiple_choice_options': [],
  'answers': ['LATIFUNDIA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1b_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What was the manager or overseer of a latifundia called?',
  'multiple_choice_options': [],
  'answers': ['VILICUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4a_0',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'latin',
  'answer_language': 'latin',
  'question': 'Quod animal facit mel?',
  'multiple_choice_options': [],
  'answers': ['APIS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6b_0',
  'question_format': 'short_answer',
  'question_content': 'literature',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': "Who was Odysseus' long-suffering wife?",
  'multiple_choice_options': [],
  'answers': ['Penelope']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7a_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Give the first person singular, present passive subjunctive of vehō.',
  'multiple_choice_options': [],
  'answers': ['VEHAR']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7b_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Change vehar to imperfect.',
  'multiple_choice_options': [],
  'answers': ['VEHERER']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7c_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Change veherer to pluperfect active.',
  'multiple_choice_options': [],
  'answers': ['VEXISSEM']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7d_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What tense is iaciēs?',
  'multiple_choice_options': [],
  'answers': ['FUTURE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7e_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What tense is iaciās?',
  'multiple_choice_options': [],
  'answers': ['PRESENT']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7f_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What tense is iacēs?',
  'multiple_choice_options': [],
  'answers': ['PRESENT']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10a_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who was the Greek god of prophecy?',
  'multiple_choice_options': [],
  'answers': ['APOLLO']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10b_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Where did Apollo establish his main oracle in Greece?',
  'multiple_choice_options': [],
  'answers': ['DELPHI']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who was the father of Iphicles?',
  'multiple_choice_options': [],
  'answers': ['AMPHITRYON']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who forbade the memory of his brother and ordered the erasure of his name from all inscriptions in AD 212?',
  'multiple_choice_options': [],
  'answers': ['CARACALLA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15b_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Name the brother whom Caracalla had murdered.',
  'multiple_choice_options': [],
  'answers': ['GETA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_16a_0',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate into Latin the relative pronoun for the following English sentence: Julia, whose mother is rich, is the daughter of a senator.',
  'multiple_choice_options': [],
  'answers': ['CUIUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_16b_0',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate into Latin the relative pronoun for the following English sentence: The soldier did not like the others with whom he was traveling.',
  'multiple_choice_options': [],
  'answers': ['QUIBUS(CUM)']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_16c_0',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate into Latin the relative pronoun for the following English sentence: The farm, of which Horace was in charge, is burning to the ground.',
  'multiple_choice_options': [],
  'answers': ['CUĪ']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17a_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which centaur tried to kidnap Deianira, the wife of Hercules?',
  'multiple_choice_options': [],
  'answers': ['NESSUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17b_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'According to Ovid, who was the father of Nessus?',
  'multiple_choice_options': [],
  'answers': ['IXION']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_18a_0',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Latin is an inflected language. What is the meaning of the verb at the root of “inflected”?',
  'multiple_choice_options': [],
  'answers': ['BEND']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_18c_0',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'In Latin, as in English, there are three degrees of comparison. What is the meaning of the adjective at the root of “comparison”?',
  'multiple_choice_options': [],
  'answers': ['EQUAL']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_19a_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who gave shelter to Danae and her son Perseus?',
  'multiple_choice_options': [],
  'answers': ['Dictys']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_19b_0',
  'question_format': 'short_answer',
  'question_content': 'geography',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'On what island did Dictys live?',
  'multiple_choice_options': [],
  'answers': ['Seriphus']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_19c_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': "Name Dictys' brother who wanted to marry Danae.",
  'multiple_choice_options': [],
  'answers': ['Polydectes']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What foreign enemy general campaigned in Italy for 16 years, but was unable to capture Rome?',
  'multiple_choice_options': [],
  'answers': ['HANNIBAL']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3b_1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What household cooking substance is derived from ācer?',
  'multiple_choice_options': [],
  'answers': ['VINEGAR']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3c_1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What is the Latin word for vinegar?',
  'multiple_choice_options': [],
  'answers': ['ACĒTUM']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4a_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What great Trojan hero was the husband of Andromache?',
  'multiple_choice_options': [],
  'answers': ['HECTOR']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4b_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Greek hero killed Hector?',
  'multiple_choice_options': [],
  'answers': ['ACHILLES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5a_1',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who was the oldest of the four emperors proclaimed in A. D. 69?',
  'multiple_choice_options': [],
  'answers': ['Galba']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5b_1',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who urged Galba to take the imperial throne from Nero?',
  'multiple_choice_options': [],
  'answers': ['Vindex']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6a_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What daughter of Cadmus was the wife of Athamas?',
  'multiple_choice_options': [],
  'answers': ['INO']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7c_1',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the genitive case is found in the following sentence: Senatōrum togae sunt sordidae.',
  'multiple_choice_options': ['POSSESSIVE'],
  'answers': ['POSSESSIVE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7d_1',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who ruled Italy after the deposition of the boy emperor Romulus Augustulus?',
  'multiple_choice_options': [],
  'answers': ['ODO(V)ACER']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_1',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin preposition is the root of “country”?',
  'multiple_choice_options': ['CONTRA', 'CUM', 'ULTRA'],
  'answers': ['CONTRA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9b_1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin adjective is the root of “farm”?',
  'multiple_choice_options': [],
  'answers': ['FIRMUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9c_1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin noun is the root of “salvage”?',
  'multiple_choice_options': [],
  'answers': ['SALŪS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10b_1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Using the verb volō, velle translate “want” into Latin for the following sentence:\nJulia, I don’t know why you want to go to the zoo to see those silly animals.',
  'multiple_choice_options': [],
  'answers': ['VELĪS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10c_1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Using the verb volō, velle translate “want” into Latin for the following sentence:\nI think I want to stay home.',
  'multiple_choice_options': [],
  'answers': ['VELLE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11a_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Name the son of Zeus and Hera who was the god of war.',
  'multiple_choice_options': [],
  'answers': ['ARES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11b_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What other deity appreciated Ares because he increased the inhabitants of his kingdom?',
  'multiple_choice_options': [],
  'answers': ['HADES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12a_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': "Who was Odysseus' father, for whom Penelope was supposedly weaving a shroud?",
  'multiple_choice_options': [],
  'answers': ['LAERTES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which father of one of the suitors was killed by the elderly Laertes?',
  'multiple_choice_options': [],
  'answers': ['EUPITHES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13a_1',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Change aggrediēbantur to subjunctive.',
  'multiple_choice_options': [],
  'answers': ['aggrederentur']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13b_1',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Change aggrederentur to present.',
  'multiple_choice_options': [],
  'answers': ['aggrediuntur']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_1',
  'question_format': 'short_answer',
  'question_content': 'geography',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'In what modern country would all or most of the imperial province of Asia have been located?',
  'multiple_choice_options': [],
  'answers': ['Turkey']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15b_1',
  'question_format': 'short_answer',
  'question_content': 'geography',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'In what modern country would all or most of the imperial province of Baetica have been located?',
  'multiple_choice_options': [],
  'answers': ['Spain']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15c_1',
  'question_format': 'short_answer',
  'question_content': 'geography',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'In what modern country would all or most of the imperial province of Macedonia have been located?',

In [73]:
len(short_answer_dict)

4941

In [74]:
with open('../data/structured/certamen_short_answer_filtered_answerable.json', 'w') as f:
    json.dump(short_answer_dict, f, indent=4)

In [ ]:
# dump remaining responses
with open('../data/structured/certamen_answerable_responses.json', 'w') as f:
    json.dump(responses, f, indent=4)

filtering translation questions

In [6]:
# load translation questions (jsonl)
with open('../data/structured/certamen_translation_unfiltered.json', 'r') as f:
    translation_dicts = [json.loads(line) for line in f]

translation_df = pd.DataFrame(translation_dicts)
translation_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers
0,NJCL-Certamen,1996,NJCL-Certamen_1996_11b_0,short_answer,translation,unknown,english,english,Translate adeō as an adverb.,[],"[SO FAR, SO MUCH, MOREOVER]"
1,NJCL-Certamen,1996,NJCL-Certamen_1996_11c_0,short_answer,translation,unknown,english,english,Translate adeō as a verb.,[],[I APPROACH]
2,NJCL-Certamen,1996,NJCL-Certamen_1996_16a_0,short_answer,translation,unknown,english,latin,Translate into Latin the relative pronoun for ...,[],[CUIUS]
3,NJCL-Certamen,1996,NJCL-Certamen_1996_16b_0,short_answer,translation,unknown,english,latin,Translate into Latin the relative pronoun for ...,[],[QUIBUS(CUM)]
4,NJCL-Certamen,1996,NJCL-Certamen_1996_16c_0,short_answer,translation,unknown,english,latin,Translate into Latin the relative pronoun for ...,[],[CUĪ]
...,...,...,...,...,...,...,...,...,...,...,...
1128,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_865,short_answer,translation,advanced,english,english,Translate the following sentence into English:...,[],[IT IS NOT CONVENIENT / COMFORTABLE / FITTING ...
1129,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_874,short_answer,translation,advanced,english,english,Translate the following sentence into English:...,[],[IT IS PROPER / BECOMING / FITTING FOR ALL / E...
1130,NJCL-Certamen,2002,NJCL-Certamen_2002_13_77,short_answer,translation,advanced,latin,english,Translate the following sentence into English:...,[],[My brother saw the dog wounded by a rock]
1131,NJCL-Certamen,2002,NJCL-Certamen_2002_13a_71,short_answer,translation,advanced,latin,english,Translate the following sentence into English:...,[],"[Having seen the wounded dog, my brother wante..."
1132,NJCL-Certamen,2002,NJCL-Certamen_2002_13b_71,short_answer,translation,advanced,latin,english,Translate the following sentence into English:...,[],[A doctor was sent as help to the dog as quick...

In [9]:
# translation >= 3 words
long_translation_df = translation_df[translation_df['answers'].apply(lambda x: len(x[0].split()) >= 3)]
long_translation_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers
8,NJCL-Certamen,1996,NJCL-Certamen_1996_8a_0,short_answer,translation,unknown,english,english,Translate the motto of Alabama: Audēmus iūra n...,[],"[WE DARE TO DEFEND OUR RIGHTS, WE DARE TO DEFE..."
9,NJCL-Certamen,1996,NJCL-Certamen_1996_8b_0,short_answer,translation,unknown,english,english,Translate the motto of the Dominion of Canada:...,[],[FROM SEA TO SEA]
10,NJCL-Certamen,1996,NJCL-Certamen_1996_8c_0,short_answer,translation,unknown,english,english,Translate the motto of Wellesley College: nōn ...,[],"[NOT TO BE SERVED, NOT TO BE MANAGED, BUT TO S..."
16,NJCL-Certamen,1996,NJCL-Certamen_1996_15a_3,short_answer,translation,unknown,english,english,Translate into English the following maxim of ...,[],"[If you want peace, prepare for war]"
17,NJCL-Certamen,1996,NJCL-Certamen_1996_15b_3,short_answer,translation,unknown,english,english,Translate into English the following quotation...,[],"[Divine nature gave (us) the fields, human art..."
...,...,...,...,...,...,...,...,...,...,...,...
1128,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_865,short_answer,translation,advanced,english,english,Translate the following sentence into English:...,[],[IT IS NOT CONVENIENT / COMFORTABLE / FITTING ...
1129,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_874,short_answer,translation,advanced,english,english,Translate the following sentence into English:...,[],[IT IS PROPER / BECOMING / FITTING FOR ALL / E...
1130,NJCL-Certamen,2002,NJCL-Certamen_2002_13_77,short_answer,translation,advanced,latin,english,Translate the following sentence into English:...,[],[My brother saw the dog wounded by a rock]
1131,NJCL-Certamen,2002,NJCL-Certamen_2002_13a_71,short_answer,translation,advanced,latin,english,Translate the following sentence into English:...,[],"[Having seen the wounded dog, my brother wante..."
1132,NJCL-Certamen,2002,NJCL-Certamen_2002_13b_71,short_answer,translation,advanced,latin,english,Translate the following sentence into English:...,[],[A doctor was sent as help to the dog as quick...

In [37]:
# long translation  df with more than 1 answer
long_translation_df[long_translation_df['answers'].apply(lambda x: len(x) > 1)]

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers
8,NJCL-Certamen,1996,NJCL-Certamen_1996_8a_0,short_answer,translation,unknown,english,english,Translate the motto of Alabama: Audēmus iūra n...,[],"[WE DARE TO DEFEND OUR RIGHTS, WE DARE TO DEFE..."
10,NJCL-Certamen,1996,NJCL-Certamen_1996_8c_0,short_answer,translation,unknown,english,english,Translate the motto of Wellesley College: nōn ...,[],"[NOT TO BE SERVED, NOT TO BE MANAGED, BUT TO S..."
18,NJCL-Certamen,1996,NJCL-Certamen_1996_15c_3,short_answer,translation,unknown,english,english,Translate into English the following quotation...,[],"[What an outstanding guard of sheep, the wolf,..."
19,NJCL-Certamen,1996,NJCL-Certamen_1996_16_0,short_answer,translation,unknown,english,english,Translate the Caesarean idiom dolōrem capere.,[],"[To be grieved, Suffer grief, Grieve]"
25,NJCL-Certamen,1996,NJCL-Certamen_1996_6c_3,short_answer,translation,unknown,english,english,Translate this adage into English: Nonne habēs...,[],[SURELY YOU HAVE SOMETHING (WHICH) YOU WANT TO...
...,...,...,...,...,...,...,...,...,...,...,...
1109,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_834,short_answer,translation,unknown,english,english,Translate the following sentence into English:...,[],"[JULIA IS THE PRETTY DAUGHTER OF THE DICTATOR,..."
1110,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_843,short_answer,translation,unknown,english,english,Translate the following sentence into English:...,[],"[LUCIUS WAS A VERY FAMOUS COOK, LUCIUS WAS THE..."
1119,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_848,short_answer,translation,advanced,english,english,Translate the Latin motto for St. Mary’s Colle...,[],"[STANDARD OF FAITH, SIGN OF FAITH, SIGNAL OF F..."
1121,NJCL-Certamen,2002,NJCL-Certamen_2002_17_79,short_answer,translation,unknown,english,english,Translate the following sentence into English:...,[],[SURELY THE SOLDIERS ARE MORE BRAVE THAN GLADI...
1122,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_862,short_answer,translation,unknown,english,english,Translate the following sentence into English:...,[],[SURELY THE SENATOR’S HOUSE IS NOT BIGGER THAN...

In [11]:
# which answers have multiple possible answers? we should add them as alternative translations
# look for answers that have / or () in them

multiple_refs_df = long_translation_df[long_translation_df['answers'].apply(lambda x: '/' in x[0] or '(' in x[0])]
multiple_refs_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers
17,NJCL-Certamen,1996,NJCL-Certamen_1996_15b_3,short_answer,translation,unknown,english,english,Translate into English the following quotation...,[],"[Divine nature gave (us) the fields, human art..."
25,NJCL-Certamen,1996,NJCL-Certamen_1996_6c_3,short_answer,translation,unknown,english,english,Translate this adage into English: Nonne habēs...,[],[SURELY YOU HAVE SOMETHING (WHICH) YOU WANT TO...
30,NJCL-Certamen,1996,NJCL-Certamen_1996_20b_3,short_answer,translation,unknown,latin,english,Dīc mihi Anglicē cur certāmen amēs.,[],[PLAYER SHOULD TELL YOU WHY HE (SHE) LOVES CER...
31,NJCL-Certamen,1996,NJCL-Certamen_1996_20c_3,short_answer,translation,unknown,latin,english,Dīcite mihi Anglicē unde vēnerītis.,[],[ALL PLAYERS SHOULD SAY WHERE (WHAT STATE) THE...
38,NJCL-Certamen,1996,NJCL-Certamen_1996_16a_6,short_answer,translation,unknown,english,english,Translate: Primā lūce servi ē villā in agrōs ī...,[],"[AT DAWN, THE SLAVES WENT OUT OF THE HOUSE (AN..."
...,...,...,...,...,...,...,...,...,...,...,...
1127,NJCL-Certamen,2002,NJCL-Certamen_2002_3_78,short_answer,translation,advanced,english,english,Translate the following sentence into English:...,[],[IT IS NECSESARY FOR YOU TO / YOU MUST LISTEN ...
1128,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_865,short_answer,translation,advanced,english,english,Translate the following sentence into English:...,[],[IT IS NOT CONVENIENT / COMFORTABLE / FITTING ...
1129,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_874,short_answer,translation,advanced,english,english,Translate the following sentence into English:...,[],[IT IS PROPER / BECOMING / FITTING FOR ALL / E...
1131,NJCL-Certamen,2002,NJCL-Certamen_2002_13a_71,short_answer,translation,advanced,latin,english,Translate the following sentence into English:...,[],"[Having seen the wounded dog, my brother wante..."
1132,NJCL-Certamen,2002,NJCL-Certamen_2002_13b_71,short_answer,translation,advanced,latin,english,Translate the following sentence into English:...,[],[A doctor was sent as help to the dog as quick...

In [12]:
multiple_refs_dict = multiple_refs_df.to_dict(orient="records")
multiple_refs_dict

[{'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15b_3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate into English the following quotation from Tibullus: Dīvīna nātūra dedit agrōs, ars hūmāna aedificāvit urbēs.',
  'multiple_choice_options': [],
  'answers': ['Divine nature gave (us) the fields, human art built the cities']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6c_3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate this adage into English: Nonne habēs aliquid quod mihi monstrāre vīs?',
  'multiple_choice_options': [],
  'answers': ['SURELY YOU HAVE SOMETHING (WHICH) YOU WANT TO SAY TO SHOW ME',
   'YOU HAVE SOMETHING (WHICH) YOU WANT TO SHOW ME, DON’T YOU?']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20b_3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'latin',
  'answer_language': 'english',
  'question': 'Dīc mihi Anglicē cur certāmen amēs.',
  'multiple_choice_options': [],
  'answers': ['PLAYER SHOULD TELL YOU WHY HE (SHE) LOVES CERTAMEN']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20c_3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'latin',
  'answer_language': 'english',
  'question': 'Dīcite mihi Anglicē unde vēnerītis.',
  'multiple_choice_options': [],
  'answers': ['ALL PLAYERS SHOULD SAY WHERE (WHAT STATE) THEY’RE FROM']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_16a_6',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate: Primā lūce servi ē villā in agrōs īvērunt.',
  'multiple_choice_options': [],
  'answers': ['AT DAWN, THE SLAVES WENT OUT OF THE HOUSE (AND) INTO THE FIELDS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5b_9',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate the following Latin sentence into English:\nIlle, quōcum iter faciēbas nuntium necāvit.',
  'multiple_choice_options': [],
  'answers': ['That man with whom you were journeying (marching or journeyed / marched) killed the messenger.']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5c_8',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate the following Latin sentence into English:\nPuerī, quōs apud Marcum vīdistī, sunt fīliī senātōris.',
  'multiple_choice_options': [],
  'answers': ['The boys whom you saw at Marcus’ house (in Marcus’ presence) are sons of a senator.']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_19_0',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate into English: Multī dominī Rōmānī servōs bene cūrābant.',
  'multiple_choice_options': [],
  'answers': ['Many Roman masters cared well for (their) slaves']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1a_11',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Say in Latin : Where are the horses of the master?',
  'multiple_choice_options': [],
  'answers': ['UBI SUNT MAGISTRĪ (DOMINĪ) EQUĪ (or CABALLĪ)?']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1b_11',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Say in Latin: The boys do not want to stay at home.',
  'multiple_choice_options': [],
  'answers': ['PUERĪ DOMĪ MANĒRE NŌLUNT / NŌN CUPIUNT / NŌN DĒSĪDERANT']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1c_11',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Say in Latin: My friend was captured by pirates.',
  'multiple_choice_options': [],
  'answers': ['MEUS(-A) AMICUS(-A) Ā PĪRĀTĪS CAPTUS(-A) EST, RAPTUS(-A) EST, etc.']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_9',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate the idiom vim facere.',
  'multiple_choice_options': [],
  'answers': ['To use violence (force)']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13b_12',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate into English: Tribus horīs mīlitibus vincendum est.',
  'multiple_choice_options': [],
  'answers': ['THE SOLDIERS MUST WIN (WITH)IN THREE HOURS',
   'IT MUST BE WON BY THE SOLDIERS (WITH)IN THREE HOURS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_8a_6',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate: Si quis vestrum amorem invēneris, beatus eris.',
  'multiple_choice_options': [],
  'answers': ['IF ANY(one) OF YOU FIND(S) (SHALL HAVE FOUND) LOVE, YOU WILL BE HAPPY (BLESSED)']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_8b_6',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate: Sī quis vestrum amōrem invenias, beatus sīs.',
  'multiple_choice_options': [],
  'answers': ['IF ANY(one) OF YOU SHOULD FIND LOVE, YOU WOULD BE HAPPY (BLESSED) or IF ANY(one) OF YOU FOUND LOVE, YOU WOULD BE HAPPY (BLESSED)']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1a_19',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate into English: Negant sē servōs fustibus verberāvisse.',
  'multiple_choice_options': [],
  'answers': ['THEY DENY THAT THEY BEAT (HAVE BEATEN) THE SLAVES WITH CLUBS',
   'THEY SAY THAT THEY DID NOT BEAT (HAVE NOT BEATEN) THE SLAVES WITH CLUBS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1c_19',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate into English: Scīmus eōs homicīdiī argūtum īrī.',
  'multiple_choice_options': [],
  'answers': ['WE KNOW THAT THEY WILL BE CHARGED WITH MURDER / HOMICIDE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10b_15',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate the Ciceronian idiom lēgem rōgāre.',
  'multiple_choice_options': [],
  'answers': ['TO PROPOSE / INTRODUCE A LAW']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10c_14',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate the Ciceronian idiom id temporis.',
  'multiple_choice_options': [],
  'answers': ['AT THAT TIME / THEN']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5b_24',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate: Mūs rusticus nescīvit quō modō urbānus fieret.',
  'multiple_choice_options': [],
  'answers': ['THE COUNTRY MOUSE DIDN’T KNOW HOW TO BECOME CITIFIED / SOPHISTICATED / POLISHED']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5c_23',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate: Mūs rusticus erat tam crūdus ut urbs eī nōn placēret.',
  'multiple_choice_options': [],
  'answers': ['THE COUNTRY MOUSE WAS SO UNREFINED THAT HE DIDN’T LIKE THE CITY (THAT THE CITY WAS NOT PLEASING TO HIM)']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4b_25',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate: Poētae ingeniōsī scrībunt carmina quae audienda sunt.',
  'multiple_choice_options': [],
  'answers': ['CRAFTY / TALENTED POETS WRITE POEMS WHICH OUGHT/MUST BE HEARD']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12a_22',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate this sentence: Quid Lucius spectat?',
  'multiple_choice_options': [],
  'answers': ['WHAT IS LUCIUS LOOKING AT / WATCHING?']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12b_21',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate this sentence: Cūr militēs currēbant?',
  'multiple_choice_options': [],
  'answers': ['WHY WERE THE SOLDIERS RUNNING? / WHY DID THE SOLDIERS RUN?']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13a_24',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate: Ego certē meum officium cognoscō.',
  'multiple_choice_options': [],
  'answers': ['I CERTAINLY KNOW / RECOGNIZE / UNDERSTAND / MY DUTY / OFFICE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20a_22',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate: Populus semper pugnābit prō patriā.',
  'multiple_choice_options': [],
  'answers': ['The people will always fight for (their) country']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20b_22',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate: Mundum vidēre est bene vīvere.',
  'multiple_choice_options': [],
  'answers': ['Seeing (to see) the world is living well (to live well)']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20c_22',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate: Rōmānī saepe volēbant spectāre lūdōs in arēnā.',
  'multiple_choice_options': [],
  'answers': ['Romans often were wanting / wanted to watch games in the arena']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4a_33',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate this sentence: Cūr mātrēs suīs līberīs nōn crēdunt?',
  'multiple_choice_options': [],
  'answers': ['WHY DO MOTHERS NOT BELIEVE / TRUST THEIR CHILDREN?']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4c_33',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate this sentence: Multī crēdunt adulēscentēs numquam cogitāre.',
  'multiple_choice_options': [],
  'answers': ['MANY BELIEVE THAT ADOLESCENTS/TEENAGERS NEVER THINK']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_24',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Say in Latin “twenty-one.”',
  'multiple_choice_options': [],
  'answers': ['VĪGINTĪ (ET) ŪNUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1c_36',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate amor in two different ways.',
  'multiple_choice_options': [],
  'answers': ['LOVE (the noun)', 'I AM LOVED']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_25',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'The phrase “mundus vult dēcipī et dēcipiātur” figuratively means “There’s a sucker born every minute.” What does it literally mean?',
  'multiple_choice_options': [],
  'answers': ['THE WORLD WANTS TO BE DECEIVED, AND LET / MAY IT BE DECEIVED']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_18b_27',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'latin',
  'answer_language': 'english',
  'question': 'Translate: Nōn dubitāvērunt quīn difficile esset.',
  'multiple_choice_options': [],
  'answers': ['THEY DIDN’T DOUBT (BUT) THAT IT WAS / WOULD BE / MIGHT BE DIFFICULT.']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_18c_26',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'latin',
  'answer_language': 'english',
  'question': 'Translate: Nihil nōs impedit quōminus id facere possīmus.',
  'multiple_choice_options': [],
  'answers': ['NOTHING PREVENTS / HINDERS / KEEPS US FROM BEING ABLE TO DO IT.']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_18a_28',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate: Fateor multōs hominēs excellentī animō ac virtūte fuisse.',
  'multiple_choice_options': [],
  'answers': ['I / GRANT / DISCOVER / CONFESS THAT THERE HAVE BEEN MANY MEN OF OUTSTANDING SOUL / SPIRIT / MIND AND VIRTUE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_18c_27',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Translate: Ītalia erat tam plēnā Graecārum artium ut pars “Magna Graecia” vocārētur.',
  'multiple_choice_options': [],
  'answers': ['ITALY WAS SO FULL OF GREEK ARTS THAT PART WAS CALLED “GREAT GREECE” / MAGNA GRAECIA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7b_36',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'advanced',
  'question_language': 'latin',
  'answer_language': 'english',
  'question': 'Translate: Multī volunt ut aliī aliīs auxiliō sint.',
  'multiple_choice_options': [],
  'answers': ['MANY WISH THAT SOME PEOPLE MIGHT BE A HELP TO OTHERS (AND OTHERS TO OTHERS)']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7c_32',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'advanced',
  'question_language': 'latin',
  'answer_language': 'english',
  'question': 'Translate: Multī verēbāntur nē auxiliīs carērent.',
  'multiple_choice_options': [],
  'answers': ['MANY FEARED THAT THEY LACKED HELP (AIDS)']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20b_27',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Look at the inscriptions labeled “B” and “C”, which were discovered together. Translate both of them. Then tell me the most likely place where they were discovered. INSCRIPTION B = EME ET HABEBIS; INSCRIPTION C = FUR, CAVE MALUM',
  'multiple_choice_options': [],
  'answers': ['B = BUY (IT) AND YOU WILL HAVE (IT)',
   'C = THIEF, BEWARE MISFORTUNE',
   'THEY WERE MOST LIKELY FOUND IN A MARKETPLACE, SHOP, STORE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13b_34',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'latin',
  'answer_language': 'english',
  'question': 'Translate: Pedes audīvit dūcem mīlitēs hortārī.',
  'multiple_choice_options': [],
  'answers': ['A FOOT SOLDIER HEARD THAT THE GENERAL ENCOURAGED/WAS ENCOURAGING THE SOLDIERS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1c_49',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'The Latin phrase “unō saltū duōs aprōs capere” is the equivalent of the English proverb “kill two birds with one stone”. What does the phrase mean literally?',
  'multiple_choice_options': [],
  'answers': ['TO SEIZE/CAPTURE TWO (WILD) BOARS WITH ONE LEAP']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11a_35',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',

In [16]:
multiple_refs_prompt = '''I will give you the answer key for a translation question. The key denotes multiple possible translations that are correct by enclosing alternatives in parentheses or using a slash. 
Please expand the key into a list of all possible translations, where each translation stands alone without parentheses or a slash.
Do not add any new translations; only expand the answer key given.
Please respond ONLY with the expanded list of translations, each on a new line. Do not include any other text.
'''

latin_ans_prompt = '''The translation is in Latin, so for reference I will also give you the original question in English.'''

In [23]:
i = 101

question = multiple_refs_dict[i]['question']
answers = multiple_refs_dict[i]['answers']
answer_language = multiple_refs_dict[i]['answer_language']


prompt = multiple_refs_prompt
if answer_language == 'latin':
    prompt += f"\n{latin_ans_prompt}\nOriginal English question: {question}"

prompt += "\nPossible translations:\n" + '\n'.join(answers)

print(prompt)

I will give you the answer key for a translation question. The key denotes multiple possible translations that are correct by enclosing alternatives in parentheses or using a slash.
Please expand the key into a list of all possible translations, where each translation stands alone without parentheses or a slash.
Do not add any new translations; only expand the answer key given.
Please respond ONLY with the expanded list of translations, each on a new line. Do not include any other text.

The translation is in Latin, so for reference I will also give you the original question in English.
Original English question: Using the dative, say in Latin “This dog is a great help to me.”
Possible translations:
IS / EA or HIC / HAEC CANIS MIHI EST MAGNŌ AUXILIŌ / SUBSIDIŌ / ŪSUĪ
MAGNAE OPĪ

In [24]:
response = openai_client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )
resp = response.choices[0].message.content
resp

'IS CANIS MIHI EST MAGNŌ AUXILIŌ  \nIS CANIS MIHI EST MAGNŌ SUBSIDIŌ  \nIS CANIS MIHI EST MAGNŌ ŪSUĪ  \nIS CANIS MIHI EST MAGNAE OPĪ  \nEA CANIS MIHI EST MAGNŌ AUXILIŌ  \nEA CANIS MIHI EST MAGNŌ SUBSIDIŌ  \nEA CANIS MIHI EST MAGNŌ ŪSUĪ  \nEA CANIS MIHI EST MAGNAE OPĪ  \nHIC CANIS MIHI EST MAGNŌ AUXILIŌ  \nHIC CANIS MIHI EST MAGNŌ SUBSIDIŌ  \nHIC CANIS MIHI EST MAGNŌ ŪSUĪ  \nHIC CANIS MIHI EST MAGNAE OPĪ  \nHAEC CANIS MIHI EST MAGNŌ AUXILIŌ  \nHAEC CANIS MIHI EST MAGNŌ SUBSIDIŌ  \nHAEC CANIS MIHI EST MAGNŌ ŪSUĪ  \nHAEC CANIS MIHI EST MAGNAE OPĪ  '

In [26]:
responses = []
N = len(multiple_refs_dict)
for i in range(len(multiple_refs_dict)):
    #if i < len(responses) and responses[i] != 'error':
    #    continue
    print(i, end=' ')

    q_id = multiple_refs_dict[i]['question_id']
    question = multiple_refs_dict[i]['question']
    answers = multiple_refs_dict[i]['answers']
    answer_language = multiple_refs_dict[i]['answer_language']

    prompt = multiple_refs_prompt
    if answer_language == 'latin':
        prompt += f"\n{latin_ans_prompt}\nOriginal English question: {question}"
    prompt += "\nPossible translations:\n" + '\n'.join(answers)

    
    try:
        response = openai_client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant."},
                    {"role": "user", "content": prompt}
                ]
            )
        resp = response.choices[0].message.content
    except Exception as e:
        print(f"Error on question {i}: {e}")
        resp = 'error'
    
    #if responses[i] == 'error':
    #    responses[i] = resp
    #elif i < len(responses):
    responses.append(resp)

    if i % 50 == 0:
        print(f"{i+1}/{N}")
        # dump to json
        with open('../data/structured/certamen_translation_expanded_responses.json', 'w') as f:
            json.dump(responses, f, indent=4)

    sleep(.01)

# save final responses
with open('../data/structured/certamen_translation_expanded_responses.json', 'w') as f:
    json.dump(responses, f, indent=4)

0 1/405
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51/405
51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101/405
101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151/405
151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201/405
201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251/405
251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301/405
301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351/405
351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401/405
401 402 403 404

In [27]:
len(responses), len(multiple_refs_dict)

(405, 405)

In [32]:
# parse responses
new_responses = []
for resp in responses:
    new_resp = resp.split('\n')
    
    # clean up whitespace
    new_resp = [r.strip() for r in new_resp]
    
    # remove duplicates 
    new_resp = list(set(new_resp))
    
    # remove empty strings
    new_resp = [r for r in new_resp if r]

    assert new_resp != []
    
    new_responses.append(new_resp)

In [35]:
#avg answer len

total_len = sum([len(r) for r in new_responses])
max_len = max([len(r) for r in new_responses])
min_len = min([len(r) for r in new_responses])
avg_len = total_len / len(new_responses)
print(f"Average number of translations per answer: {avg_len}")
print(f"Max number of translations per answer: {max_len}")
print(f"Min number of translations per answer: {min_len}")

Average number of translations per answer: 4.241975308641975
Max number of translations per answer: 48
Min number of translations per answer: 1

In [39]:
# add back to multiple_refs_dict
for i, dict_ in enumerate(multiple_refs_dict):
    dict_['answers'] = new_responses[i]

# update multiple_refs_df
multiple_refs_df = pd.DataFrame(multiple_refs_dict)

In [38]:
# multiple_refs_ids
multiple_refs_ids = multiple_refs_df['question_id'].tolist()

In [41]:
# update long_translation_df with the new multiple_refs answers 
long_translation_dict = long_translation_df.to_dict(orient="records")
for i, old_dict in enumerate(long_translation_dict):
    if old_dict['question_id'] in multiple_refs_ids:
        # find the row in multiple_refs_df
        new_dict = multiple_refs_df[multiple_refs_df['question_id'] == old_dict['question_id']].to_dict(orient="records")[0]
        # update the row
        long_translation_dict[i] = new_dict

In [43]:
len(long_translation_dict)

960

In [44]:
# dump json
with open('../data/structured/certamen_translation_long.json', 'w') as f:
    json.dump(long_translation_dict, f, indent=4)