In [1]:
import json
import pandas as pd

certamen: fix multiple choice questions

In [2]:
with open('../data/final_dataset/certamen_short_answer.json', 'r') as f:
    data = json.load(f)

df = pd.DataFrame(data)
df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers
0,NJCL-Certamen,1996,NJCL-Certamen_1996_1a_0,short_answer,history,unknown,english,latin,What name was given to the large agricultural ...,[],[LATIFUNDIA]
1,NJCL-Certamen,1996,NJCL-Certamen_1996_1b_0,short_answer,history,unknown,english,latin,What was the manager or overseer of a latifund...,[],[VILICUS]
2,NJCL-Certamen,1996,NJCL-Certamen_1996_4a_0,short_answer,vocabulary,unknown,latin,latin,Quod animal facit mel?,[],[APIS]
3,NJCL-Certamen,1996,NJCL-Certamen_1996_6b_0,short_answer,literature,unknown,english,english,Who was Odysseus' long-suffering wife?,[],[Penelope]
4,NJCL-Certamen,1996,NJCL-Certamen_1996_7a_0,short_answer,grammar,unknown,english,latin,"Give the first person singular, present passiv...",[],[VEHAR]
...,...,...,...,...,...,...,...,...,...,...,...
4933,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_894,short_answer,history,advanced,english,latin,Name the last of the Gallic emperors whom Aure...,[],[TETRICUS]
4934,NJCL-Certamen,2002,NJCL-Certamen_2002_12_76,short_answer,mythology,unknown,english,latin,"Which deity, according to Aeschylus, was “kind...",[],[ARTEMIS]
4935,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_887,short_answer,mythology,unknown,english,latin,Who was so chaste and devoted to Artemis that ...,[],[HIPPOLYTUS]
4936,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_896,short_answer,mythology,unknown,english,latin,Who almost married Artemis but was killed by t...,[],[ORION]
4937,NJCL-Certamen,2002,NJCL-Certamen_2002_14b_66,short_answer,history,advanced,english,english,How many tabulae were produced by the commissi...,[],[TEN]

In [3]:
mult_choice_df = df[df['question_format'] == 'multiple_choice']
mult_choice_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers
33,NJCL-Certamen,1996,NJCL-Certamen_1996_7c_1,multiple_choice,grammar,unknown,english,latin,What use of the genitive case is found in the ...,NaN,[POSSESSIVE]
35,NJCL-Certamen,1996,NJCL-Certamen_1996_9a_1,multiple_choice,vocabulary,unknown,english,latin,What Latin preposition is the root of “country”?,"[CONTRA, CUM, ULTRA]",[CONTRA]
88,NJCL-Certamen,1996,NJCL-Certamen_1996_11_0,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[sauce, saline, salad, sausage, sautee]",[sautee]
145,NJCL-Certamen,1996,NJCL-Certamen_1996_15a_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[HORTATORY]
146,NJCL-Certamen,1996,NJCL-Certamen_1996_15b_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[DELIBERATIVE]
...,...,...,...,...,...,...,...,...,...,...,...
4907,NJCL-Certamen,2002,NJCL-Certamen_2002_7_77,multiple_choice,grammar,advanced,english,english,What use of the genitive case can be found in ...,"[OBJECTIVE, DESCRIPTION / QUALITY, PARTITIVE /...",[OBJECTIVE]
4912,NJCL-Certamen,2002,NJCL-Certamen_2002_10_71,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...",[],[CONJURE]
4913,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_870,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...",[],[VICIOUS]
4914,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_879,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[cable, chef, capital, chief, chapter]",[CABLE]
4923,NJCL-Certamen,2002,NJCL-Certamen_2002_3_79,multiple_choice,history,advanced,english,english,Which of the following was not grown by the Ro...,"[apricot, pomegranate, peach, tomato, cherry]",[TOMATO]

In [4]:
non_empty_mc = mult_choice_df[mult_choice_df['multiple_choice_options'].apply(lambda x: type(x) == list and len(x) > 0)]
non_empty_mc

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers
35,NJCL-Certamen,1996,NJCL-Certamen_1996_9a_1,multiple_choice,vocabulary,unknown,english,latin,What Latin preposition is the root of “country”?,"[CONTRA, CUM, ULTRA]",[CONTRA]
88,NJCL-Certamen,1996,NJCL-Certamen_1996_11_0,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[sauce, saline, salad, sausage, sautee]",[sautee]
145,NJCL-Certamen,1996,NJCL-Certamen_1996_15a_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[HORTATORY]
146,NJCL-Certamen,1996,NJCL-Certamen_1996_15b_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[DELIBERATIVE]
147,NJCL-Certamen,1996,NJCL-Certamen_1996_15c_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[OPTATIVE]
...,...,...,...,...,...,...,...,...,...,...,...
4874,NJCL-Certamen,2002,NJCL-Certamen_2002_18_75,multiple_choice,vocabulary,advanced,english,latin,With which of the following Latin terms are ru...,"[arborēs, animālia, factiōnēs, nāvēs, cibī]",[FACTIŌNĒS]
4890,NJCL-Certamen,2002,NJCL-Certamen_2002_10_70,multiple_choice,vocabulary,advanced,english,latin,Which of the following does not belong because...,"[Agnus, gallus, fēlīx, serpēns, ovis]",[FĒLĪX]
4907,NJCL-Certamen,2002,NJCL-Certamen_2002_7_77,multiple_choice,grammar,advanced,english,english,What use of the genitive case can be found in ...,"[OBJECTIVE, DESCRIPTION / QUALITY, PARTITIVE /...",[OBJECTIVE]
4914,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_879,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[cable, chef, capital, chief, chapter]",[CABLE]
4923,NJCL-Certamen,2002,NJCL-Certamen_2002_3_79,multiple_choice,history,advanced,english,english,Which of the following was not grown by the Ro...,"[apricot, pomegranate, peach, tomato, cherry]",[TOMATO]

In [44]:
# dump non empty mc to tsv
non_empty_mc.to_csv('../data/structured/certamen_mc_non_empty.tsv', sep='\t', index=False)

In [5]:
# load edited non empty mc
non_empty_mc = pd.read_csv('../data/structured/certamen_nonemptymc_edited.tsv', sep='\t')

In [10]:
# mc with empty "multiple_choice_options" field (na or [])
rows1 = mult_choice_df[mult_choice_df['multiple_choice_options'].isna()]
rows2 = mult_choice_df[mult_choice_df['multiple_choice_options'].apply(lambda x: type(x) == list and len(x) == 0)]
empty_mc = pd.concat([rows1, rows2])
empty_mc.drop_duplicates(subset=['question_id'], inplace=True)
empty_mc

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers
33,NJCL-Certamen,1996,NJCL-Certamen_1996_7c_1,multiple_choice,grammar,unknown,english,latin,What use of the genitive case is found in the ...,NaN,[POSSESSIVE]
228,NJCL-Certamen,1996,NJCL-Certamen_1996_7a_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin nouns, if any, do...",[],[VULNUS]
229,NJCL-Certamen,1996,NJCL-Certamen_1996_7b_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin verbs, if any, do...",[],[VERTŌ]
230,NJCL-Certamen,1996,NJCL-Certamen_1996_7c_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin adjectives, if an...",[],[ĀCER]
356,NJCL-Certamen,1996,NJCL-Certamen_1996_11c_11,multiple_choice,grammar,unknown,english,latin,"Using the Latin verb ambulō, ambulare translat...",[],[AMBULEMUS]
...,...,...,...,...,...,...,...,...,...,...,...
4632,NJCL-Certamen,2002,NJCL-Certamen_2002_3_66,multiple_choice,mythology,advanced,english,english,"In Book 6 of Ovid’s Metamorphoses, into what k...",[],[FROGS]
4730,NJCL-Certamen,2002,NJCL-Certamen_2002_2_63,multiple_choice,vocabulary,unknown,english,latin,"Of the animals delphīnus, gallus, orca, testūd...",[],[GALLUS]
4836,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_838,multiple_choice,vocabulary,advanced,english,english,"Which of the following, if any, is NOT derived...",[],[NONE]
4912,NJCL-Certamen,2002,NJCL-Certamen_2002_10_71,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...",[],[CONJURE]
4913,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_870,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...",[],[VICIOUS]

In [14]:
# replace nan with []
empty_mc_dict = empty_mc.to_dict(orient='records')
for row in empty_mc_dict:
    row['multiple_choice_options'] = []

empty_mc_df = pd.DataFrame(empty_mc_dict)
empty_mc_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers
0,NJCL-Certamen,1996,NJCL-Certamen_1996_7c_1,multiple_choice,grammar,unknown,english,latin,What use of the genitive case is found in the ...,[],[POSSESSIVE]
1,NJCL-Certamen,1996,NJCL-Certamen_1996_7a_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin nouns, if any, do...",[],[VULNUS]
2,NJCL-Certamen,1996,NJCL-Certamen_1996_7b_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin verbs, if any, do...",[],[VERTŌ]
3,NJCL-Certamen,1996,NJCL-Certamen_1996_7c_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin adjectives, if an...",[],[ĀCER]
4,NJCL-Certamen,1996,NJCL-Certamen_1996_11c_11,multiple_choice,grammar,unknown,english,latin,"Using the Latin verb ambulō, ambulare translat...",[],[AMBULEMUS]
...,...,...,...,...,...,...,...,...,...,...,...
122,NJCL-Certamen,2002,NJCL-Certamen_2002_3_66,multiple_choice,mythology,advanced,english,english,"In Book 6 of Ovid’s Metamorphoses, into what k...",[],[FROGS]
123,NJCL-Certamen,2002,NJCL-Certamen_2002_2_63,multiple_choice,vocabulary,unknown,english,latin,"Of the animals delphīnus, gallus, orca, testūd...",[],[GALLUS]
124,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_838,multiple_choice,vocabulary,advanced,english,english,"Which of the following, if any, is NOT derived...",[],[NONE]
125,NJCL-Certamen,2002,NJCL-Certamen_2002_10_71,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...",[],[CONJURE]
126,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_870,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...",[],[VICIOUS]

In [15]:
# dump to tsv
empty_mc_df.to_csv('../data/structured/certamen_multiple_choice_empty_options.tsv', sep='\t', index=False)

In [6]:
# load edit
empty_mc_df = pd.read_csv('../data/structured/certamen_mc_empty_edited.tsv', sep='\t')
empty_mc_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,mv_mc_opt,change_short_ans,manual_edits,answerable
0,NJCL-Certamen,1996,NJCL-Certamen_1996_7c_1,short_answer,grammar,unknown,english,latin,What use of the genitive case is found in the ...,[],['POSSESSIVE'],NaN,NaN,1.0,NaN
1,NJCL-Certamen,1996,NJCL-Certamen_1996_7a_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin nouns, if any, do...","[""mūrus"", ""pēs"", ""poēta"", ""vulnus"", ""dominus?""]",['VULNUS'],NaN,NaN,1.0,NaN
2,NJCL-Certamen,1996,NJCL-Certamen_1996_7b_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin verbs, if any, do...",[],['VERTŌ'],1.0,NaN,NaN,NaN
3,NJCL-Certamen,1996,NJCL-Certamen_1996_7c_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin adjectives, if an...",[],['ĀCER'],1.0,NaN,NaN,NaN
4,NJCL-Certamen,1996,NJCL-Certamen_1996_11c_11,multiple_choice,grammar,unknown,english,latin,"Using the Latin verb ambulō, ambulare translat...",[],['AMBULEMUS'],NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,NJCL-Certamen,2002,NJCL-Certamen_2002_3_66,short_answer,literature,advanced,english,english,"In Book 6 of Ovid’s Metamorphoses, into what k...",[],['FROGS'],NaN,NaN,1.0,NaN
123,NJCL-Certamen,2002,NJCL-Certamen_2002_2_63,multiple_choice,vocabulary,unknown,english,latin,Which of the following animals is described in...,"[""delphīnus"", ""gallus"", ""orca"", ""testūdō"", ""pi...",['GALLUS'],NaN,NaN,1.0,NaN
124,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_838,multiple_choice,vocabulary,advanced,english,english,"Which of the following, if any, is NOT derived...",[],['NONE'],1.0,NaN,NaN,NaN
125,NJCL-Certamen,2002,NJCL-Certamen_2002_10_71,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...",[],['CONJURE'],1.0,NaN,NaN,NaN
126,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_870,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...",[],['VICIOUS'],1.0,NaN,NaN,NaN

In [7]:
# drop rows where answerable == 0
unanswerable_ids = empty_mc_df[empty_mc_df['answerable'] == 0]['question_id'].tolist()
unanswerable_ids

['NJCL-Certamen_2002_12c_12',
 'NJCL-Certamen_2002_4_12',
 'NJCL-Certamen_2002_B2_15']

In [8]:
empty_mc_dict = empty_mc_df.to_dict(orient='records')

In [9]:
# 
for dict_ in empty_mc_dict:
    q_id = dict_['question_id']

    # double check if answers field is string, then do eval 
    if type(dict_['answers']) == str:
        try:
            dict_['answers'] = eval(dict_['answers'])
        except:
            pass
    if type(dict_['multiple_choice_options']) == str:
        try:
            dict_['multiple_choice_options'] = eval(dict_['multiple_choice_options'])
        except:
            pass

    # if "mv_mc_opt" == 1, then add the options to the "multiple_choice_options" field
    # and remove them from the question
    if dict_['mv_mc_opt'] == 1 or dict_['mv_mc_opt'] == 1.0:
        question = dict_['question']

        # if : in question, split there
        if ':' in question:
            question, options = question.split(':')
            options = options.strip()
            options = options.split(',')
            options = [option.strip() for option in options]
            # make sure last opt doesn't have a question mark
            if options[-1].endswith('?'):
                options[-1] = options[-1].rstrip('?')
            dict_['multiple_choice_options'] = options
            dict_['question'] = question.strip() + ': '

        elif '?' in question:
            # try to split on the first '?', not the one at the end
            question, options = question.split('?', 1)
            options = options.strip()
            options = options.split(',')
            options = [option.strip() for option in options]
            # make sure last opt doesn't have a question mark
            if options[-1].endswith('?'):
                options[-1] = options[-1].rstrip('?')
            dict_['multiple_choice_options'] = options
            dict_['question'] = question.strip() + '? '

        else:
            print(f"question {q_id} error parsing")

In [10]:
empty_mc_dict

[{'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7c_1',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the genitive case is found in the following sentence: Senatōrum togae sunt sordidae.',
  'multiple_choice_options': [],
  'answers': ['POSSESSIVE'],
  'mv_mc_opt': nan,
  'change_short_ans': nan,
  'manual_edits': 1.0,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7a_8',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin nouns, if any, does NOT belong because of gender: ',
  'multiple_choice_options': ['mūrus', 'pēs', 'poēta', 'vulnus', 'dominus?'],
  'answers': ['VULNUS'],
  'mv_mc_opt': nan,
  'change_short_ans': nan,
  'manual_edits': 1.0,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7b_8',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin verbs, if any, does NOT belong because of conjugation: ',
  'multiple_choice_options': ['aedificō', 'vertō', 'amō', 'necō', 'levō'],
  'answers': ['VERTŌ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7c_8',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin adjectives, if any, does NOT belong because of declension: ',
  'multiple_choice_options': ['ācer', 'pulcher', 'magnus', 'līber', 'niger'],
  'answers': ['ĀCER'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11c_11',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Using the Latin verb ambulō, ambulare translate “walk” in the following sentence: Let’s walk next door and see if anyone’s home.',
  'multiple_choice_options': [],
  'answers': ['AMBULEMUS'],
  'mv_mc_opt': nan,
  'change_short_ans': 1.0,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3a_20',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following, if any, does NOT belong with the others because of meaning: ',
  'multiple_choice_options': ['nūtrix',
   'tergum',
   'labrum',
   'femur',
   'capillus'],
  'answers': ['NŪTRIX'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3b_20',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following, if any, does NOT belong with the others because of meaning: ',
  'multiple_choice_options': ['āter', 'albus', 'viridis', 'flāvus', 'rictus'],
  'answers': ['RICTUS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3c_19',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following, if any, does NOT belong with the others because of meaning: ',
  'multiple_choice_options': ['colus', 'fāgus', 'fīcus', 'ulmus', 'acanthus'],
  'answers': ['COLUS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13a_17',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['admiral',
   'mirror',
   'marvel',
   'miracle',
   'admire'],
  'answers': ['ADMIRAL'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13b_17',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['patron',
   'paternity',
   'patrician',
   'patient',
   'patter'],
  'answers': ['PATIENT'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13c_17',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['abuse', 'useful', 'usurp', 'utensil', 'utter'],
  'answers': ['UTTER'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11a_20',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['city',
   'civic',
   'citizen',
   'citation',
   'civilian'],
  'answers': ['CITATION'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11b_20',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['insult',
   'isle',
   'insulin',
   'peninsula',
   'insulation'],
  'answers': ['INSULT'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11c_19',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['coronary',
   'crown',
   'coronet',
   'coroner',
   'corner'],
  'answers': ['CORNER'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_2a_27',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of these words does not belong in this group because of its meaning? ',
  'multiple_choice_options': ['dēfendō',
   'serviō',
   'tueor',
   'muniō',
   'prōtegō'],
  'answers': ['SERVIŌ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_2b_27',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of these words does not belong in this group because of its meaning? ',
  'multiple_choice_options': ['cogitō', 'loquor', 'inquam', 'dicō', 'nārrō'],
  'answers': ['COGITŌ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_2c_27',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of these words does not belong in this group because of its meaning? ',
  'multiple_choice_options': ['festīnō',
   'contendō',
   'cēlō',
   'incitō',
   'properō'],
  'answers': ['CĒLŌ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6a_22',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin words, if any, does NOT share a common root with the others: ',
  'multiple_choice_options': ['ōrātor',
   'ōsculum',
   'ostendere',
   'ōrāre',
   'ōrāculum'],
  'answers': ['OSTENDERE'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6b_22',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin words, if any, does NOT share a common root with the others: ',
  'multiple_choice_options': ['vidēlicet',
   'prūdēns',
   'vīsitāre',
   'viduus',
   'vīsiō'],
  'answers': ['VIDUUS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6c_20',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin words, if any, does NOT share a common root with the others: ',
  'multiple_choice_options': ['novitās',
   'ignōtus',
   'recognōscere',
   'nōtiō',
   'nōbilitās'],
  'answers': ['NOVITĀS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4a_31',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['timid', 'temerity', 'timorous', 'intimidate'],
  'answers': ['TEMERITY'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4b_31',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['travel', 'treat', 'contract', 'portrait'],
  'answers': ['TRAVEL'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4c_31',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['transpire',
   'sprite',
   'aspire',
   'spirit',
   'despair'],
  'answers': ['DESPAIR'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_2a_34',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin words, if any, does NOT share a common root with the others: ',
  'multiple_choice_options': ['agmen',
   'āctiō',
   'agilis',
   'cōgere',
   'agrārius'],
  'answers': ['AGRĀRIUS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_2b_34',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin words, if any, does NOT share a common root with the others: ',
  'multiple_choice_options': ['sēditiō',
   'sessiō',
   'residuus',
   'subsidium',
   'obsidēre'],
  'answers': ['SĒDITIŌ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_2c_34',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin words, if any, does NOT share a common root with the others: ',
  'multiple_choice_options': ['obīre',
   'īrātus',
   'initium',
   'ambitiō',
   'exitium'],
  'answers': ['ĪRĀTUS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10a_32',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin nouns does not belong because of gender: ',
  'multiple_choice_options': ['custōs', 'humus', 'fidēs', 'aetās', 'domus'],
  'answers': ['CUSTŌS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11b_34',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following is NOT a verb that is REGULARLY used with the genitive case: ',
  'multiple_choice_options': ['Respondeō',
   'Oblīvīscor',
   'Interest',
   'Misereor',
   'Egeō'],
  'answers': ['RESPONDEŌ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_8a_34',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin prepositions does not belong: ',
  'multiple_choice_options': ['sine', 'inter', 'ad', 'apud', 'per'],
  'answers': ['SINE'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_8b_34',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin prepositions does not belong: ',
  'multiple_choice_options': ['intrā', 'ex', 'prō', 'dē', 'cum'],
  'answers': ['INTRĀ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3a_54',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, does NOT belong: ',
  'multiple_choice_options': ['Imperfect',
   'Indirect',
   'Present',
   'Perfect',
   'Future'],
  'answers': ['Indirect'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3b_54',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, does NOT belong: ',
  'multiple_choice_options': ['Infinitive',
   'Imperative',
   'Passive',
   'Indicative',
   'Subjunctive'],
  'answers': ['Passive'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3c_51',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, does NOT belong: ',
  'multiple_choice_options': ['Vocative',
   'Predicative',
   'Genitive',
   'Accusative',
   'Ablative'],
  'answers': ['Predicative'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7a_48',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin word as the others: ',
  'multiple_choice_options': ['maintain',
   'manual',
   'manure',
   'manager',
   'mandate'],
  'answers': ['MANDATE'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15b_38',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following, IS a synonym of horribilis: ',
  'multiple_choice_options': ['viridis',
   'madidus',
   'fervidus',
   'calidus',
   'fēlīx',
   'or none of the above'],
  'answers': ['NONE'],
  'mv_mc_opt': 1.0,

In [11]:
# change mc to short answer 
for dict_ in empty_mc_dict:
    if dict_['change_short_ans'] == 1 or dict_['change_short_ans'] == 1.0:
        dict_['question_format'] = 'short_answer'
        dict_['multiple_choice_options'] = []

empty_mc_dict

[{'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7c_1',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the genitive case is found in the following sentence: Senatōrum togae sunt sordidae.',
  'multiple_choice_options': [],
  'answers': ['POSSESSIVE'],
  'mv_mc_opt': nan,
  'change_short_ans': nan,
  'manual_edits': 1.0,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7a_8',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin nouns, if any, does NOT belong because of gender: ',
  'multiple_choice_options': ['mūrus', 'pēs', 'poēta', 'vulnus', 'dominus?'],
  'answers': ['VULNUS'],
  'mv_mc_opt': nan,
  'change_short_ans': nan,
  'manual_edits': 1.0,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7b_8',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin verbs, if any, does NOT belong because of conjugation: ',
  'multiple_choice_options': ['aedificō', 'vertō', 'amō', 'necō', 'levō'],
  'answers': ['VERTŌ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7c_8',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin adjectives, if any, does NOT belong because of declension: ',
  'multiple_choice_options': ['ācer', 'pulcher', 'magnus', 'līber', 'niger'],
  'answers': ['ĀCER'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11c_11',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Using the Latin verb ambulō, ambulare translate “walk” in the following sentence: Let’s walk next door and see if anyone’s home.',
  'multiple_choice_options': [],
  'answers': ['AMBULEMUS'],
  'mv_mc_opt': nan,
  'change_short_ans': 1.0,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3a_20',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following, if any, does NOT belong with the others because of meaning: ',
  'multiple_choice_options': ['nūtrix',
   'tergum',
   'labrum',
   'femur',
   'capillus'],
  'answers': ['NŪTRIX'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3b_20',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following, if any, does NOT belong with the others because of meaning: ',
  'multiple_choice_options': ['āter', 'albus', 'viridis', 'flāvus', 'rictus'],
  'answers': ['RICTUS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3c_19',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following, if any, does NOT belong with the others because of meaning: ',
  'multiple_choice_options': ['colus', 'fāgus', 'fīcus', 'ulmus', 'acanthus'],
  'answers': ['COLUS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13a_17',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['admiral',
   'mirror',
   'marvel',
   'miracle',
   'admire'],
  'answers': ['ADMIRAL'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13b_17',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['patron',
   'paternity',
   'patrician',
   'patient',
   'patter'],
  'answers': ['PATIENT'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13c_17',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['abuse', 'useful', 'usurp', 'utensil', 'utter'],
  'answers': ['UTTER'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11a_20',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['city',
   'civic',
   'citizen',
   'citation',
   'civilian'],
  'answers': ['CITATION'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11b_20',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['insult',
   'isle',
   'insulin',
   'peninsula',
   'insulation'],
  'answers': ['INSULT'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11c_19',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['coronary',
   'crown',
   'coronet',
   'coroner',
   'corner'],
  'answers': ['CORNER'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_2a_27',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of these words does not belong in this group because of its meaning? ',
  'multiple_choice_options': ['dēfendō',
   'serviō',
   'tueor',
   'muniō',
   'prōtegō'],
  'answers': ['SERVIŌ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_2b_27',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of these words does not belong in this group because of its meaning? ',
  'multiple_choice_options': ['cogitō', 'loquor', 'inquam', 'dicō', 'nārrō'],
  'answers': ['COGITŌ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_2c_27',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of these words does not belong in this group because of its meaning? ',
  'multiple_choice_options': ['festīnō',
   'contendō',
   'cēlō',
   'incitō',
   'properō'],
  'answers': ['CĒLŌ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6a_22',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin words, if any, does NOT share a common root with the others: ',
  'multiple_choice_options': ['ōrātor',
   'ōsculum',
   'ostendere',
   'ōrāre',
   'ōrāculum'],
  'answers': ['OSTENDERE'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6b_22',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin words, if any, does NOT share a common root with the others: ',
  'multiple_choice_options': ['vidēlicet',
   'prūdēns',
   'vīsitāre',
   'viduus',
   'vīsiō'],
  'answers': ['VIDUUS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6c_20',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin words, if any, does NOT share a common root with the others: ',
  'multiple_choice_options': ['novitās',
   'ignōtus',
   'recognōscere',
   'nōtiō',
   'nōbilitās'],
  'answers': ['NOVITĀS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4a_31',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['timid', 'temerity', 'timorous', 'intimidate'],
  'answers': ['TEMERITY'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4b_31',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['travel', 'treat', 'contract', 'portrait'],
  'answers': ['TRAVEL'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4c_31',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others: ',
  'multiple_choice_options': ['transpire',
   'sprite',
   'aspire',
   'spirit',
   'despair'],
  'answers': ['DESPAIR'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_2a_34',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin words, if any, does NOT share a common root with the others: ',
  'multiple_choice_options': ['agmen',
   'āctiō',
   'agilis',
   'cōgere',
   'agrārius'],
  'answers': ['AGRĀRIUS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_2b_34',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin words, if any, does NOT share a common root with the others: ',
  'multiple_choice_options': ['sēditiō',
   'sessiō',
   'residuus',
   'subsidium',
   'obsidēre'],
  'answers': ['SĒDITIŌ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_2c_34',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin words, if any, does NOT share a common root with the others: ',
  'multiple_choice_options': ['obīre',
   'īrātus',
   'initium',
   'ambitiō',
   'exitium'],
  'answers': ['ĪRĀTUS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10a_32',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin nouns does not belong because of gender: ',
  'multiple_choice_options': ['custōs', 'humus', 'fidēs', 'aetās', 'domus'],
  'answers': ['CUSTŌS'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11b_34',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following is NOT a verb that is REGULARLY used with the genitive case: ',
  'multiple_choice_options': ['Respondeō',
   'Oblīvīscor',
   'Interest',
   'Misereor',
   'Egeō'],
  'answers': ['RESPONDEŌ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_8a_34',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin prepositions does not belong: ',
  'multiple_choice_options': ['sine', 'inter', 'ad', 'apud', 'per'],
  'answers': ['SINE'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_8b_34',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin prepositions does not belong: ',
  'multiple_choice_options': ['intrā', 'ex', 'prō', 'dē', 'cum'],
  'answers': ['INTRĀ'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3a_54',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, does NOT belong: ',
  'multiple_choice_options': ['Imperfect',
   'Indirect',
   'Present',
   'Perfect',
   'Future'],
  'answers': ['Indirect'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3b_54',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, does NOT belong: ',
  'multiple_choice_options': ['Infinitive',
   'Imperative',
   'Passive',
   'Indicative',
   'Subjunctive'],
  'answers': ['Passive'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3c_51',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, does NOT belong: ',
  'multiple_choice_options': ['Vocative',
   'Predicative',
   'Genitive',
   'Accusative',
   'Ablative'],
  'answers': ['Predicative'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7a_48',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin word as the others: ',
  'multiple_choice_options': ['maintain',
   'manual',
   'manure',
   'manager',
   'mandate'],
  'answers': ['MANDATE'],
  'mv_mc_opt': 1.0,
  'change_short_ans': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15b_38',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following, IS a synonym of horribilis: ',
  'multiple_choice_options': ['viridis',
   'madidus',
   'fervidus',
   'calidus',
   'fēlīx',
   'or none of the above'],
  'answers': ['NONE'],
  'mv_mc_opt': 1.0,

In [12]:
# back to df
empty_mc_df = pd.DataFrame(empty_mc_dict)
empty_mc_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,mv_mc_opt,change_short_ans,manual_edits,answerable
0,NJCL-Certamen,1996,NJCL-Certamen_1996_7c_1,short_answer,grammar,unknown,english,latin,What use of the genitive case is found in the ...,[],[POSSESSIVE],NaN,NaN,1.0,NaN
1,NJCL-Certamen,1996,NJCL-Certamen_1996_7a_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin nouns, if any, do...","[mūrus, pēs, poēta, vulnus, dominus?]",[VULNUS],NaN,NaN,1.0,NaN
2,NJCL-Certamen,1996,NJCL-Certamen_1996_7b_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin verbs, if any, do...","[aedificō, vertō, amō, necō, levō]",[VERTŌ],1.0,NaN,NaN,NaN
3,NJCL-Certamen,1996,NJCL-Certamen_1996_7c_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin adjectives, if an...","[ācer, pulcher, magnus, līber, niger]",[ĀCER],1.0,NaN,NaN,NaN
4,NJCL-Certamen,1996,NJCL-Certamen_1996_11c_11,short_answer,grammar,unknown,english,latin,"Using the Latin verb ambulō, ambulare translat...",[],[AMBULEMUS],NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,NJCL-Certamen,2002,NJCL-Certamen_2002_3_66,short_answer,literature,advanced,english,english,"In Book 6 of Ovid’s Metamorphoses, into what k...",[],[FROGS],NaN,NaN,1.0,NaN
123,NJCL-Certamen,2002,NJCL-Certamen_2002_2_63,multiple_choice,vocabulary,unknown,english,latin,Which of the following animals is described in...,"[delphīnus, gallus, orca, testūdō, piscis]",[GALLUS],NaN,NaN,1.0,NaN
124,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_838,multiple_choice,vocabulary,advanced,english,english,"Which of the following, if any, is NOT derived...","[lieutenant, location, allocate, locomotive.]",[NONE],1.0,NaN,NaN,NaN
125,NJCL-Certamen,2002,NJCL-Certamen_2002_10_71,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[sojourn, conjure, meridian, circadian, diary]",[CONJURE],1.0,NaN,NaN,NaN
126,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_870,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[vintner, vinyl, vicious, vignette, vinegar]",[VICIOUS],1.0,NaN,NaN,NaN

In [13]:
# drop unanswerable ids
empty_mc_df = empty_mc_df[~empty_mc_df['question_id'].isin(unanswerable_ids)]
empty_mc_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,mv_mc_opt,change_short_ans,manual_edits,answerable
0,NJCL-Certamen,1996,NJCL-Certamen_1996_7c_1,short_answer,grammar,unknown,english,latin,What use of the genitive case is found in the ...,[],[POSSESSIVE],NaN,NaN,1.0,NaN
1,NJCL-Certamen,1996,NJCL-Certamen_1996_7a_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin nouns, if any, do...","[mūrus, pēs, poēta, vulnus, dominus?]",[VULNUS],NaN,NaN,1.0,NaN
2,NJCL-Certamen,1996,NJCL-Certamen_1996_7b_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin verbs, if any, do...","[aedificō, vertō, amō, necō, levō]",[VERTŌ],1.0,NaN,NaN,NaN
3,NJCL-Certamen,1996,NJCL-Certamen_1996_7c_8,multiple_choice,grammar,unknown,english,latin,"Which of the following Latin adjectives, if an...","[ācer, pulcher, magnus, līber, niger]",[ĀCER],1.0,NaN,NaN,NaN
4,NJCL-Certamen,1996,NJCL-Certamen_1996_11c_11,short_answer,grammar,unknown,english,latin,"Using the Latin verb ambulō, ambulare translat...",[],[AMBULEMUS],NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,NJCL-Certamen,2002,NJCL-Certamen_2002_3_66,short_answer,literature,advanced,english,english,"In Book 6 of Ovid’s Metamorphoses, into what k...",[],[FROGS],NaN,NaN,1.0,NaN
123,NJCL-Certamen,2002,NJCL-Certamen_2002_2_63,multiple_choice,vocabulary,unknown,english,latin,Which of the following animals is described in...,"[delphīnus, gallus, orca, testūdō, piscis]",[GALLUS],NaN,NaN,1.0,NaN
124,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_838,multiple_choice,vocabulary,advanced,english,english,"Which of the following, if any, is NOT derived...","[lieutenant, location, allocate, locomotive.]",[NONE],1.0,NaN,NaN,NaN
125,NJCL-Certamen,2002,NJCL-Certamen_2002_10_71,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[sojourn, conjure, meridian, circadian, diary]",[CONJURE],1.0,NaN,NaN,NaN
126,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_870,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[vintner, vinyl, vicious, vignette, vinegar]",[VICIOUS],1.0,NaN,NaN,NaN

In [15]:
non_empty_mc_dict = non_empty_mc.to_dict(orient='records')
non_empty_mc_dict

[{'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_1',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin preposition is the root of “country”?',
  'multiple_choice_options': "['CONTRA', 'CUM', 'ULTRA']",
  'answers': "['CONTRA']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11_0',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others:',
  'multiple_choice_options': "['sauce', 'saline', 'salad', 'sausage', 'sautee']",
  'answers': "['sautee']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_5',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the subjunctive is found in this sentence: Hōs latrōnēs interficiāmus?',
  'multiple_choice_options': "['HORTATORY', 'DELIBERATIVE', 'OPTATIVE']",
  'answers': "['HORTATORY']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15b_5',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the subjunctive is found in this sentence: Quid agam, iūdicēs? quō mē vertam?',
  'multiple_choice_options': "['HORTATORY', 'DELIBERATIVE', 'OPTATIVE']",
  'answers': "['DELIBERATIVE']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15c_5',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the subjunctive is found in this sentence: Utinam mē mortuum vīdissēs?',
  'multiple_choice_options': "['HORTATORY', 'DELIBERATIVE', 'OPTATIVE']",
  'answers': "['OPTATIVE']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3_2',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following English words, if any, IS derived from the pronoun ego:',
  'multiple_choice_options': "['eagle', 'egg', 'egalitarian', 'egotist', 'egret']",
  'answers': "['egotist']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12a_8',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from sum, esse:',
  'multiple_choice_options': "['consummate', 'essence', 'present', 'entity', 'interesting']",
  'answers': "['CONSUMMATE']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12b_8',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from amō, amāre:',
  'multiple_choice_options': "['amiable', 'enamor', 'amaze', 'amateur', 'amatory']",
  'answers': "['AMAZE']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_7',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from habeō, habēre:',
  'multiple_choice_options': "['habit', 'have', 'ability', 'prohibit', 'habitat']",
  'answers': "['HAVE']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_14a_9',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from locus:',
  'multiple_choice_options': "['location', 'couch', 'locomotion', 'locular', 'none of the above']",
  'answers': "['NONE']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_14b_9',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from crēdere:',
  'multiple_choice_options': "['credit', 'creed', 'creation', 'credulity']",
  'answers': "['CREATION']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_14c_9',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from lac: ',
  'multiple_choice_options': "['lactate', 'lettuce', 'laconic', 'lacteal']",
  'answers': "['LACONIC']",
  'rm_opt_question': nan,
  'manual_edits': 1.0,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12a_13',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Greek root as the others:',
  'multiple_choice_options': "['elephant', 'diaphanous', 'phantom', 'fantasy']",
  'answers': "['ELEPHANT']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12b_13',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Greek root as the others:',
  'multiple_choice_options': "['skeptic', 'stethoscope', 'bishop', 'eschew']",
  'answers': "['ESCHEW']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_12',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Greek root as the others:',
  'multiple_choice_options': "['paradox', 'doxology', 'dogmatic', 'docket']",
  'answers': "['DOCKET']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6a_17',
  'question_format': 'multiple_choice',
  'question_content': 'literary_devices',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Identify a figure of speech in these lines: Intereā māgnō miscērī murmure pontum ēmissaque hiemem sēnsit Neptūnus et īmīs',
  'multiple_choice_options': "['ALLITERATION', 'ASSONANCE', 'ONOMATOPOEIA']",
  'answers': "['ALLITERATION']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3a_24',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin word as the others:',
  'multiple_choice_options': "['praise', 'prize', 'pretzel', 'precious', 'appreciate']",
  'answers': "['PRETZEL']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_21',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'How does Latin express the word “that” for this sentence: Do you know that girl over there?',
  'multiple_choice_options': "['ILLAM', 'ISTAM', 'EAM']",
  'answers': "['ILLAM']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': 0.0},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9b_21',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'How does Latin express the word “that” for this sentence: That camp is Catiline’s.',
  'multiple_choice_options': "['ILLA', 'ISTA', 'EA']",
  'answers': "['ILLA']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': 0.0},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20a_19',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Argentum nōn est pretiōsius aurō.',
  'multiple_choice_options': "['COMPARISON', 'DEGREE OF DIFFERENCE', 'SEPARATION']",
  'answers': "['COMPARISON']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20c_19',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Servī līberent sē servitūte.',
  'multiple_choice_options': "['COMPARISON', 'DEGREE OF DIFFERENCE', 'SEPARATION']",
  'answers': "['SEPARATION']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1b_30',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What use of the dative case is found in the following sentence: Nōbīs omnibus amandī sunt aliī?',
  'multiple_choice_options': "['COMPOUND VERBS', 'AGENCY', 'REFERENCE']",
  'answers': "['AGENCY']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1c_28',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What use of the dative case is found in the following sentence: Laudāvit mihi fratrem?',
  'multiple_choice_options': "['COMPOUND VERBS', 'AGENCY', 'REFERENCE']",
  'answers': "['REFERENCE']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_24',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which case would be needed to translate “Publius” for this sentence: Marcus, why is Publius so handsome?',
  'multiple_choice_options': "['NOMINATIVE', 'DATIVE', 'GENITIVE']",
  'answers': "['NOMINATIVE']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9b_24',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which case would be needed to translate “Publius” for this sentence: Marcus gave Publius a fountain.',
  'multiple_choice_options': "['NOMINATIVE', 'DATIVE', 'GENITIVE']",
  'answers': "['DATIVE']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9c_24',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which case would be needed to translate “Publius” for this sentence: Publius’ house is not very austere.',
  'multiple_choice_options': "['NOMINATIVE', 'DATIVE', 'GENITIVE']",
  'answers': "['GENITIVE']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_22',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What use of the genitive case is found in the following sentence: Maxima est potentia imperātōris.',
  'multiple_choice_options': "['POSSESSION', 'PARTITIVE (GEN. OF THE WHOLE)', 'QUALITY (DESCRIPTION)']",
  'answers': "['POSSESSION']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7_5',
  'question_format': 'multiple_choice',
  'question_content': 'translation',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate “Publius” into Latin for this sentence: Caesar sent Publius to Athens.',
  'multiple_choice_options': "['PUBLIUM', 'PUBLIŌ (PUBLIĪ)', 'PUBLĪ']",
  'answers': "['PUBLIUM']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17a_27',
  'question_format': 'multiple_choice',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What son of Hermes and Aphrodite became a half-man, half-woman creature?',
  'multiple_choice_options': "['HERMAPHRODITUS', 'ATLANTIADES', 'ATLANTIUS']",
  'answers': "['HERMAPHRODITUS']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': 0.0},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5b_40',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Prōconsulēs fraude praecēdunt.',
  'multiple_choice_options': "['MEANS', 'SPECIAL VERBS', 'SPECIFICATION', 'PRICE']",
  'answers': "['MEANS']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5c_38',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Agricola senex nōn voluit vendere fundum pecūniā.',
  'multiple_choice_options': "['MEANS', 'SPECIAL VERBS', 'SPECIFICATION', 'PRICE']",
  'answers': "['PRICE']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17a_33',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin numerals answers the question “In which order”:',
  'multiple_choice_options': "['secundus', 'bis', 'bīnī', 'duō', 'duplex']",
  'answers': "['SECUNDUS']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17b_33',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following answers the question “How many at a time”:',
  'multiple_choice_options': "['secundus', 'bis', 'bīnī', 'duō', 'duplex']",
  'answers': "['BĪNĪ']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17c_31',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following answers the question “How often”:',
  'multiple_choice_options': "['secundus', 'bis', 'bīnī', 'duō', 'duplex']",
  'answers': "['BIS']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10b_32',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin nouns does not belong because of gender:',
  'multiple_choice_options': "['bellum', 'legiō', 'animal', 'mare', 'cornū']",
  'answers': "['LEGIŌ']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10c_30',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin nouns does not belong because of gender:',
  'multiple_choice_options': "['cor', 'agricola', 'senātus', 'pēs', 'leō']",
  'answers': "['COR']",
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11a_34',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',

In [16]:
# 
for dict_ in non_empty_mc_dict:
    q_id = dict_['question_id']

    # double check if answers field is string, then do eval 
    if type(dict_['answers']) == str:
        try:
            dict_['answers'] = eval(dict_['answers'])
        except:
            pass
    if type(dict_['multiple_choice_options']) == str:
        try:
            dict_['multiple_choice_options'] = eval(dict_['multiple_choice_options'])
        except:
            pass

    # if "mv_mc_opt" == 1, then add the options to the "multiple_choice_options" field
    # and remove them from the question
    if dict_['rm_opt_question'] == 1 or dict_['rm_opt_question'] == 1.0:
        question = dict_['question']

        # if : in question, split there
        if ':' in question:
            question, options = question.split(':')
            dict_['question'] = question.strip() + ': '

        elif '?' in question:
            # try to split on the first '?', not the one at the end
            question, options = question.split('?', 1)
            
            dict_['question'] = question.strip() + '? '

        else:
            print(f"question {q_id} error parsing")
non_empty_mc_dict

[{'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_1',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin preposition is the root of “country”?',
  'multiple_choice_options': ['CONTRA', 'CUM', 'ULTRA'],
  'answers': ['CONTRA'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11_0',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others:',
  'multiple_choice_options': ['sauce', 'saline', 'salad', 'sausage', 'sautee'],
  'answers': ['sautee'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_5',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the subjunctive is found in this sentence: Hōs latrōnēs interficiāmus?',
  'multiple_choice_options': ['HORTATORY', 'DELIBERATIVE', 'OPTATIVE'],
  'answers': ['HORTATORY'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15b_5',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the subjunctive is found in this sentence: Quid agam, iūdicēs? quō mē vertam?',
  'multiple_choice_options': ['HORTATORY', 'DELIBERATIVE', 'OPTATIVE'],
  'answers': ['DELIBERATIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15c_5',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the subjunctive is found in this sentence: Utinam mē mortuum vīdissēs?',
  'multiple_choice_options': ['HORTATORY', 'DELIBERATIVE', 'OPTATIVE'],
  'answers': ['OPTATIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3_2',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following English words, if any, IS derived from the pronoun ego:',
  'multiple_choice_options': ['eagle',
   'egg',
   'egalitarian',
   'egotist',
   'egret'],
  'answers': ['egotist'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12a_8',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from sum, esse:',
  'multiple_choice_options': ['consummate',
   'essence',
   'present',
   'entity',
   'interesting'],
  'answers': ['CONSUMMATE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12b_8',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from amō, amāre:',
  'multiple_choice_options': ['amiable',
   'enamor',
   'amaze',
   'amateur',
   'amatory'],
  'answers': ['AMAZE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_7',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from habeō, habēre:',
  'multiple_choice_options': ['habit',
   'have',
   'ability',
   'prohibit',
   'habitat'],
  'answers': ['HAVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_14a_9',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from locus:',
  'multiple_choice_options': ['location',
   'couch',
   'locomotion',
   'locular',
   'none of the above'],
  'answers': ['NONE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_14b_9',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from crēdere:',
  'multiple_choice_options': ['credit', 'creed', 'creation', 'credulity'],
  'answers': ['CREATION'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_14c_9',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from lac: ',
  'multiple_choice_options': ['lactate', 'lettuce', 'laconic', 'lacteal'],
  'answers': ['LACONIC'],
  'rm_opt_question': nan,
  'manual_edits': 1.0,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12a_13',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Greek root as the others:',
  'multiple_choice_options': ['elephant', 'diaphanous', 'phantom', 'fantasy'],
  'answers': ['ELEPHANT'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12b_13',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Greek root as the others:',
  'multiple_choice_options': ['skeptic', 'stethoscope', 'bishop', 'eschew'],
  'answers': ['ESCHEW'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_12',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Greek root as the others:',
  'multiple_choice_options': ['paradox', 'doxology', 'dogmatic', 'docket'],
  'answers': ['DOCKET'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6a_17',
  'question_format': 'multiple_choice',
  'question_content': 'literary_devices',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Identify a figure of speech in these lines: Intereā māgnō miscērī murmure pontum ēmissaque hiemem sēnsit Neptūnus et īmīs',
  'multiple_choice_options': ['ALLITERATION', 'ASSONANCE', 'ONOMATOPOEIA'],
  'answers': ['ALLITERATION'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3a_24',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin word as the others:',
  'multiple_choice_options': ['praise',
   'prize',
   'pretzel',
   'precious',
   'appreciate'],
  'answers': ['PRETZEL'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_21',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'How does Latin express the word “that” for this sentence: Do you know that girl over there?',
  'multiple_choice_options': ['ILLAM', 'ISTAM', 'EAM'],
  'answers': ['ILLAM'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': 0.0},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9b_21',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'How does Latin express the word “that” for this sentence: That camp is Catiline’s.',
  'multiple_choice_options': ['ILLA', 'ISTA', 'EA'],
  'answers': ['ILLA'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': 0.0},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20a_19',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Argentum nōn est pretiōsius aurō.',
  'multiple_choice_options': ['COMPARISON',
   'DEGREE OF DIFFERENCE',
   'SEPARATION'],
  'answers': ['COMPARISON'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20c_19',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Servī līberent sē servitūte.',
  'multiple_choice_options': ['COMPARISON',
   'DEGREE OF DIFFERENCE',
   'SEPARATION'],
  'answers': ['SEPARATION'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1b_30',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What use of the dative case is found in the following sentence: Nōbīs omnibus amandī sunt aliī?',
  'multiple_choice_options': ['COMPOUND VERBS', 'AGENCY', 'REFERENCE'],
  'answers': ['AGENCY'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1c_28',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What use of the dative case is found in the following sentence: Laudāvit mihi fratrem?',
  'multiple_choice_options': ['COMPOUND VERBS', 'AGENCY', 'REFERENCE'],
  'answers': ['REFERENCE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_24',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which case would be needed to translate “Publius” for this sentence: Marcus, why is Publius so handsome?',
  'multiple_choice_options': ['NOMINATIVE', 'DATIVE', 'GENITIVE'],
  'answers': ['NOMINATIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9b_24',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which case would be needed to translate “Publius” for this sentence: Marcus gave Publius a fountain.',
  'multiple_choice_options': ['NOMINATIVE', 'DATIVE', 'GENITIVE'],
  'answers': ['DATIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9c_24',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which case would be needed to translate “Publius” for this sentence: Publius’ house is not very austere.',
  'multiple_choice_options': ['NOMINATIVE', 'DATIVE', 'GENITIVE'],
  'answers': ['GENITIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_22',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What use of the genitive case is found in the following sentence: Maxima est potentia imperātōris.',
  'multiple_choice_options': ['POSSESSION',
   'PARTITIVE (GEN. OF THE WHOLE)',
   'QUALITY (DESCRIPTION)'],
  'answers': ['POSSESSION'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7_5',
  'question_format': 'multiple_choice',
  'question_content': 'translation',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate “Publius” into Latin for this sentence: Caesar sent Publius to Athens.',
  'multiple_choice_options': ['PUBLIUM', 'PUBLIŌ (PUBLIĪ)', 'PUBLĪ'],
  'answers': ['PUBLIUM'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17a_27',
  'question_format': 'multiple_choice',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What son of Hermes and Aphrodite became a half-man, half-woman creature?',
  'multiple_choice_options': ['HERMAPHRODITUS', 'ATLANTIADES', 'ATLANTIUS'],
  'answers': ['HERMAPHRODITUS'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': 0.0},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5b_40',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Prōconsulēs fraude praecēdunt.',
  'multiple_choice_options': ['MEANS',
   'SPECIAL VERBS',
   'SPECIFICATION',
   'PRICE'],
  'answers': ['MEANS'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5c_38',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Agricola senex nōn voluit vendere fundum pecūniā.',
  'multiple_choice_options': ['MEANS',
   'SPECIAL VERBS',
   'SPECIFICATION',
   'PRICE'],
  'answers': ['PRICE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17a_33',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin numerals answers the question “In which order”:',
  'multiple_choice_options': ['secundus', 'bis', 'bīnī', 'duō', 'duplex'],
  'answers': ['SECUNDUS'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17b_33',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following answers the question “How many at a time”:',
  'multiple_choice_options': ['secundus', 'bis', 'bīnī', 'duō', 'duplex'],
  'answers': ['BĪNĪ'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17c_31',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following answers the question “How often”:',
  'multiple_choice_options': ['secundus', 'bis', 'bīnī', 'duō', 'duplex'],
  'answers': ['BIS'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10b_32',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin nouns does not belong because of gender:',
  'multiple_choice_options': ['bellum', 'legiō', 'animal', 'mare', 'cornū'],
  'answers': ['LEGIŌ'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10c_30',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin nouns does not belong because of gender:',
  'multiple_choice_options': ['cor', 'agricola', 'senātus', 'pēs', 'leō'],
  'answers': ['COR'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11a_34',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following does NOT belong because it is not a use of the genitive case: ',

In [17]:
non_empty_mc = pd.DataFrame(non_empty_mc_dict)
non_empty_mc

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,rm_opt_question,manual_edits,answerable
0,NJCL-Certamen,1996,NJCL-Certamen_1996_9a_1,multiple_choice,vocabulary,unknown,english,latin,What Latin preposition is the root of “country”?,"[CONTRA, CUM, ULTRA]",[CONTRA],NaN,NaN,NaN
1,NJCL-Certamen,1996,NJCL-Certamen_1996_11_0,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[sauce, saline, salad, sausage, sautee]",[sautee],NaN,NaN,NaN
2,NJCL-Certamen,1996,NJCL-Certamen_1996_15a_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[HORTATORY],NaN,NaN,NaN
3,NJCL-Certamen,1996,NJCL-Certamen_1996_15b_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[DELIBERATIVE],NaN,NaN,NaN
4,NJCL-Certamen,1996,NJCL-Certamen_1996_15c_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[OPTATIVE],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,NJCL-Certamen,2002,NJCL-Certamen_2002_18_75,multiple_choice,vocabulary,advanced,english,latin,With which of the following Latin terms are ru...,"[arborēs, animālia, factiōnēs, nāvēs, cibī]",[FACTIŌNĒS],NaN,NaN,NaN
232,NJCL-Certamen,2002,NJCL-Certamen_2002_10_70,multiple_choice,vocabulary,advanced,english,latin,Which of the following does not belong because...,"[Agnus, gallus, fēlīx, serpēns, ovis]",[FĒLĪX],1.0,NaN,NaN
233,NJCL-Certamen,2002,NJCL-Certamen_2002_7_77,multiple_choice,grammar,advanced,english,english,What use of the genitive case can be found in ...,"[OBJECTIVE, DESCRIPTION / QUALITY, PARTITIVE /...",[OBJECTIVE],NaN,NaN,NaN
234,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_879,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[cable, chef, capital, chief, chapter]",[CABLE],1.0,NaN,NaN
235,NJCL-Certamen,2002,NJCL-Certamen_2002_3_79,multiple_choice,history,advanced,english,english,Which of the following was not grown by the Ro...,"[apricot, pomegranate, peach, tomato, cherry]",[TOMATO],1.0,NaN,NaN

In [18]:
unanswerable_nonempty_ids = non_empty_mc[non_empty_mc['answerable'] == 0]['question_id'].tolist()
unanswerable_nonempty_ids
# remove from non empty mc
non_empty_mc = non_empty_mc[~non_empty_mc['question_id'].isin(unanswerable_nonempty_ids)]
non_empty_mc

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,rm_opt_question,manual_edits,answerable
0,NJCL-Certamen,1996,NJCL-Certamen_1996_9a_1,multiple_choice,vocabulary,unknown,english,latin,What Latin preposition is the root of “country”?,"[CONTRA, CUM, ULTRA]",[CONTRA],NaN,NaN,NaN
1,NJCL-Certamen,1996,NJCL-Certamen_1996_11_0,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[sauce, saline, salad, sausage, sautee]",[sautee],NaN,NaN,NaN
2,NJCL-Certamen,1996,NJCL-Certamen_1996_15a_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[HORTATORY],NaN,NaN,NaN
3,NJCL-Certamen,1996,NJCL-Certamen_1996_15b_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[DELIBERATIVE],NaN,NaN,NaN
4,NJCL-Certamen,1996,NJCL-Certamen_1996_15c_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[OPTATIVE],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,NJCL-Certamen,2002,NJCL-Certamen_2002_18_75,multiple_choice,vocabulary,advanced,english,latin,With which of the following Latin terms are ru...,"[arborēs, animālia, factiōnēs, nāvēs, cibī]",[FACTIŌNĒS],NaN,NaN,NaN
232,NJCL-Certamen,2002,NJCL-Certamen_2002_10_70,multiple_choice,vocabulary,advanced,english,latin,Which of the following does not belong because...,"[Agnus, gallus, fēlīx, serpēns, ovis]",[FĒLĪX],1.0,NaN,NaN
233,NJCL-Certamen,2002,NJCL-Certamen_2002_7_77,multiple_choice,grammar,advanced,english,english,What use of the genitive case can be found in ...,"[OBJECTIVE, DESCRIPTION / QUALITY, PARTITIVE /...",[OBJECTIVE],NaN,NaN,NaN
234,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_879,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[cable, chef, capital, chief, chapter]",[CABLE],1.0,NaN,NaN
235,NJCL-Certamen,2002,NJCL-Certamen_2002_3_79,multiple_choice,history,advanced,english,english,Which of the following was not grown by the Ro...,"[apricot, pomegranate, peach, tomato, cherry]",[TOMATO],1.0,NaN,NaN

In [ ]:
# non empty mc dict
non_empty_mc_dict = non_empty_mc.to_dict(orient='records')
for dict_ in non_empty_mc_dict:
    if dict_['change_short_ans'] == 1 or dict_['change_short_ans'] == 1.0:

In [25]:
# add back to non empty mc df
final_mc = pd.concat([non_empty_mc, empty_mc_df])
final_mc

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,rm_opt_question,manual_edits,answerable,mv_mc_opt,change_short_ans
0,NJCL-Certamen,1996,NJCL-Certamen_1996_9a_1,multiple_choice,vocabulary,unknown,english,latin,What Latin preposition is the root of “country”?,"[CONTRA, CUM, ULTRA]",[CONTRA],NaN,NaN,NaN,NaN,NaN
1,NJCL-Certamen,1996,NJCL-Certamen_1996_11_0,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[sauce, saline, salad, sausage, sautee]",[sautee],NaN,NaN,NaN,NaN,NaN
2,NJCL-Certamen,1996,NJCL-Certamen_1996_15a_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[HORTATORY],NaN,NaN,NaN,NaN,NaN
3,NJCL-Certamen,1996,NJCL-Certamen_1996_15b_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[DELIBERATIVE],NaN,NaN,NaN,NaN,NaN
4,NJCL-Certamen,1996,NJCL-Certamen_1996_15c_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[HORTATORY, DELIBERATIVE, OPTATIVE]",[OPTATIVE],NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,NJCL-Certamen,2002,NJCL-Certamen_2002_3_66,short_answer,literature,advanced,english,english,"In Book 6 of Ovid’s Metamorphoses, into what k...",[],[FROGS],NaN,1.0,NaN,NaN,NaN
123,NJCL-Certamen,2002,NJCL-Certamen_2002_2_63,multiple_choice,vocabulary,unknown,english,latin,Which of the following animals is described in...,"[delphīnus, gallus, orca, testūdō, piscis]",[GALLUS],NaN,1.0,NaN,NaN,NaN
124,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_838,multiple_choice,vocabulary,advanced,english,english,"Which of the following, if any, is NOT derived...","[lieutenant, location, allocate, locomotive.]",[NONE],NaN,NaN,NaN,1.0,NaN
125,NJCL-Certamen,2002,NJCL-Certamen_2002_10_71,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[sojourn, conjure, meridian, circadian, diary]",[CONJURE],NaN,NaN,NaN,1.0,NaN
126,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_870,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[vintner, vinyl, vicious, vignette, vinegar]",[VICIOUS],NaN,NaN,NaN,1.0,NaN

In [22]:
def get_letter(old_options, new_options, answer_str, letters):
    answer_str = answer_str.lower()
    if answer_str == 'none':
        new_answer = new_options[-1] 
        return new_answer 
    
    # check for exact matches
    for i, opt in enumerate(old_options):
        if answer_str == opt.lower():
            return new_options[i]
    
    # check for partial matches
    highest_match_index = -1 # highest string overlap
    highest_overlap = 0
    for i, opt in enumerate(old_options):
        overlap = len(set(answer_str) & set(opt.lower()))
        if overlap > highest_overlap:
            highest_overlap = overlap
            best_match_index = i
            
    if best_match_index != -1:
        print(f'Matching {answer_str} to {old_options[best_match_index]}')
        return new_options[best_match_index]
    
    return None

In [31]:
ans = 'AURIGA'
ans.lower() == 'aurīga'

False

In [26]:
final_dict = final_mc.to_dict(orient='records')
final_dict

[{'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_1',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin preposition is the root of “country”?',
  'multiple_choice_options': ['CONTRA', 'CUM', 'ULTRA'],
  'answers': ['CONTRA'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11_0',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others:',
  'multiple_choice_options': ['sauce', 'saline', 'salad', 'sausage', 'sautee'],
  'answers': ['sautee'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_5',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the subjunctive is found in this sentence: Hōs latrōnēs interficiāmus?',
  'multiple_choice_options': ['HORTATORY', 'DELIBERATIVE', 'OPTATIVE'],
  'answers': ['HORTATORY'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15b_5',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the subjunctive is found in this sentence: Quid agam, iūdicēs? quō mē vertam?',
  'multiple_choice_options': ['HORTATORY', 'DELIBERATIVE', 'OPTATIVE'],
  'answers': ['DELIBERATIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15c_5',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the subjunctive is found in this sentence: Utinam mē mortuum vīdissēs?',
  'multiple_choice_options': ['HORTATORY', 'DELIBERATIVE', 'OPTATIVE'],
  'answers': ['OPTATIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3_2',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following English words, if any, IS derived from the pronoun ego:',
  'multiple_choice_options': ['eagle',
   'egg',
   'egalitarian',
   'egotist',
   'egret'],
  'answers': ['egotist'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12a_8',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from sum, esse:',
  'multiple_choice_options': ['consummate',
   'essence',
   'present',
   'entity',
   'interesting'],
  'answers': ['CONSUMMATE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12b_8',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from amō, amāre:',
  'multiple_choice_options': ['amiable',
   'enamor',
   'amaze',
   'amateur',
   'amatory'],
  'answers': ['AMAZE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_7',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from habeō, habēre:',
  'multiple_choice_options': ['habit',
   'have',
   'ability',
   'prohibit',
   'habitat'],
  'answers': ['HAVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_14a_9',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from locus:',
  'multiple_choice_options': ['location',
   'couch',
   'locomotion',
   'locular',
   'none of the above',
   'none of the above'],
  'answers': ['NONE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_14b_9',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from crēdere:',
  'multiple_choice_options': ['credit', 'creed', 'creation', 'credulity'],
  'answers': ['CREATION'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_14c_9',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from lac: ',
  'multiple_choice_options': ['lactate', 'lettuce', 'laconic', 'lacteal'],
  'answers': ['LACONIC'],
  'rm_opt_question': nan,
  'manual_edits': 1.0,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12a_13',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Greek root as the others:',
  'multiple_choice_options': ['elephant', 'diaphanous', 'phantom', 'fantasy'],
  'answers': ['ELEPHANT'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12b_13',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Greek root as the others:',
  'multiple_choice_options': ['skeptic', 'stethoscope', 'bishop', 'eschew'],
  'answers': ['ESCHEW'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_12',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Greek root as the others:',
  'multiple_choice_options': ['paradox', 'doxology', 'dogmatic', 'docket'],
  'answers': ['DOCKET'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6a_17',
  'question_format': 'multiple_choice',
  'question_content': 'literary_devices',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Identify a figure of speech in these lines: Intereā māgnō miscērī murmure pontum ēmissaque hiemem sēnsit Neptūnus et īmīs',
  'multiple_choice_options': ['ALLITERATION', 'ASSONANCE', 'ONOMATOPOEIA'],
  'answers': ['ALLITERATION'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3a_24',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin word as the others:',
  'multiple_choice_options': ['praise',
   'prize',
   'pretzel',
   'precious',
   'appreciate'],
  'answers': ['PRETZEL'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20a_19',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Argentum nōn est pretiōsius aurō.',
  'multiple_choice_options': ['COMPARISON',
   'DEGREE OF DIFFERENCE',
   'SEPARATION'],
  'answers': ['COMPARISON'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20c_19',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Servī līberent sē servitūte.',
  'multiple_choice_options': ['COMPARISON',
   'DEGREE OF DIFFERENCE',
   'SEPARATION'],
  'answers': ['SEPARATION'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1b_30',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What use of the dative case is found in the following sentence: Nōbīs omnibus amandī sunt aliī?',
  'multiple_choice_options': ['COMPOUND VERBS', 'AGENCY', 'REFERENCE'],
  'answers': ['AGENCY'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1c_28',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What use of the dative case is found in the following sentence: Laudāvit mihi fratrem?',
  'multiple_choice_options': ['COMPOUND VERBS', 'AGENCY', 'REFERENCE'],
  'answers': ['REFERENCE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_24',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which case would be needed to translate “Publius” for this sentence: Marcus, why is Publius so handsome?',
  'multiple_choice_options': ['NOMINATIVE', 'DATIVE', 'GENITIVE'],
  'answers': ['NOMINATIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9b_24',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which case would be needed to translate “Publius” for this sentence: Marcus gave Publius a fountain.',
  'multiple_choice_options': ['NOMINATIVE', 'DATIVE', 'GENITIVE'],
  'answers': ['DATIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9c_24',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which case would be needed to translate “Publius” for this sentence: Publius’ house is not very austere.',
  'multiple_choice_options': ['NOMINATIVE', 'DATIVE', 'GENITIVE'],
  'answers': ['GENITIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_22',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What use of the genitive case is found in the following sentence: Maxima est potentia imperātōris.',
  'multiple_choice_options': ['POSSESSION',
   'PARTITIVE (GEN. OF THE WHOLE)',
   'QUALITY (DESCRIPTION)'],
  'answers': ['POSSESSION'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7_5',
  'question_format': 'multiple_choice',
  'question_content': 'translation',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate “Publius” into Latin for this sentence: Caesar sent Publius to Athens.',
  'multiple_choice_options': ['PUBLIUM', 'PUBLIŌ (PUBLIĪ)', 'PUBLĪ'],
  'answers': ['PUBLIUM'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5b_40',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Prōconsulēs fraude praecēdunt.',
  'multiple_choice_options': ['MEANS',
   'SPECIAL VERBS',
   'SPECIFICATION',
   'PRICE'],
  'answers': ['MEANS'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5c_38',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Agricola senex nōn voluit vendere fundum pecūniā.',
  'multiple_choice_options': ['MEANS',
   'SPECIAL VERBS',
   'SPECIFICATION',
   'PRICE'],
  'answers': ['PRICE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17a_33',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin numerals answers the question “In which order”:',
  'multiple_choice_options': ['secundus', 'bis', 'bīnī', 'duō', 'duplex'],
  'answers': ['SECUNDUS'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17b_33',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following answers the question “How many at a time”:',
  'multiple_choice_options': ['secundus', 'bis', 'bīnī', 'duō', 'duplex'],
  'answers': ['BĪNĪ'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17c_31',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following answers the question “How often”:',
  'multiple_choice_options': ['secundus', 'bis', 'bīnī', 'duō', 'duplex'],
  'answers': ['BIS'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10b_32',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin nouns does not belong because of gender:',
  'multiple_choice_options': ['bellum', 'legiō', 'animal', 'mare', 'cornū'],
  'answers': ['LEGIŌ'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10c_30',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin nouns does not belong because of gender:',
  'multiple_choice_options': ['cor', 'agricola', 'senātus', 'pēs', 'leō'],
  'answers': ['COR'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11a_34',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following does NOT belong because it is not a use of the genitive case: ',

In [27]:
# add letter options to MC questions
letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
for dict_ in final_dict:
    if dict_['question_format'] == 'multiple_choice':
        options = dict_['multiple_choice_options']
        if len(options) == 0:
            print(f"question {dict_['question_id']} has no options, changing to short answer")
            dict_['question_format'] = 'short_answer'
            dict_['multiple_choice_options'] = []
            continue
            
        if options[-1][-1] in ['?', '.', '!', ',']:
            options[-1] = options[-1][:-1]
        
        # update answer to be matching letter 
        curr_answer = dict_['answers'][0]

        if curr_answer.lower() == 'none':
            if options[-1] not in ['none', 'or none of the above']:
                options.append('none of the above')
            elif options[-1] in ['none', 'or none of the above']:
                options[-1] = 'none of the above'

            if options[-2].lower() == 'none' and options[-1].lower() == 'none of the above':
                # remove options[-2]
                options.pop(-2)
        
        new_options = [f"{letters[i]}: {opt}" for i, opt in enumerate(options)]
        dict_['multiple_choice_options'] = new_options    

        # update answer to be matching letter
        new_answer = get_letter(options, new_options, curr_answer, letters)
        if new_answer is not None:
            dict_['answers'] = [new_answer]

final_dict

question NJCL-Certamen_2000_2c_7 has no options, changing to short answer
question NJCL-Certamen_2000_5_3 has no options, changing to short answer
Matching hostile to hostile(adj)
Matching auriga to aurīga
Matching būbula to bubula
Matching posuistī to pōsuistī
Matching volabam to vōlābam
Matching mīlitī to mHitī

[{'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_1',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin preposition is the root of “country”?',
  'multiple_choice_options': ['A: CONTRA', 'B: CUM', 'C: ULTRA'],
  'answers': ['A: CONTRA'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11_0',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin root as the others:',
  'multiple_choice_options': ['A: sauce',
   'B: saline',
   'C: salad',
   'D: sausage',
   'E: sautee'],
  'answers': ['E: sautee'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_5',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the subjunctive is found in this sentence: Hōs latrōnēs interficiāmus?',
  'multiple_choice_options': ['A: HORTATORY',
   'B: DELIBERATIVE',
   'C: OPTATIVE'],
  'answers': ['A: HORTATORY'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15b_5',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the subjunctive is found in this sentence: Quid agam, iūdicēs? quō mē vertam?',
  'multiple_choice_options': ['A: HORTATORY',
   'B: DELIBERATIVE',
   'C: OPTATIVE'],
  'answers': ['B: DELIBERATIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15c_5',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the subjunctive is found in this sentence: Utinam mē mortuum vīdissēs?',
  'multiple_choice_options': ['A: HORTATORY',
   'B: DELIBERATIVE',
   'C: OPTATIVE'],
  'answers': ['C: OPTATIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3_2',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following English words, if any, IS derived from the pronoun ego:',
  'multiple_choice_options': ['A: eagle',
   'B: egg',
   'C: egalitarian',
   'D: egotist',
   'E: egret'],
  'answers': ['D: egotist'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12a_8',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from sum, esse:',
  'multiple_choice_options': ['A: consummate',
   'B: essence',
   'C: present',
   'D: entity',
   'E: interesting'],
  'answers': ['A: consummate'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12b_8',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from amō, amāre:',
  'multiple_choice_options': ['A: amiable',
   'B: enamor',
   'C: amaze',
   'D: amateur',
   'E: amatory'],
  'answers': ['C: amaze'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_7',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from habeō, habēre:',
  'multiple_choice_options': ['A: habit',
   'B: have',
   'C: ability',
   'D: prohibit',
   'E: habitat'],
  'answers': ['B: have'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_14a_9',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from locus:',
  'multiple_choice_options': ['A: location',
   'B: couch',
   'C: locomotion',
   'D: locular',
   'E: none of the above',
   'F: none of the above',
   'G: none of the above'],
  'answers': ['G: none of the above'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_14b_9',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from crēdere:',
  'multiple_choice_options': ['A: credit',
   'B: creed',
   'C: creation',
   'D: credulity'],
  'answers': ['C: creation'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_14c_9',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from lac: ',
  'multiple_choice_options': ['A: lactate',
   'B: lettuce',
   'C: laconic',
   'D: lacteal'],
  'answers': ['C: laconic'],
  'rm_opt_question': nan,
  'manual_edits': 1.0,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12a_13',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Greek root as the others:',
  'multiple_choice_options': ['A: elephant',
   'B: diaphanous',
   'C: phantom',
   'D: fantasy'],
  'answers': ['A: elephant'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12b_13',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Greek root as the others:',
  'multiple_choice_options': ['A: skeptic',
   'B: stethoscope',
   'C: bishop',
   'D: eschew'],
  'answers': ['D: eschew'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_12',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Greek root as the others:',
  'multiple_choice_options': ['A: paradox',
   'B: doxology',
   'C: dogmatic',
   'D: docket'],
  'answers': ['D: docket'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6a_17',
  'question_format': 'multiple_choice',
  'question_content': 'literary_devices',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Identify a figure of speech in these lines: Intereā māgnō miscērī murmure pontum ēmissaque hiemem sēnsit Neptūnus et īmīs',
  'multiple_choice_options': ['A: ALLITERATION',
   'B: ASSONANCE',
   'C: ONOMATOPOEIA'],
  'answers': ['A: ALLITERATION'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3a_24',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Which of the following, if any, is NOT derived from the same Latin word as the others:',
  'multiple_choice_options': ['A: praise',
   'B: prize',
   'C: pretzel',
   'D: precious',
   'E: appreciate'],
  'answers': ['C: pretzel'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20a_19',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Argentum nōn est pretiōsius aurō.',
  'multiple_choice_options': ['A: COMPARISON',
   'B: DEGREE OF DIFFERENCE',
   'C: SEPARATION'],
  'answers': ['A: COMPARISON'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20c_19',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Servī līberent sē servitūte.',
  'multiple_choice_options': ['A: COMPARISON',
   'B: DEGREE OF DIFFERENCE',
   'C: SEPARATION'],
  'answers': ['C: SEPARATION'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1b_30',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What use of the dative case is found in the following sentence: Nōbīs omnibus amandī sunt aliī?',
  'multiple_choice_options': ['A: COMPOUND VERBS',
   'B: AGENCY',
   'C: REFERENCE'],
  'answers': ['B: AGENCY'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1c_28',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What use of the dative case is found in the following sentence: Laudāvit mihi fratrem?',
  'multiple_choice_options': ['A: COMPOUND VERBS',
   'B: AGENCY',
   'C: REFERENCE'],
  'answers': ['C: REFERENCE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_24',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which case would be needed to translate “Publius” for this sentence: Marcus, why is Publius so handsome?',
  'multiple_choice_options': ['A: NOMINATIVE', 'B: DATIVE', 'C: GENITIVE'],
  'answers': ['A: NOMINATIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9b_24',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which case would be needed to translate “Publius” for this sentence: Marcus gave Publius a fountain.',
  'multiple_choice_options': ['A: NOMINATIVE', 'B: DATIVE', 'C: GENITIVE'],
  'answers': ['B: DATIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9c_24',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which case would be needed to translate “Publius” for this sentence: Publius’ house is not very austere.',
  'multiple_choice_options': ['A: NOMINATIVE', 'B: DATIVE', 'C: GENITIVE'],
  'answers': ['C: GENITIVE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_22',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What use of the genitive case is found in the following sentence: Maxima est potentia imperātōris.',
  'multiple_choice_options': ['A: POSSESSION',
   'B: PARTITIVE (GEN. OF THE WHOLE)',
   'C: QUALITY (DESCRIPTION)'],
  'answers': ['A: POSSESSION'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7_5',
  'question_format': 'multiple_choice',
  'question_content': 'translation',
  'difficulty': 'advanced',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate “Publius” into Latin for this sentence: Caesar sent Publius to Athens.',
  'multiple_choice_options': ['A: PUBLIUM', 'B: PUBLIŌ (PUBLIĪ)', 'C: PUBLĪ'],
  'answers': ['A: PUBLIUM'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5b_40',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Prōconsulēs fraude praecēdunt.',
  'multiple_choice_options': ['A: MEANS',
   'B: SPECIAL VERBS',
   'C: SPECIFICATION',
   'D: PRICE'],
  'answers': ['A: MEANS'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5c_38',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the ablative case is found in the following sentence: Agricola senex nōn voluit vendere fundum pecūniā.',
  'multiple_choice_options': ['A: MEANS',
   'B: SPECIAL VERBS',
   'C: SPECIFICATION',
   'D: PRICE'],
  'answers': ['D: PRICE'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17a_33',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin numerals answers the question “In which order”:',
  'multiple_choice_options': ['A: secundus',
   'B: bis',
   'C: bīnī',
   'D: duō',
   'E: duplex'],
  'answers': ['A: secundus'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17b_33',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following answers the question “How many at a time”:',
  'multiple_choice_options': ['A: secundus',
   'B: bis',
   'C: bīnī',
   'D: duō',
   'E: duplex'],
  'answers': ['C: bīnī'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17c_31',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following answers the question “How often”:',
  'multiple_choice_options': ['A: secundus',
   'B: bis',
   'C: bīnī',
   'D: duō',
   'E: duplex'],
  'answers': ['B: bis'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10b_32',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which of the following Latin nouns does not belong because of gender:',
  'multiple_choice_options': ['A: bellum',
   'B: legiō',
   'C: animal',
   'D: mare',
   'E: cornū'],
  'answers': ['B: legiō'],
  'rm_opt_question': nan,
  'manual_edits': nan,
  'answerable': nan,
  'mv_mc_opt': nan,
  'change_short_ans': nan},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10c_30',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',

In [29]:
# move back to df, remove columns
final_mc = pd.DataFrame(final_dict)

Series([], Name: count, dtype: int64)

In [32]:
final_mc.drop(columns=['rm_opt_question', 'manual_edits', 'answerable', 'mv_mc_opt', 'change_short_ans'], inplace=True)
final_mc

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers
0,NJCL-Certamen,1996,NJCL-Certamen_1996_9a_1,multiple_choice,vocabulary,unknown,english,latin,What Latin preposition is the root of “country”?,"[A: CONTRA, B: CUM, C: ULTRA]",[A: CONTRA]
1,NJCL-Certamen,1996,NJCL-Certamen_1996_11_0,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[A: sauce, B: saline, C: salad, D: sausage, E:...",[E: sautee]
2,NJCL-Certamen,1996,NJCL-Certamen_1996_15a_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[A: HORTATORY, B: DELIBERATIVE, C: OPTATIVE]",[A: HORTATORY]
3,NJCL-Certamen,1996,NJCL-Certamen_1996_15b_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[A: HORTATORY, B: DELIBERATIVE, C: OPTATIVE]",[B: DELIBERATIVE]
4,NJCL-Certamen,1996,NJCL-Certamen_1996_15c_5,multiple_choice,grammar,unknown,english,latin,What use of the subjunctive is found in this s...,"[A: HORTATORY, B: DELIBERATIVE, C: OPTATIVE]",[C: OPTATIVE]
...,...,...,...,...,...,...,...,...,...,...,...
331,NJCL-Certamen,2002,NJCL-Certamen_2002_3_66,short_answer,literature,advanced,english,english,"In Book 6 of Ovid’s Metamorphoses, into what k...",[],[FROGS]
332,NJCL-Certamen,2002,NJCL-Certamen_2002_2_63,multiple_choice,vocabulary,unknown,english,latin,Which of the following animals is described in...,"[A: delphīnus, B: gallus, C: orca, D: testūdō,...",[B: gallus]
333,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_838,multiple_choice,vocabulary,advanced,english,english,"Which of the following, if any, is NOT derived...","[A: lieutenant, B: location, C: allocate, D: l...",[E: none of the above]
334,NJCL-Certamen,2002,NJCL-Certamen_2002_10_71,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[A: sojourn, B: conjure, C: meridian, D: circa...",[B: conjure]
335,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_870,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[A: vintner, B: vinyl, C: vicious, D: vignette...",[C: vicious]

In [33]:
# drop unanswerable ids from original df
df = df[~df['question_id'].isin(unanswerable_ids)]
df = df[~df['question_id'].isin(unanswerable_nonempty_ids)]
df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers
0,NJCL-Certamen,1996,NJCL-Certamen_1996_1a_0,short_answer,history,unknown,english,latin,What name was given to the large agricultural ...,[],[LATIFUNDIA]
1,NJCL-Certamen,1996,NJCL-Certamen_1996_1b_0,short_answer,history,unknown,english,latin,What was the manager or overseer of a latifund...,[],[VILICUS]
2,NJCL-Certamen,1996,NJCL-Certamen_1996_4a_0,short_answer,vocabulary,unknown,latin,latin,Quod animal facit mel?,[],[APIS]
3,NJCL-Certamen,1996,NJCL-Certamen_1996_6b_0,short_answer,literature,unknown,english,english,Who was Odysseus' long-suffering wife?,[],[Penelope]
4,NJCL-Certamen,1996,NJCL-Certamen_1996_7a_0,short_answer,grammar,unknown,english,latin,"Give the first person singular, present passiv...",[],[VEHAR]
...,...,...,...,...,...,...,...,...,...,...,...
4933,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_894,short_answer,history,advanced,english,latin,Name the last of the Gallic emperors whom Aure...,[],[TETRICUS]
4934,NJCL-Certamen,2002,NJCL-Certamen_2002_12_76,short_answer,mythology,unknown,english,latin,"Which deity, according to Aeschylus, was “kind...",[],[ARTEMIS]
4935,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_887,short_answer,mythology,unknown,english,latin,Who was so chaste and devoted to Artemis that ...,[],[HIPPOLYTUS]
4936,NJCL-Certamen,2002,NJCL-Certamen_2002_B2_896,short_answer,mythology,unknown,english,latin,Who almost married Artemis but was killed by t...,[],[ORION]
4937,NJCL-Certamen,2002,NJCL-Certamen_2002_14b_66,short_answer,history,advanced,english,english,How many tabulae were produced by the commissi...,[],[TEN]

In [34]:
full_dict = df.to_dict(orient='records')
full_dict

[{'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1a_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What name was given to the large agricultural estates which resulted from the distribution of the ager publicus in the 2nd century B.C.?',
  'multiple_choice_options': [],
  'answers': ['LATIFUNDIA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_1b_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What was the manager or overseer of a latifundia called?',
  'multiple_choice_options': [],
  'answers': ['VILICUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4a_0',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'latin',
  'answer_language': 'latin',
  'question': 'Quod animal facit mel?',
  'multiple_choice_options': [],
  'answers': ['APIS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6b_0',
  'question_format': 'short_answer',
  'question_content': 'literature',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': "Who was Odysseus' long-suffering wife?",
  'multiple_choice_options': [],
  'answers': ['Penelope']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7a_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Give the first person singular, present passive subjunctive of vehō.',
  'multiple_choice_options': [],
  'answers': ['VEHAR']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7b_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Change vehar to imperfect.',
  'multiple_choice_options': [],
  'answers': ['VEHERER']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7c_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Change veherer to pluperfect active.',
  'multiple_choice_options': [],
  'answers': ['VEXISSEM']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7d_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What tense is iaciēs?',
  'multiple_choice_options': [],
  'answers': ['FUTURE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7e_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What tense is iaciās?',
  'multiple_choice_options': [],
  'answers': ['PRESENT']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7f_0',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What tense is iacēs?',
  'multiple_choice_options': [],
  'answers': ['PRESENT']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10a_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who was the Greek god of prophecy?',
  'multiple_choice_options': [],
  'answers': ['APOLLO']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10b_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Where did Apollo establish his main oracle in Greece?',
  'multiple_choice_options': [],
  'answers': ['DELPHI']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who was the father of Iphicles?',
  'multiple_choice_options': [],
  'answers': ['AMPHITRYON']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who forbade the memory of his brother and ordered the erasure of his name from all inscriptions in AD 212?',
  'multiple_choice_options': [],
  'answers': ['CARACALLA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15b_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Name the brother whom Caracalla had murdered.',
  'multiple_choice_options': [],
  'answers': ['GETA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_16a_0',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate into Latin the relative pronoun for the following English sentence: Julia, whose mother is rich, is the daughter of a senator.',
  'multiple_choice_options': [],
  'answers': ['CUIUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_16b_0',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate into Latin the relative pronoun for the following English sentence: The soldier did not like the others with whom he was traveling.',
  'multiple_choice_options': [],
  'answers': ['QUIBUS(CUM)']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_16c_0',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Translate into Latin the relative pronoun for the following English sentence: The farm, of which Horace was in charge, is burning to the ground.',
  'multiple_choice_options': [],
  'answers': ['CUĪ']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17a_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which centaur tried to kidnap Deianira, the wife of Hercules?',
  'multiple_choice_options': [],
  'answers': ['NESSUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_17b_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'According to Ovid, who was the father of Nessus?',
  'multiple_choice_options': [],
  'answers': ['IXION']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_18a_0',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'Latin is an inflected language. What is the meaning of the verb at the root of “inflected”?',
  'multiple_choice_options': [],
  'answers': ['BEND']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_18c_0',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'In Latin, as in English, there are three degrees of comparison. What is the meaning of the adjective at the root of “comparison”?',
  'multiple_choice_options': [],
  'answers': ['EQUAL']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_19a_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who gave shelter to Danae and her son Perseus?',
  'multiple_choice_options': [],
  'answers': ['Dictys']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_19b_0',
  'question_format': 'short_answer',
  'question_content': 'geography',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'On what island did Dictys live?',
  'multiple_choice_options': [],
  'answers': ['Seriphus']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_19c_0',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': "Name Dictys' brother who wanted to marry Danae.",
  'multiple_choice_options': [],
  'answers': ['Polydectes']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_20_0',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What foreign enemy general campaigned in Italy for 16 years, but was unable to capture Rome?',
  'multiple_choice_options': [],
  'answers': ['HANNIBAL']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3b_1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'What household cooking substance is derived from ācer?',
  'multiple_choice_options': [],
  'answers': ['VINEGAR']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_3c_1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What is the Latin word for vinegar?',
  'multiple_choice_options': [],
  'answers': ['ACĒTUM']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4a_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What great Trojan hero was the husband of Andromache?',
  'multiple_choice_options': [],
  'answers': ['HECTOR']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_4b_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Greek hero killed Hector?',
  'multiple_choice_options': [],
  'answers': ['ACHILLES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5a_1',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who was the oldest of the four emperors proclaimed in A. D. 69?',
  'multiple_choice_options': [],
  'answers': ['Galba']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_5b_1',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who urged Galba to take the imperial throne from Nero?',
  'multiple_choice_options': [],
  'answers': ['Vindex']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_6a_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What daughter of Cadmus was the wife of Athamas?',
  'multiple_choice_options': [],
  'answers': ['INO']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7c_1',
  'question_format': 'multiple_choice',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What use of the genitive case is found in the following sentence: Senatōrum togae sunt sordidae.',
  'multiple_choice_options': nan,
  'answers': ['POSSESSIVE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_7d_1',
  'question_format': 'short_answer',
  'question_content': 'history',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Who ruled Italy after the deposition of the boy emperor Romulus Augustulus?',
  'multiple_choice_options': [],
  'answers': ['ODO(V)ACER']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9a_1',
  'question_format': 'multiple_choice',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin preposition is the root of “country”?',
  'multiple_choice_options': ['CONTRA', 'CUM', 'ULTRA'],
  'answers': ['CONTRA']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9b_1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin adjective is the root of “farm”?',
  'multiple_choice_options': [],
  'answers': ['FIRMUS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_9c_1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What Latin noun is the root of “salvage”?',
  'multiple_choice_options': [],
  'answers': ['SALŪS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10b_1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Using the verb volō, velle translate “want” into Latin for the following sentence:\nJulia, I don’t know why you want to go to the zoo to see those silly animals.',
  'multiple_choice_options': [],
  'answers': ['VELĪS']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_10c_1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Using the verb volō, velle translate “want” into Latin for the following sentence:\nI think I want to stay home.',
  'multiple_choice_options': [],
  'answers': ['VELLE']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11a_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Name the son of Zeus and Hera who was the god of war.',
  'multiple_choice_options': [],
  'answers': ['ARES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_11b_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'What other deity appreciated Ares because he increased the inhabitants of his kingdom?',
  'multiple_choice_options': [],
  'answers': ['HADES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12a_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': "Who was Odysseus' father, for whom Penelope was supposedly weaving a shroud?",
  'multiple_choice_options': [],
  'answers': ['LAERTES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_12c_1',
  'question_format': 'short_answer',
  'question_content': 'mythology',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Which father of one of the suitors was killed by the elderly Laertes?',
  'multiple_choice_options': [],
  'answers': ['EUPITHES']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13a_1',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Change aggrediēbantur to subjunctive.',
  'multiple_choice_options': [],
  'answers': ['aggrederentur']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_13b_1',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question': 'Change aggrederentur to present.',
  'multiple_choice_options': [],
  'answers': ['aggrediuntur']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15a_1',
  'question_format': 'short_answer',
  'question_content': 'geography',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'In what modern country would all or most of the imperial province of Asia have been located?',
  'multiple_choice_options': [],
  'answers': ['Turkey']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15b_1',
  'question_format': 'short_answer',
  'question_content': 'geography',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'In what modern country would all or most of the imperial province of Baetica have been located?',
  'multiple_choice_options': [],
  'answers': ['Spain']},
 {'source_name': 'NJCL-Certamen',
  'source_year': 1996,
  'question_id': 'NJCL-Certamen_1996_15c_1',
  'question_format': 'short_answer',
  'question_content': 'geography',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question': 'In what modern country would all or most of the imperial province of Macedonia have been located?',

In [35]:
replace_ids = final_mc['question_id'].tolist()

# drop these from df 
df = df[~df['question_id'].isin(replace_ids)]
df
# add back to df
df = pd.concat([df, final_mc])
df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers
0,NJCL-Certamen,1996,NJCL-Certamen_1996_1a_0,short_answer,history,unknown,english,latin,What name was given to the large agricultural ...,[],[LATIFUNDIA]
1,NJCL-Certamen,1996,NJCL-Certamen_1996_1b_0,short_answer,history,unknown,english,latin,What was the manager or overseer of a latifund...,[],[VILICUS]
2,NJCL-Certamen,1996,NJCL-Certamen_1996_4a_0,short_answer,vocabulary,unknown,latin,latin,Quod animal facit mel?,[],[APIS]
3,NJCL-Certamen,1996,NJCL-Certamen_1996_6b_0,short_answer,literature,unknown,english,english,Who was Odysseus' long-suffering wife?,[],[Penelope]
4,NJCL-Certamen,1996,NJCL-Certamen_1996_7a_0,short_answer,grammar,unknown,english,latin,"Give the first person singular, present passiv...",[],[VEHAR]
...,...,...,...,...,...,...,...,...,...,...,...
331,NJCL-Certamen,2002,NJCL-Certamen_2002_3_66,short_answer,literature,advanced,english,english,"In Book 6 of Ovid’s Metamorphoses, into what k...",[],[FROGS]
332,NJCL-Certamen,2002,NJCL-Certamen_2002_2_63,multiple_choice,vocabulary,unknown,english,latin,Which of the following animals is described in...,"[A: delphīnus, B: gallus, C: orca, D: testūdō,...",[B: gallus]
333,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_838,multiple_choice,vocabulary,advanced,english,english,"Which of the following, if any, is NOT derived...","[A: lieutenant, B: location, C: allocate, D: l...",[E: none of the above]
334,NJCL-Certamen,2002,NJCL-Certamen_2002_10_71,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[A: sojourn, B: conjure, C: meridian, D: circa...",[B: conjure]
335,NJCL-Certamen,2002,NJCL-Certamen_2002_B1_870,multiple_choice,vocabulary,unknown,english,english,"Which of the following, if any, is NOT derived...","[A: vintner, B: vinyl, C: vicious, D: vignette...",[C: vicious]

In [36]:
# separately save the short answer and MC questions
short_answer_df = df[df['question_format'] == 'short_answer']
mc_df = df[df['question_format'] == 'multiple_choice']

assert len(short_answer_df) + len(mc_df) == len(df)

In [38]:
# save as json
short_answer_dict = short_answer_df.to_dict(orient='records')
with open('../data/final_dataset/certamen_short_answer.json', 'w') as f:
    json.dump(short_answer_dict, f, indent=4)

mc_dict = mc_df.to_dict(orient='records')
with open('../data/final_dataset/certamen_mc.json', 'w') as f:
    json.dump(mc_dict, f, indent=4)