In [2]:
import json
import pandas as pd

from openai import OpenAI
from time import sleep


with open('openai-api-key.txt', 'r') as f:
    openai_api_key = f.read().strip()

openai_client = OpenAI(api_key=openai_api_key)

In [2]:
# separate the translation from other questions
with open('../data/structured/junior_scholarship.json', 'r') as f:
    questions = json.load(f)

question_df = pd.DataFrame(questions)
len(question_df)

3746

In [17]:
question_df['answers'].apply(type).value_counts()

answers
<class 'list'>    3746
Name: count, dtype: int64

In [3]:
# drop empty answers (where answers cell is != [""])
question_df = question_df[question_df['answers'].apply(lambda x: x != [""])]
len(question_df)

3714

In [4]:
# unique question ids
len(question_df['question_id'].unique())

3714

In [23]:
# non-translation questions
short_answer_long = question_df[question_df['question_content'] != 'translation']
short_answer_long

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question_text,multiple_choice_options,answers
0,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_1.1.1,short_answer,grammar,unknown,english,english,Which nouns of the first declension make the g...,[],[Compounds of _colo_ and _gigno_; _drachma_ an...
1,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_1.1.2,short_answer,grammar,unknown,english,english,Which nouns of the second declension make the ...,[],"[Weights, coins, trades, measures; dissyllable..."
2,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_1.2.1,short_answer,grammar,unknown,english,latin,Decline Æneas in the singular.,[],"[N. Æneas, V. Æneas, Ac. Ænean, G. Æneæ, D. Æn..."
3,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_1.2.2,short_answer,grammar,unknown,english,latin,Decline Cybele in the singular.,[],"[N. Cybele, V. Cybele, Ac. Cybelen, G. Cybeles..."
4,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_1.2.3,short_answer,grammar,unknown,english,latin,Decline respublica in the singular.,[],"[N. respublica, V. respublica, Ac. rempublicam..."
...,...,...,...,...,...,...,...,...,...,...,...
3741,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.10.14,short_answer,vocabulary,unknown,english,english,"Explain the term ""relegatio.""",[],[More honourable form of banishment.]
3742,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.10.15,short_answer,vocabulary,unknown,english,english,"Explain the term ""majestas.""",[],[High treason.]
3743,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.10.16,short_answer,vocabulary,unknown,english,english,"Explain the term ""res repetundae.""",[],[Embezzlement.]
3744,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.10.17,short_answer,vocabulary,unknown,english,english,"Explain the term ""spolia optima.""",[],[Spoils taken by commander of one army from th...
3745,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.10.18,short_answer,vocabulary,unknown,english,english,"Explain the term ""sub jugo mittere.""",[],[To send conquered enemy under yoke (three spe...

In [24]:
# filter to one word responses
short_answer = short_answer_long[short_answer_long['answers'].apply(len) == 1]
short_answer = short_answer[short_answer['answers'].apply(lambda x: ' ' not in x[0])]
short_answer

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question_text,multiple_choice_options,answers
57,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_2.4.3,short_answer,grammar,unknown,english,latin,Give the acc. sing. of *Thisbe*.,[],[Thisben.]
59,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_2.4.5,short_answer,grammar,unknown,english,latin,Give the acc. sing. of *Peleus*.,[],[Pelea.]
60,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_2.4.6,short_answer,grammar,unknown,english,latin,Give the acc. sing. of *vis*.,[],[Vim.]
62,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_2.5.2,short_answer,vocabulary,unknown,english,latin,What other forms are used for *penus*?,[],[Penum.]
64,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_2.5.4,short_answer,vocabulary,unknown,english,latin,What other forms are used for *vespere*?,[],[Vesperi.]
...,...,...,...,...,...,...,...,...,...,...,...
3698,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.1.2,short_answer,vocabulary,unknown,english,english,What is a tunica?,[],[Under-garment.]
3725,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.9.1,short_answer,vocabulary,unknown,english,latin,"Give the Latin for ""starting-post.""",[],[*Carceres*]
3726,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.9.2,short_answer,vocabulary,unknown,english,latin,"Give the Latin for ""half-way-post.""",[],[*meta*]
3729,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.10.2,short_answer,vocabulary,unknown,english,english,"Explain the term ""emeritus.""",[],[Veteran.]
3743,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.10.16,short_answer,vocabulary,unknown,english,english,"Explain the term ""res repetundae.""",[],[Embezzlement.]

In [25]:
short_answer_df = short_answer 

short_answer = short_answer_df.to_dict(orient='records')
short_answer

[{'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_2.4.3',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the acc. sing. of *Thisbe*.',
  'multiple_choice_options': [],
  'answers': ['Thisben.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_2.4.5',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the acc. sing. of *Peleus*.',
  'multiple_choice_options': [],
  'answers': ['Pelea.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_2.4.6',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the acc. sing. of *vis*.',
  'multiple_choice_options': [],
  'answers': ['Vim.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_2.5.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What other forms are used for *penus*?',
  'multiple_choice_options': [],
  'answers': ['Penum.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_2.5.4',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What other forms are used for *vespere*?',
  'multiple_choice_options': [],
  'answers': ['Vesperi.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_2.5.5',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What other forms are used for *nocte*?',
  'multiple_choice_options': [],
  'answers': ['Noctu.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.8.1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the feminine form of leo.',
  'multiple_choice_options': [],
  'answers': ['Leaena.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.8.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the feminine form of asinus.',
  'multiple_choice_options': [],
  'answers': ['Asina.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.8.3',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the feminine form of equus.',
  'multiple_choice_options': [],
  'answers': ['Equua.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.8.4',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the feminine form of Cres.',
  'multiple_choice_options': [],
  'answers': ['Cressa.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.8.5',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the feminine form of Laco.',
  'multiple_choice_options': [],
  'answers': ['Lacaena.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.10.9',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'What is the meaning of "preces"?',
  'multiple_choice_options': [],
  'answers': ['Prayers.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.10.11',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'What is the meaning of "indutiae"?',
  'multiple_choice_options': [],
  'answers': ['Truce.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_4.8.1',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'What alternative spelling is there for -*es* in the accusative plural of the third declension in Latin grammar?',
  'multiple_choice_options': [],
  'answers': ['-is.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the diminutive form of "cornu"?',
  'multiple_choice_options': [],
  'answers': ['Cornicula']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the diminutive form of "liber"?',
  'multiple_choice_options': [],
  'answers': ['Libellus']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.3',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the diminutive form of "lapis"?',
  'multiple_choice_options': [],
  'answers': ['Lapillus']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.4',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the substantive expressing the quality of "fortis"?',
  'multiple_choice_options': [],
  'answers': ['Fortitudo']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.5',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the substantive expressing the quality of "bonus"?',
  'multiple_choice_options': [],
  'answers': ['Bonitas']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.6',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the substantive expressing the quality of "justus"?',
  'multiple_choice_options': [],
  'answers': ['Justitia']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.7',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the substantive expressing the quality of "audax"?',
  'multiple_choice_options': [],
  'answers': ['Audacitas']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.8',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the substantive expressing the quality of "sapiens"?',
  'multiple_choice_options': [],
  'answers': ['Sapientia']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.8.1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'both',
  'question_text': 'What other forms are used for—vesper?',
  'multiple_choice_options': [],
  'answers': ['Vespera.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.8.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'both',
  'question_text': 'What other forms are used for—requiete?',
  'multiple_choice_options': [],
  'answers': ['Requie.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.8.4',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'both',
  'question_text': 'What other forms are used for—Jupiter?',
  'multiple_choice_options': [],
  'answers': ['Diespiter.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.9.1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What contraction is used in poetry for the genitive singular of consilium?',
  'multiple_choice_options': [],
  'answers': ['consili']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.9.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What contraction is used in poetry for the genitive plural of parens?',
  'multiple_choice_options': [],
  'answers': ['parentum']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.9.3',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What contraction is used in poetry for the dative singular of metus?',
  'multiple_choice_options': [],
  'answers': ['metu']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.10.1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What indeclinable means "right"?',
  'multiple_choice_options': [],
  'answers': ['*Fas*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.10.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What indeclinable means "wrong"?',
  'multiple_choice_options': [],
  'answers': ['*Nefas*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.10.3',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What indeclinable means "likeness"?',
  'multiple_choice_options': [],
  'answers': ['*Instar*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.10.4',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What indeclinable means "necessity"?',
  'multiple_choice_options': [],
  'answers': ['*Necesse*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.1.1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "gold."',
  'multiple_choice_options': [],
  'answers': ['*Aurum*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.1.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "silver."',
  'multiple_choice_options': [],
  'answers': ['*Argentum*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.1.3',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "copper."',
  'multiple_choice_options': [],
  'answers': ['*Aes*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.1.4',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "lead."',
  'multiple_choice_options': [],
  'answers': ['*Plumbum*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.1.5',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "iron."',
  'multiple_choice_options': [],
  'answers': ['*Ferrum*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.1.6',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "steel."',
  'multiple_choice_options': [],
  'answers': ['*Chalybs*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.1',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *leo*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Leonis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.2',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *virgo*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Virginis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.3',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *Cato*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Catonis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.4',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *Apollo*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Apollinis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.5',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *Macedo*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Maconis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.6',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *multitudo*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Multitudinis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.7',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *ferrugo*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Ferruginis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.8',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *temo*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Temōnis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,

are short answer questions answerable?

In [26]:
answerable_prompt='''I will give you a question and its answer.
Please decide if the question is answerable based on the given answer, and the added context that the question is related to Roman and Greek history, mythology, and geography, and Latin language and grammar. This additional context is provided along with the question, so you should take it into account.
Unanswerable questions don't have enough information. For example, if the question references a diagram, map, or table that is not provided, the question is unanswerable. If the question refers to a phrase or text that is not provided, the question is unanswerable. 

Please respond simply with "answerable" or "unanswerable".
'''

In [28]:
len(short_answer)

748

In [29]:
ids = []
responses = []

N = len(short_answer)

# continue from where we left off, or from first error response
for i in range(len(short_answer)):
    #if i < len(responses) and responses[i] != 'error':
    #    continue
    print(i, end=' ')

    q_id = short_answer[i]['question_id']
    question = short_answer[i]['question_text']
    answer = short_answer[i]['answers'][0]
    multiple_choice = short_answer[i]['multiple_choice_options']

    prompt = answerable_prompt 
    prompt += f"\nHere is the question: {question}\n"
    if multiple_choice:
        choice_str = '\n'.join(multiple_choice)
        prompt += f"Here are the multiple choice options: {choice_str}\n"
    prompt += f"Answer: {answer}\n"
    
    try:
        response = openai_client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant."},
                    {"role": "user", "content": prompt}
                ]
            )
        resp = response.choices[0].message.content
    except Exception as e:
        print(f"Error on question {i}: {e}")
        resp = 'error'
    
    #if responses[i] == 'error':
    #    responses[i] = resp
    #elif i < len(responses):
    responses.append(resp)
    ids.append(q_id)

    if i % 50 == 0:
        print(f"{i+1}/{N}")
        # dump to json
        with open('../data/structured/junior_answerable_responses.json', 'w') as f:
            json.dump(responses, f, indent=4)

    sleep(.01)

# save final 
with open('../data/structured/junior_answerable_responses.json', 'w') as f:
    json.dump(responses, f, indent=4)

0 1/748
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51/748
51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101/748
101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151/748
151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201/748
201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251/748
251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301/748
301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351/748
351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401/748
401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451/748
451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501/748
501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551/748
551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597 598 599 600 601/748
601 602 603 604 605 606 607 608 609 610 611 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648 649 650 651/748
651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701/748
701 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738 739 740 741 742 743 744 745 746 747

In [30]:
from collections import Counter
lower_resp = [r.lower() for r in responses]
lower_resp = [r.replace('.', '') for r in lower_resp]
count_resp = Counter(lower_resp)
count_resp

Counter({'answerable': 600, 'unanswerable': 148})

In [31]:
short_answer_df['answerable'] = lower_resp

In [32]:
unanswerable_df = short_answer_df[short_answer_df['answerable'] == 'unanswerable']
unanswerable_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question_text,multiple_choice_options,answers,answerable
102,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_3.8.3,short_answer,vocabulary,unknown,english,latin,Give the feminine form of equus.,[],[Equua.],unanswerable
243,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_5.8.2,short_answer,vocabulary,unknown,english,both,What other forms are used for—requiete?,[],[Requie.],unanswerable
247,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_5.9.2,short_answer,vocabulary,unknown,english,latin,What contraction is used in poetry for the gen...,[],[parentum],unanswerable
257,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_6.1.4,short_answer,vocabulary,unknown,english,latin,"Give the Latin for ""lead.""",[],[*Plumbum*],unanswerable
267,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_6.3.2,short_answer,grammar,unknown,english,latin,What is the genitive singular form of *virgo*?...,[],[*Virginis*],unanswerable
...,...,...,...,...,...,...,...,...,...,...,...,...
3644,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.6.8,short_answer,vocabulary,unknown,english,english,What is symbolized by *ignis et aqua*?,[],[Submission.],unanswerable
3651,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_115.3.1,short_answer,vocabulary,unknown,english,latin,"What is the meaning of the Latin expression ""S...",[],[Siccine],unanswerable
3662,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.III.1.5,short_answer,mythology,unknown,english,english,Name the deity of strength.,[],[Hercules],unanswerable
3725,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.9.1,short_answer,vocabulary,unknown,english,latin,"Give the Latin for ""starting-post.""",[],[*Carceres*],unanswerable
3729,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.10.2,short_answer,vocabulary,unknown,english,english,"Explain the term ""emeritus.""",[],[Veteran.],unanswerable

In [33]:
# save to tsv
with open('../data/structured/junior_unanswerable.tsv', 'w') as f:
    unanswerable_df.to_csv(f, sep='\t')

In [40]:
# load edited unanswerable questions
unanswerable_df = pd.read_csv('../data/structured/junior_unanswerable_edits.tsv', sep='\t')
unanswerable_df = unanswerable_df.drop(columns=['Unnamed: 0'])
unanswerable_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question_text,multiple_choice_options,answers,answerable,edits
0,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_3.8.3,short_answer,vocabulary,unknown,english,latin,Give the feminine form of equus.,[],['Equua.'],1,NaN
1,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_5.8.2,short_answer,vocabulary,unknown,english,both,What other forms are used for—requiete?,[],['Requie.'],0,NaN
2,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_5.9.2,short_answer,vocabulary,unknown,english,latin,What contraction is used in poetry for the gen...,[],['parentum'],1,NaN
3,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_6.1.4,short_answer,vocabulary,unknown,english,latin,"Give the Latin for ""lead"" (metal)",[],['*Plumbum*'],1,1.0
4,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_6.3.2,short_answer,grammar,unknown,english,latin,What is the genitive singular form of *virgo*?,[],['*Virginis*'],1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.6.8,short_answer,vocabulary,unknown,english,english,What is symbolized by *ignis et aqua*?,[],['Submission.'],0,NaN
144,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_115.3.1,short_answer,vocabulary,unknown,english,latin,"What is the meaning of the Latin expression ""S...",[],['Siccine'],0,NaN
145,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.III.1.5,short_answer,mythology,unknown,english,english,Name the deity of strength.,[],['Hercules'],0,NaN
146,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.9.1,short_answer,vocabulary,unknown,english,latin,"Give the Latin for ""starting-post.""",[],['*Carceres*'],1,NaN
147,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.10.2,short_answer,vocabulary,unknown,english,english,"Explain the term ""emeritus.""",[],['Veteran.'],0,NaN

In [36]:
unanswerable_ids = unanswerable_df[unanswerable_df['answerable'] == 0]['question_id'].tolist()
len(unanswerable_ids)

48

In [39]:
# ids where edit = 1
update_ids = unanswerable_df[unanswerable_df['edits'] == 1.0]['question_id'].tolist()
len(update_ids)

48

In [42]:
# drop unanswerable from short_answer_df
short_answer_df = short_answer_df[~short_answer_df['question_id'].isin(unanswerable_ids)]
len(short_answer_df)

700

In [43]:
# update the questions with edits
short_answer_dict = short_answer_df.to_dict(orient='records')
for i, dict_ in enumerate(short_answer_dict):
    this_id = dict_['question_id']
    if this_id in update_ids:
        # find the row in unanswerable_df
        new_row = unanswerable_df[unanswerable_df['question_id'] == this_id]
        # drop the "edits" column
        new_row = new_row.drop(columns=['edits'])
        # turn into dict
        new_row = new_row.to_dict(orient='records')[0]
        # update the row
        short_answer_dict[i] = new_row
    # delete the "answerable" key 
    del short_answer_dict[i]['answerable']

short_answer_dict

[{'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_2.4.3',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the acc. sing. of *Thisbe*.',
  'multiple_choice_options': [],
  'answers': ['Thisben.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_2.4.5',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the acc. sing. of *Peleus*.',
  'multiple_choice_options': [],
  'answers': ['Pelea.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_2.4.6',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the acc. sing. of *vis*.',
  'multiple_choice_options': [],
  'answers': ['Vim.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_2.5.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What other forms are used for *penus*?',
  'multiple_choice_options': [],
  'answers': ['Penum.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_2.5.4',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What other forms are used for *vespere*?',
  'multiple_choice_options': [],
  'answers': ['Vesperi.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_2.5.5',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What other forms are used for *nocte*?',
  'multiple_choice_options': [],
  'answers': ['Noctu.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.8.1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the feminine form of leo.',
  'multiple_choice_options': [],
  'answers': ['Leaena.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.8.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the feminine form of asinus.',
  'multiple_choice_options': [],
  'answers': ['Asina.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.8.3',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the feminine form of equus.',
  'multiple_choice_options': [],
  'answers': ['Equua.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.8.4',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the feminine form of Cres.',
  'multiple_choice_options': [],
  'answers': ['Cressa.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.8.5',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the feminine form of Laco.',
  'multiple_choice_options': [],
  'answers': ['Lacaena.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.10.9',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'What is the meaning of "preces"?',
  'multiple_choice_options': [],
  'answers': ['Prayers.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_3.10.11',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'What is the meaning of "indutiae"?',
  'multiple_choice_options': [],
  'answers': ['Truce.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_4.8.1',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'What alternative spelling is there for -*es* in the accusative plural of the third declension in Latin grammar?',
  'multiple_choice_options': [],
  'answers': ['-is.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the diminutive form of "cornu"?',
  'multiple_choice_options': [],
  'answers': ['Cornicula']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the diminutive form of "liber"?',
  'multiple_choice_options': [],
  'answers': ['Libellus']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.3',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the diminutive form of "lapis"?',
  'multiple_choice_options': [],
  'answers': ['Lapillus']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.4',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the substantive expressing the quality of "fortis"?',
  'multiple_choice_options': [],
  'answers': ['Fortitudo']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.5',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the substantive expressing the quality of "bonus"?',
  'multiple_choice_options': [],
  'answers': ['Bonitas']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.6',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the substantive expressing the quality of "justus"?',
  'multiple_choice_options': [],
  'answers': ['Justitia']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.7',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the substantive expressing the quality of "audax"?',
  'multiple_choice_options': [],
  'answers': ['Audacitas']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.5.8',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Question text: What is the substantive expressing the quality of "sapiens"?',
  'multiple_choice_options': [],
  'answers': ['Sapientia']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.8.1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'both',
  'question_text': 'What other forms are used for—vesper?',
  'multiple_choice_options': [],
  'answers': ['Vespera.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.8.4',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'both',
  'question_text': 'What other forms are used for—Jupiter?',
  'multiple_choice_options': [],
  'answers': ['Diespiter.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.9.1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What contraction is used in poetry for the genitive singular of consilium?',
  'multiple_choice_options': [],
  'answers': ['consili']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.9.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What contraction is used in poetry for the genitive plural of parens?',
  'multiple_choice_options': [],
  'answers': ['parentum']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.9.3',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What contraction is used in poetry for the dative singular of metus?',
  'multiple_choice_options': [],
  'answers': ['metu']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.10.1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What indeclinable means "right"?',
  'multiple_choice_options': [],
  'answers': ['*Fas*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.10.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What indeclinable means "wrong"?',
  'multiple_choice_options': [],
  'answers': ['*Nefas*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.10.3',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What indeclinable means "likeness"?',
  'multiple_choice_options': [],
  'answers': ['*Instar*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_5.10.4',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What indeclinable means "necessity"?',
  'multiple_choice_options': [],
  'answers': ['*Necesse*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.1.1',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "gold."',
  'multiple_choice_options': [],
  'answers': ['*Aurum*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.1.2',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "silver."',
  'multiple_choice_options': [],
  'answers': ['*Argentum*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.1.3',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "copper."',
  'multiple_choice_options': [],
  'answers': ['*Aes*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.1.4',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "lead" (metal)',
  'multiple_choice_options': '[]',
  'answers': "['*Plumbum*']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.1.5',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "iron."',
  'multiple_choice_options': [],
  'answers': ['*Ferrum*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.1.6',
  'question_format': 'short_answer',
  'question_content': 'vocabulary',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "steel."',
  'multiple_choice_options': [],
  'answers': ['*Chalybs*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.1',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *leo*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Leonis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.2',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *virgo*? ',
  'multiple_choice_options': '[]',
  'answers': "['*Virginis*']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.3',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *Cato*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Catonis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.4',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *Apollo*?',
  'multiple_choice_options': '[]',
  'answers': "['*Apollinis*']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.5',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *Macedo*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Maconis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.6',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *multitudo*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Multitudinis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.7',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *ferrugo*? ',
  'multiple_choice_options': '[]',
  'answers': "['*Ferruginis*']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.8',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *temo*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Temōnis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_6.3.9',
  'question_format': 'short_answer',
  'question_content': 'grammar',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'What is the genitive singular form of *ordo*? (Mark the quantities of penults.)',
  'multiple_choice_options': [],
  'answers': ['*Ordinis*']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,

In [44]:
len(short_answer_dict)

700

In [45]:
# save to json
with open('../data/structured/junior_scholarship_short_answer.json', 'w') as f:
    json.dump(short_answer_dict, f, indent=4)

translation questions

In [5]:
translation_df = question_df[question_df['question_content'] == 'translation']
translation_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question_text,multiple_choice_options,answers
187,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_4.10.1,short_answer,translation,unknown,english,both,"Put into Latin in two ways—""There is need (*op...",[],[Opus est mihi equo (abl.). Equus est opus mihi.]
624,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_14.7.1,short_answer,translation,unknown,english,latin,"Put into Latin—""This is my house, such as it is.""",[],"[Haec mea domus, quantulacumque est.]"
636,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_14.11.1,short_answer,translation,unknown,english,latin,"Put into Latin—""He is rich rather than happy.""",[],[Ditior quam felicior est.]
665,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_15.4.1,short_answer,translation,unknown,english,both,"Put into Latin, using adjectives—""I came gladly.""",[],[*Libens veni*.]
666,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_15.4.2,short_answer,translation,unknown,english,both,"Put into Latin, using adjectives—""I came unwil...",[],[*Invitus veni*.]
...,...,...,...,...,...,...,...,...,...,...,...
3647,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.8.2,short_answer,translation,unknown,english,latin,"Put into Latin—""At the end of the third book.""",[],[Extremo tertio libro.]
3648,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.8.3,short_answer,translation,unknown,english,latin,"Put into Latin—""Every tenth man.""",[],[Decimus quisque.]
3649,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.8.4,short_answer,translation,unknown,english,latin,"Put into Latin—""Some think one thing, some ano...",[],[Alii alia putant.]
3708,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.4.1,short_answer,translation,unknown,english,english,Translate and explain—Cedant arma togae.,[],"[""Let war yield to peace.""]"
3709,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.4.2,short_answer,translation,unknown,english,english,"Translate and explain—Nocitura toga, nocitura ...",[],"[""Hurtful things are sought in peace and war.""]"

In [6]:
# translation >= 3 words
long_translation_df = translation_df[translation_df['answers'].apply(lambda x: len(x[0].split()) >= 3)]
long_translation_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question_text,multiple_choice_options,answers
187,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_4.10.1,short_answer,translation,unknown,english,both,"Put into Latin in two ways—""There is need (*op...",[],[Opus est mihi equo (abl.). Equus est opus mihi.]
624,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_14.7.1,short_answer,translation,unknown,english,latin,"Put into Latin—""This is my house, such as it is.""",[],"[Haec mea domus, quantulacumque est.]"
636,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_14.11.1,short_answer,translation,unknown,english,latin,"Put into Latin—""He is rich rather than happy.""",[],[Ditior quam felicior est.]
667,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_15.4.3,short_answer,translation,unknown,english,both,"Put into Latin, using adjectives—""He came with...",[],[*Me inscio venit*.]
668,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_15.4.4,short_answer,translation,unknown,english,both,"Put into Latin, using adjectives—""It is easily...",[],[*Facile factu est*.]
...,...,...,...,...,...,...,...,...,...,...,...
3645,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.7.1,short_answer,translation,unknown,english,both,Translate the following Latin phrase into Engl...,[],"[""The more a man denies [lit. 'shall have deni..."
3647,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.8.2,short_answer,translation,unknown,english,latin,"Put into Latin—""At the end of the third book.""",[],[Extremo tertio libro.]
3649,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.8.4,short_answer,translation,unknown,english,latin,"Put into Latin—""Some think one thing, some ano...",[],[Alii alia putant.]
3708,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.4.1,short_answer,translation,unknown,english,english,Translate and explain—Cedant arma togae.,[],"[""Let war yield to peace.""]"
3709,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.4.2,short_answer,translation,unknown,english,english,"Translate and explain—Nocitura toga, nocitura ...",[],"[""Hurtful things are sought in peace and war.""]"

In [8]:
answers = long_translation_df['answers'].tolist()
answers

[['Opus est mihi equo (abl.). Equus est opus mihi.'],
 ['Haec mea domus, quantulacumque est.'],
 ['Ditior quam felicior est.'],
 ['*Me inscio venit*.'],
 ['*Facile factu est*.'],
 ['"A wolf in the folds is a sad sight; and showers on ripe crops." The neut. adjective triste agrees with the general idea.'],
 ['"Death is the end of all things." Extremum stands for abstract noun.'],
 ['"He preferred honour to expediency." Honestum and utili are neut. adjectives standing for abstract nouns.'],
 ['Singulos equos habent.'],
 ['In meis nummis est.'],
 ['In multis meis nummis est.'],
 ['"I accept a loan from Titius."'],
 ['"To make a loan to Titius."'],
 ['Dic mihi quis veniat.'],
 ['Dic mihi quis venerit.'],
 ['Qui (sometimes quis) miles adest?'],
 ['Quivis or quilibet.'],
 ['Quisquam or ullus, with noun.'],
 ['Ullus or ecquis.'],
 ['Dic mihi quot oves habeas.'],
 ['Mittam quot oves habeo.'],
 ['Amat suam pecuniam.'],
 ['Ejus libros habeo.'],
 ['Suos inimicos oderunt.'],
 ['Eorum liberos amamus.'],
 ['Victis sua reddo.'],
 ['Speret se venturum.'],
 ['Speramus eum venturum.'],
 ['Feminae negant se aetate provectas esse.'],
 ['Pecunia, quam habeo, parva est.'],
 ['Pecunia, quae hic est, magna est.'],
 ['Vir, de quo loqueris, hic est.'],
 ['Equi, quos misimus, juvenes sunt.'],
 ['Doceor rebus quas enuntias.'],
 ['Meo ipsius auxilio civitas servata est.'],
 ['"And it (i.e. tree with a graft added) wonders at the new leaves and fruits not natural to itself."'],
 ['"The prayers found gods to listen to them."'],
 ['"He died at a time desirable for himself rather than for his fellow-countrymen."'],
 ['"He is master of himself in discussion."'],
 ['"His own appointed time is fixed for every man."'],
 ['"What is o\'clock?"'],
 ['"How few and far between are the wise!"'],
 ['"At what hour shall we drink?"'],
 ['"Just beneath the walls."'],
 ['"Beautiful even in decay."'],
 ['"I hate that character of yours."'],
 ['"How much changed from the old Hector!"'],
 ['Pecunia mihi deest.'],
 ['Imperat mihi ut eam.'],
 ['Hortatus est me ne irem.'],
 ['Monet me periculum esse.'],
 ['Mihi pecuniam imperat.'],
 ['Jubet me ire.'],
 ['Pecuniam a rege quaeremus.'],
 ['Deos pacem oraveram.'],
 ['[Translation into Latin]'],
 ['[Translation into Latin]'],
 ['[Translation into Latin]'],
 ['[Translation into Latin]'],
 ['Lucio a Caio parcendum est.'],
 ['Lucio a militibus parendum est.'],
 ['Trebius castris praefuit.'],
 ['Pecunia tibi proderit.'],
 ['Scimus equites mittendos fuisse.'],
 ['Negari non potest quin reditura fuerit.'],
 ['"They are well spoken of."'],
 ['"O father Matutinus, or if thou preferrest to be called Janus."'],
 ['"He had gone into exile."'],
 ['"It will be allowable to go to law."'],
 ['"Thou givest contracts for quarrying marble."'],
 ['"They undertake funerals."'],
 ['"I could not but come."'],
 ['"You may go."'],
 ['"What are you doing?" or "How are you faring?"'],
 ['"He pretends not to be afraid."'],
 ['"I have ascertained that this was done."'],
 ['"He makes no secret of his grief."'],
 ['"I will humour you."'],
 ['*Videre est credere*.'],
 ['*Hoc viso, rediit*.'],
 ['"The speech smacks of Cicero."'],
 ['"The song smells of the oil" (i.e. is laboured).'],
 ['"With his temples surrounded with bay."'],
 ['"Having put on Tyrian garb."'],
 ['"I do not wish to be hen-pecked."'],
 ['"He will turn out a great orator."'],
 ['"You will become one of my leaders."'],
 ['"I must serve you."'],
 ['"You will be pardoned."'],
 ['"Either learn or go: a third chance remains, to be flogged."'],
 ['*Scio eum venire*.'],
 ['*Sciebam eum venire*.'],
 ['*Sciebam eum venturum fuisse*.'],
 ['*Scio eum venisse*.'],
 ['*Sciebam eum vivere*.'],
 ['"When wilt thou come?"'],
 ['"He has no reason to hate me."'],
 ['"We are three in all."'],
 ['"I went because you ordered."'],
 ['"Merchants very rarely come to them."'],
 ['"It belongs to you least of all."'],
 ['“Why, do you not believe this? Not at all, for my part.”'],
 ['“The law was excessively short.”'],
 ['“He did not die till the fourth year.”'],
 ['*Utrum vales an aegrotas*?'],
 ['*Rogo utrum valeat an aegrotet*.'],
 ['*Rogavi utrum valeret an aegrotaret*.'],
 ['*Ibo, sive valebit seu (sive) aegrotabit*.'],
 ['Prius veni quam tu profectus eras.'],
 ['*Quo plus habet, eo plus capit.*'],
 ['*Nemo est quin tibi credat.*'],
 ['*Eos prohibebo quominus pecuniam reddant.*'],
 ['*Utrum veniet, an non*?'],
 ['*Dic mihi utrum venturus sit necne.*'],
 ['*Si quid habet, dat.*'],
 ['*Si quid habuisset, dedisset.*'],
 ['*Si quid habebit, datit.*'],
 ['*Oportet te ire*; *oportet ut eas*; *oportet eas*.'],
 ['For the good of the state.'],
 ["With all one's might."],
 ['From day to day.'],
 ['From the front.'],
 ['According to custom.'],
 ['According to circumstances.'],
 ['As far as I was able.'],
 ['In aere alieno est.'],
 ['In meis nummis est.'],
 ['Prae timore silet.'],
 ['De Persis triumphamus.'],
 ['Per me licet.'],
 ['Apud me erat.'],
 ['E regione Brundisii.'],
 ['Pro tua benevolentia. Quae est tua benevolentia. Qua es benevolentia. Cujus es benevolentiae.'],
 ['*Me deus Fidius,* "May the god of faith protect me!"'],
 ['*Edepol,* "May Pollux save me!" e (*me*)-de (*deus*)- Pol (*Pollux*)? or (*per*) *aedem Pollucis*?'],
 ['*Mehercle,* "May Hercules save me!"'],
 ['"Go and be hanged!"'],
 ['"Go and be food for crows!"'],
 ['"Alas for our scars!"'],
 ['"See him!" (= *en illum*).'],
 ['"See him!" (= *ecce illum*).'],
 ['"See him!" (= *ecce eum*).'],
 ['"If you please!" (= *si audies*).'],
 ['"If you please!" (= *si vultus*).'],
 ['"May the gods grant us better things!"'],
 ['"I implore thee by the gods."'],
 ['"Verily he would have left his country without hesitation."'],
 ['“To think that I should suffer such things.”'],
 ['“Manlius is said to have spoken.”'],
 ['"He felt that he had fallen into the midst of the foe."'],
 ['"Beware of going."'],
 ['"I will forbid him to be under the same roof with me."'],
 ['"You ought to have come."'],
 ['*Curat naves aedificandas*.'],
 ['*Servum prehensum interfecit*.'],
 ['*Victoria hosti multis militibus stetit*.'],
 ['*Castra obsideri coepta sunt*.'],
 ['*Vereor ne maneat*.'],
 ['*Oppugnari desitus sum*.'],
 ['Meus amor tui.'],
 ['Tuus amor mei.'],
 ['Vester amor nostri.'],
 ['"He has come to such a degree of wisdom that he knows everything."'],
 ['"It is in my power."'],
 ['"Monarchy was designed to preserve liberty."'],
 ['"Such is his clemency."'],
 ['"He preserves his natural strength."'],
 ['"It is the part of a good citizen to obey the laws."'],
 ['"A horse like a mountain."'],
 ['"Nowhere in the world."'],
 ['"Well known for his fatherly disposition towards his brothers."'],
 ['"Thou also shalt become one of famous fountains."'],
 ['_Vox clarior quàm Stentor_ or _quàm Stentoris_.'],
 ['"As far as he is able."'],
 ['"He takes it in good part."'],
 ['"It is valued at three unciæ."'],
 ['"I hold the matter of no account" (lit. "at a piece of wool").'],
 ['_A Caesare Crasso parcendum._'],
 ['_Mortem sibi conscivit._'],
 ['_Se Caesari ad pedes projecit._'],
 ['_Filiam patri eripuit._'],
 ['_Mihi mortem minatur._'],
 ['See 53 (5).'],
 ['"There you have the man who wanted to be king," etc.'],
 ['"But, look you, suddenly," etc.'],
 ['"This, you see, was their style of warfare."'],
 ['"A speech more eloquent than one of Cicero\'s."'],
 ['"They returned without effecting anything."'],
 ['"Hardly any came."'],
 ['"He takes this very deeply to heart."'],
 ['"They had observed it."'],
 ['"He had committed suicide."'],
 ['"The war came to an end ten years after it broke out."'],
 ['[Translate into Latin]'],
 ['[Translate into Latin]'],
 ['[Translate into Latin]'],
 ['[Translate into Latin]'],
 ['[Translate into Latin]'],
 ['Euphemistically, to avoid the ill omen in damnus, which suggests damnum, hurt.'],
 ['Euphemistically, to avoid the ill omen in damnus, which suggests damnum, hurt.'],
 ['Euphemistically, to avoid the ill omen in damnus, which suggests damnum, hurt.'],
 ['Euphemistically, to avoid the ill omen in damnus, which suggests damnum, hurt.'],
 ['Bellum Romanis multo sanguine stetit.'],
 ['Doctus, idem imperator.'],
 ['Mihi mortem minatur.'],
 ['Promisit se venturum esse.'],
 ['Dixit se venturum fuisse, si jussisses.'],
 ['Sperabant eum venturum.'],
 ['Num nescis qualis fuerit?'],
 ['*Inter se oderunt*.'],
 ['*Alii alia dicunt*.'],
 ['*Alter alterum oderat*.'],
 ['Ne joco quidem.'],
 ['Colenda est pietas.'],
 ['Patris imperiis parendum est.'],
 ['Paucis rebus opus est.'],
 ['Multa mentitus est.'],
 ['Marcus Quinto. S.P.D. S.V.B.E.E.V. Scribebam ut discerem quid tu agas, me absente. Fac rescribas quam primum. Data (dabam) A.D. XIV. Kal. Feb., Baiis.'],
 ['Illas aquas, quas viderent (flumen enim haud longè aberat), et se et hostes patria intercludere.'],
 ['Locus natus ad insidias.'],
 ['Ancipiti marte pugnatum est.'],
 ['Juxta bonos et malos interfecit.'],
 ['Non possum non ire.'],
 ['"A truce was agreed upon."'],
 ['"They make a treaty."'],
 ['"Six miles from the city."'],
 ['"According to circumstances."'],
 ['"He is rather (too) passionate."'],
 ['Macte virtute esto, mi fili!'],
 ['"I have sworn to thee by this holy and chaste love."'],
 ['"Desirous of revolution."'],
 ['"A public thanksgiving for several days was announced."'],
 ['"You will be called father of your country."'],
 ['"He had served in thirty campaigns."'],
 ['"They had asked for and obtained peace."'],
 ['"They leave nothing undone to hinder our escaping."'],
 ['*Si quid habeo, do.*'],
 ['*Si quid habuissem, dedissem.*'],
 ['*Si quid habeam, dem* or *haberem, darem.*'],
 ['*Si quid habebo, dabo.*'],
 ['*Dixit se, si quid haberet, daturum esse.*'],
 ['*Dixit se, si quid habuisset, daturum fuisse.*'],
 ['Ibo, sive ibit seu non.'],
 ['Quis scit utrum eab necne?'],
 ['Eum rogavi utrum ivisset necne.'],
 ['Quae cum ita sint.'],
 ['Quae cum ita essent.'],
 ['Nemo praeter te; Nemo, nisi tu; Nemo te excepto venit.'],
 ['"He who blows his nose too much, draws blood."'],
 ['"He was unwilling, though he had the power, to destroy me."'],
 ['"He made a present of."'],
 ['"I returned without losing my honour."'],
 ['"With the help of Phœbus, Troy rises again."'],
 ['Pro illo veni.'],
 ['Se recepit, quum urbem oppugnare potuisset.'],
 ['Tantum illi abest ut me oderit ut amet.'],
 ['Majus erat opus quàm quoa susciperet.'],
 ['Hoc est idem quod illud.'],
 ['"I almost think he is wise."'],
 ['"As far as I know."'],
 ['"He is not the man to do this."'],
 ['"He caught and killed his foe."'],
 ['"He sent the most faithful slave he had."'],
 ['(1) Credunt urbem captum iri or fore ut urbs capiatur.'],
 ['(2) Credebant urbem captum iri or fore ut urbs caperetur.'],
 ['"Credidit me sanum esse."'],
 ['"Credit me sanum fuisse."'],
 ['"Negavit me sanum esse."'],
 ['"Promisit se rediturum."'],
 ['"I go into exile."'],
 ['"I make an erasion (turn the pen)."'],
 ['"I am being changed into a bird."'],
 ['"I have been changed into a beast."'],
 ['"I am bankrupt."'],
 ['"I have ready money."'],
 ['"I am in debt."'],
 ['"Fabius has an audience of the senate."'],
 ['"I arrived in two days\' march."'],
 ['"He will throw a bridge across the river."'],
 ['"It is uncertain whether it was done rightly or wrongly."'],
 ['"He died yesterday."'],
 ['"The thing is exceedingly new."'],
 ['"What did our ancestors mean?"'],
 ['"Blind of an eye."'],
 ['"I will lend money."'],
 ['"I will borrow money."'],
 ['"It agrees not only not with reason, but not even with common sense."'],
 ['In meo templo et Dianae.'],
 ['"I fear he will not come."'],
 ['"I was afraid you would come."'],
 ['"Take care you do not waste time."'],
 ['"There was a battle the day after."'],
 ['"We returned the day after the battle."'],
 ['"To remain in allegiance."'],
 ['"Suppose the chariot is granted, what will you do?" or "how will you fare?"'],
 ['Yes, "quid ages?" can be rendered as "what will you do?" or "how will you fare?"'],
 ['Quum de consilio suo eos certiores fecisset, abiit.'],
 ['De consilio certior factus, abiit.'],
 ['Longi laboris damnatus.'],
 ['Reus majestatis et rerum repetundarum.'],
 ['"Let justice be done, though heaven fall" (justitium = holidays, or cessation from public business).'],
 ['"The fates denied Tithonus the power of dying."'],
 ['"He has won a decided victory."'],
 ['"You strove with all your might."'],
 ['"He was on the point of departing."'],
 ['Extra urbem est.'],
 ['Sine pecunia est.'],
 ['Nunquam eum video quin rideam.'],
 ['Bellum finitum est, ne uno quidem vulnerato.'],
 ['Haud moratus venit.'],
 ['Locutus, neque tamen mihi persuasit.'],
 ['Non auditus condemnatus est.'],
 ['Nemo discere potest, nisi litteris studet.'],
 ['Nemo litteris studere potest, quin discat.'],
 ['Ille primus Romanorum victoriam mari reportavit.'],
 ['Ultimus Graecorum peregrinis servio.'],
 ['Quivis or quilibet.'],
 ['Quemvis or quemlibet.'],
 ['Actum est de republica.'],
 ['Opus, quod se facturum recepit, e mea sententia fecit.'],
 ['Sexti decimo anno post Carthaginem deletam.'],
 ['"At first dawn."'],
 ['"On the motion of Caius, the bill was proposed."'],
 ['"At the urgent appeal of Cicero, the bill was carried."'],
 ['"He has deserved well of his party."'],
 ['"It were better to die than to suffer this."'],
 ['"It was worth my while to serve on the campaign."'],
 ['"I cannot help sending you a letter."'],
 ['"Take me back if you find me straying; you shall not go unrewarded. You shall see my mistress; ask nothing more!"'],
 ['Exercitui praefectus, rediit.'],
 ['Hostibus victis, rediit.'],
 ['Quum hostis pepercisset, rediit.'],
 ['Milites hortatus, rediit.'],
 ['Quum militibus praecepisset, rediit.'],
 ['Caio victo, redivimus.'],
 ['"How much changed from the old (the great) Hector!"'],
 ['"He was on the point of setting out."'],
 ['"As far as I was able."'],
 ['"What good was it to struggle?"'],
 ['"Suppose some one sees this, how will you fare?" (or "what will you do?").'],
 ['"On the first opportunity."'],
 ['"An occasion offered."'],
 ['"Equally careless of fame and notoriety."'],
 ['"A letter of the same tenor."'],
 ['"We have sufficiently provided for the country."'],
 ['"He rages, and pretends that he is not raging."'],
 ['Quum Hannibal profectus est, ver appetebat.'],
 ['Quum ver appeteret, H. profectus est.'],
 ['*Mihi obviam ivit*.'],
 ['*Legionibus Caius praefuit*.'],
 ['*Caesari ad pedes se projecit*.'],
 ['*Jam dudum pacem cupio*.'],
 ['Sub radicibus montis acrius quam diutius pugnatum est.'],
 ['In eo erat, ut proficiserer.'],
 ['Veritus est ne indignus esset qui mitteretur.'],
 ['Bella semel inita finienda sunt.'],
 ['Ne unus quidem hostis effugisset.'],
 ['Post me consulem.'],
 ['Ante te praetorem.'],
 ['(Context needed to answer correctly)'],
 ['Post reges exactos.'],
 ['"Respected the oaths and vow of the suppliant."'],
 ['"Will thirst for honours."'],
 ['"The poor hungry Greek, if you bid him, will go up to heaven."'],
 ['*Nisi venissem, luderent*.'],
 ['*Si oppidum capiet, captis parcet*.'],
 ['*Dixit se, si oppidum cepisset, captos interfecturum fuisse*.'],
 ['*Eum rogarunt utrum, si oppidum cepisset, captos interfecturus fuisset, necne*.'],
 ['*Promittit se venturum*.'],
 ['*Sperat se posse venire*.'],
 ['"The more a man denies [lit. \'shall have denied\'] himself, the more will he receive from heaven."'],
 ['Extremo tertio libro.'],
 ['Alii alia putant.'],
 ['"Let war yield to peace."'],
 ['"Hurtful things are sought in peace and war."']]

In [9]:
# dump to tsv
with open('../data/structured/junior_translation_long_unfiltered.tsv', 'w') as f:
    long_translation_df.to_csv(f, sep='\t')

In [5]:
# load edited long translation questions 
with open('../data/structured/junior_scholarship_translation_edits.tsv', 'r') as f:
    edited_df = pd.read_csv(f, sep='\t')

edited_df.drop(columns=['Unnamed: 0'], inplace=True)
edited_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question_text,multiple_choice_options,answers,answerable,edits
0,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_4.10.1,short_answer,translation,unknown,english,both,"Put into Latin—""There is need (*opus*) to me o...",[],"['Opus est mihi equo.', 'Equus est opus mihi.']",NaN,1.0
1,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_14.7.1,short_answer,translation,unknown,english,latin,"Put into Latin—""This is my house, such as it is.""",[],"['Haec mea domus, quantulacumque est.']",NaN,NaN
2,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_14.11.1,short_answer,translation,unknown,english,latin,"Put into Latin—""He is rich rather than happy.""",[],['Ditior quam felicior est.'],NaN,NaN
3,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_15.4.3,short_answer,translation,unknown,english,latin,"Put into Latin, using adjectives—""He came with...",[],['*Me inscio venit*.'],NaN,NaN
4,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_15.4.4,short_answer,translation,unknown,english,latin,"Put into Latin, using adjectives—""It is easily...",[],['*Facile factu est*.'],NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.7.1,short_answer,translation,unknown,english,english,Translate the following Latin phrase into Engl...,[],"[""The more a man denies himself, the more will...",NaN,1.0
371,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.8.2,short_answer,translation,unknown,english,latin,"Put into Latin—""At the end of the third book.""",[],['Extremo tertio libro.'],NaN,NaN
372,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.8.4,short_answer,translation,unknown,english,latin,"Put into Latin—""Some think one thing, some ano...",[],['Alii alia putant.'],NaN,NaN
373,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.4.1,short_answer,translation,unknown,english,english,Translate and explain—Cedant arma togae.,[],"['""Let war yield to peace.""']",NaN,NaN
374,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.4.2,short_answer,translation,unknown,english,english,"Translate and explain—Nocitura toga, nocitura ...",[],"['""Hurtful things are sought in peace and war.""']",NaN,NaN

In [8]:
# drop rows where answerable = 0 (keep nan or 1)
edited_df = edited_df[edited_df['answerable'] != 0]
edited_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question_text,multiple_choice_options,answers,answerable,edits
0,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_4.10.1,short_answer,translation,unknown,english,both,"Put into Latin—""There is need (*opus*) to me o...",[],"['Opus est mihi equo.', 'Equus est opus mihi.']",NaN,1.0
1,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_14.7.1,short_answer,translation,unknown,english,latin,"Put into Latin—""This is my house, such as it is.""",[],"['Haec mea domus, quantulacumque est.']",NaN,NaN
2,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_14.11.1,short_answer,translation,unknown,english,latin,"Put into Latin—""He is rich rather than happy.""",[],['Ditior quam felicior est.'],NaN,NaN
3,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_15.4.3,short_answer,translation,unknown,english,latin,"Put into Latin, using adjectives—""He came with...",[],['*Me inscio venit*.'],NaN,NaN
4,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_15.4.4,short_answer,translation,unknown,english,latin,"Put into Latin, using adjectives—""It is easily...",[],['*Facile factu est*.'],NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.7.1,short_answer,translation,unknown,english,english,Translate the following Latin phrase into Engl...,[],"[""The more a man denies himself, the more will...",NaN,1.0
371,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.8.2,short_answer,translation,unknown,english,latin,"Put into Latin—""At the end of the third book.""",[],['Extremo tertio libro.'],NaN,NaN
372,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_114.8.4,short_answer,translation,unknown,english,latin,"Put into Latin—""Some think one thing, some ano...",[],['Alii alia putant.'],NaN,NaN
373,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.4.1,short_answer,translation,unknown,english,english,Translate and explain—Cedant arma togae.,[],"['""Let war yield to peace.""']",NaN,NaN
374,latin-grammar-junior-scholarship,1884,latin-grammar-junior-scholarship_app.V.4.2,short_answer,translation,unknown,english,english,"Translate and explain—Nocitura toga, nocitura ...",[],"['""Hurtful things are sought in peace and war.""']",NaN,NaN

In [9]:
# drop the "answerable" and "edits" columns
edited_df = edited_df.drop(columns=['answerable', 'edits'])
edited_dict = edited_df.to_dict(orient='records')
edited_dict

[{'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_4.10.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'both',
  'question_text': 'Put into Latin—"There is need (*opus*) to me of a horse."',
  'multiple_choice_options': '[]',
  'answers': "['Opus est mihi equo.', 'Equus est opus mihi.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_14.7.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"This is my house, such as it is."',
  'multiple_choice_options': '[]',
  'answers': "['Haec mea domus, quantulacumque est.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_14.11.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"He is rich rather than happy."',
  'multiple_choice_options': '[]',
  'answers': "['Ditior quam felicior est.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_15.4.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin, using adjectives—"He came without my knowledge."',
  'multiple_choice_options': '[]',
  'answers': "['*Me inscio venit*.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_15.4.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin, using adjectives—"It is easily done."',
  'multiple_choice_options': '[]',
  'answers': "['*Facile factu est*.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_16.4.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Triste lupus stabulis, maturis frugibus imbres.*',
  'multiple_choice_options': '[]',
  'answers': '["A wolf in the folds is a sad sight; and showers on ripe crops."]'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_16.4.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Mors omnium rerum extremum est.*',
  'multiple_choice_options': '[]',
  'answers': '["Death is the end of all things."]'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_16.4.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Honestum praetulit utili.*',
  'multiple_choice_options': '[]',
  'answers': '["He preferred honour to expediency."]'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_17.10.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"They have one horse each."',
  'multiple_choice_options': '[]',
  'answers': "['Singulos equos habent.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_20.8.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"He is in my debt."',
  'multiple_choice_options': '[]',
  'answers': "['In meis nummis est.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_20.8.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"He has much ready money."',
  'multiple_choice_options': '[]',
  'answers': "['In multis meis nummis est.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_20.10.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Acceptum Titio ferre*.',
  'multiple_choice_options': '[]',
  'answers': '[\'"I accept a loan from Titius."\']'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_20.10.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Expensum Titio ferre*.',
  'multiple_choice_options': '[]',
  'answers': '[\'"To make a loan to Titius."\']'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.7.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "Tell me who comes."',
  'multiple_choice_options': '[]',
  'answers': "['Dic mihi quis veniat.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.7.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "Tell me who came."',
  'multiple_choice_options': '[]',
  'answers': "['Dic mihi quis venerit.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.7.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "What soldier is here?"',
  'multiple_choice_options': '[]',
  'answers': "['Qui miles adest?', 'Quis miles adest?']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.11.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"Tell me how many sheep you have;" using quot.',
  'multiple_choice_options': '[]',
  'answers': "['Dic mihi quot oves habeas.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.11.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"I will send all the sheep I have;" using quot.',
  'multiple_choice_options': '[]',
  'answers': "['Mittam quot oves habeo.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "He loves his money."',
  'multiple_choice_options': '[]',
  'answers': "['Amat suam pecuniam.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "I have his books."',
  'multiple_choice_options': '[]',
  'answers': "['Ejus libros habeo.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "They hate their enemies."',
  'multiple_choice_options': '[]',
  'answers': "['Suos inimicos oderunt.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "We love their children."',
  'multiple_choice_options': '[]',
  'answers': "['Eorum liberos amamus.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.5',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "I give back their (property) to the conquered."',
  'multiple_choice_options': '[]',
  'answers': "['Victis sua reddo.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.6',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "He hopes to come."',
  'multiple_choice_options': '[]',
  'answers': "['Speret se venturum.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.7',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "We hope he will come."',
  'multiple_choice_options': '[]',
  'answers': "['Speramus eum venturum.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.8',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "Women deny that they are old."',
  'multiple_choice_options': '[]',
  'answers': "['Feminae negant se aetate provectas esse.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The money, which I have, is small."',
  'multiple_choice_options': '[]',
  'answers': "['Pecunia, quam habeo, parva est.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The money, which is here, is great."',
  'multiple_choice_options': '[]',
  'answers': "['Pecunia, quae hic est, magna est.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The man you speak of is here."',
  'multiple_choice_options': '[]',
  'answers': "['Vir, de quo loqueris, hic est.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The horses we sent are young."',
  'multiple_choice_options': '[]',
  'answers': "['Equi, quos misimus, juvenes sunt.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.5',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"I am being taught by what you say."',
  'multiple_choice_options': '[]',
  'answers': "['Doceor rebus quas enuntias.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.8.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The state was saved by my very (*ipse*) own aid."',
  'multiple_choice_options': '[]',
  'answers': "['Meo ipsius auxilio civitas servata est.']"},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Miraturque novas frondes et non sua poma*.',
  'multiple_choice_options': '[]',
  'answers': '[\'"And it wonders at the new leaves and fruits not natural to itself."\']'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Vota suos habuere deos*.',
  'multiple_choice_options': '[]',
  'answers': '[\'"The prayers found gods to listen to them."\']'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Cessit e vita suo magis suam suorum civium tempore*.',
  'multiple_choice_options': '[]',
  'answers': '[\'"He died at a time desirable for himself rather than for his fellow-countrymen."\']'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*In disputando suus est*.',
  'multiple_choice_options': '[]',
  'answers': '[\'"He is master of himself in discussion."\']'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.5',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Stat sua cuique dies*.',
  'multiple_choice_options': '[]',
  'answers': '[\'"His own appointed time is fixed for every man."\']'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.4.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Quota hora est*?',
  'multiple_choice_options': '[]',
  'answers': '["What is o\\\'clock?", "What is the hour?", "What is the time?", "What time is it?"]'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.4.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Quotus quisque sapiens est*?',
  'multiple_choice_options': '[]',
  'answers': '[\'"How few and far between are the wise!"\']'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.4.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Quotā bibemus*?',
  'multiple_choice_options': '[]',
  'answers': '[\'"At what hour shall we drink?"\']'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.6.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Sub ipsis moenibus*.',
  'multiple_choice_options': '[]',
  'answers': '[\'"Just beneath the walls."\']'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.6.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *In ipsis clara ruinis*.',
  'multiple_choice_options': '[]',
  'answers': '[\'"Beautiful even in decay."\']'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.6.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Odi istos mores*.',
  'multiple_choice_options': '[]',
  'answers': '[\'"I hate that character of yours."\']'},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.6.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',

In [10]:
# make sure "answers" and "multiple_choice_options" are lists
for i, dict_ in enumerate(edited_dict):
    if isinstance(dict_['answers'], str):
        edited_dict[i]['answers'] = eval(dict_['answers'])
    if isinstance(dict_['multiple_choice_options'], str):
        edited_dict[i]['multiple_choice_options'] = eval(dict_['multiple_choice_options'])
edited_dict

[{'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_4.10.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'both',
  'question_text': 'Put into Latin—"There is need (*opus*) to me of a horse."',
  'multiple_choice_options': [],
  'answers': ['Opus est mihi equo.', 'Equus est opus mihi.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_14.7.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"This is my house, such as it is."',
  'multiple_choice_options': [],
  'answers': ['Haec mea domus, quantulacumque est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_14.11.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"He is rich rather than happy."',
  'multiple_choice_options': [],
  'answers': ['Ditior quam felicior est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_15.4.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin, using adjectives—"He came without my knowledge."',
  'multiple_choice_options': [],
  'answers': ['*Me inscio venit*.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_15.4.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin, using adjectives—"It is easily done."',
  'multiple_choice_options': [],
  'answers': ['*Facile factu est*.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_16.4.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Triste lupus stabulis, maturis frugibus imbres.*',
  'multiple_choice_options': [],
  'answers': ['A wolf in the folds is a sad sight; and showers on ripe crops.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_16.4.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Mors omnium rerum extremum est.*',
  'multiple_choice_options': [],
  'answers': ['Death is the end of all things.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_16.4.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Honestum praetulit utili.*',
  'multiple_choice_options': [],
  'answers': ['He preferred honour to expediency.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_17.10.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"They have one horse each."',
  'multiple_choice_options': [],
  'answers': ['Singulos equos habent.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_20.8.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"He is in my debt."',
  'multiple_choice_options': [],
  'answers': ['In meis nummis est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_20.8.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"He has much ready money."',
  'multiple_choice_options': [],
  'answers': ['In multis meis nummis est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_20.10.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Acceptum Titio ferre*.',
  'multiple_choice_options': [],
  'answers': ['"I accept a loan from Titius."']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_20.10.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Expensum Titio ferre*.',
  'multiple_choice_options': [],
  'answers': ['"To make a loan to Titius."']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.7.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "Tell me who comes."',
  'multiple_choice_options': [],
  'answers': ['Dic mihi quis veniat.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.7.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "Tell me who came."',
  'multiple_choice_options': [],
  'answers': ['Dic mihi quis venerit.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.7.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "What soldier is here?"',
  'multiple_choice_options': [],
  'answers': ['Qui miles adest?', 'Quis miles adest?']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.11.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"Tell me how many sheep you have;" using quot.',
  'multiple_choice_options': [],
  'answers': ['Dic mihi quot oves habeas.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.11.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"I will send all the sheep I have;" using quot.',
  'multiple_choice_options': [],
  'answers': ['Mittam quot oves habeo.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "He loves his money."',
  'multiple_choice_options': [],
  'answers': ['Amat suam pecuniam.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "I have his books."',
  'multiple_choice_options': [],
  'answers': ['Ejus libros habeo.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "They hate their enemies."',
  'multiple_choice_options': [],
  'answers': ['Suos inimicos oderunt.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "We love their children."',
  'multiple_choice_options': [],
  'answers': ['Eorum liberos amamus.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.5',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "I give back their (property) to the conquered."',
  'multiple_choice_options': [],
  'answers': ['Victis sua reddo.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.6',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "He hopes to come."',
  'multiple_choice_options': [],
  'answers': ['Speret se venturum.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.7',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "We hope he will come."',
  'multiple_choice_options': [],
  'answers': ['Speramus eum venturum.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.8',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "Women deny that they are old."',
  'multiple_choice_options': [],
  'answers': ['Feminae negant se aetate provectas esse.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The money, which I have, is small."',
  'multiple_choice_options': [],
  'answers': ['Pecunia, quam habeo, parva est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The money, which is here, is great."',
  'multiple_choice_options': [],
  'answers': ['Pecunia, quae hic est, magna est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The man you speak of is here."',
  'multiple_choice_options': [],
  'answers': ['Vir, de quo loqueris, hic est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The horses we sent are young."',
  'multiple_choice_options': [],
  'answers': ['Equi, quos misimus, juvenes sunt.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.5',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"I am being taught by what you say."',
  'multiple_choice_options': [],
  'answers': ['Doceor rebus quas enuntias.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.8.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The state was saved by my very (*ipse*) own aid."',
  'multiple_choice_options': [],
  'answers': ['Meo ipsius auxilio civitas servata est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Miraturque novas frondes et non sua poma*.',
  'multiple_choice_options': [],
  'answers': ['"And it wonders at the new leaves and fruits not natural to itself."']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Vota suos habuere deos*.',
  'multiple_choice_options': [],
  'answers': ['"The prayers found gods to listen to them."']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Cessit e vita suo magis suam suorum civium tempore*.',
  'multiple_choice_options': [],
  'answers': ['"He died at a time desirable for himself rather than for his fellow-countrymen."']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*In disputando suus est*.',
  'multiple_choice_options': [],
  'answers': ['"He is master of himself in discussion."']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.5',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Stat sua cuique dies*.',
  'multiple_choice_options': [],
  'answers': ['"His own appointed time is fixed for every man."']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.4.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Quota hora est*?',
  'multiple_choice_options': [],
  'answers': ["What is o'clock?",
   'What is the hour?',
   'What is the time?',
   'What time is it?']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.4.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Quotus quisque sapiens est*?',
  'multiple_choice_options': [],
  'answers': ['"How few and far between are the wise!"']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.4.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Quotā bibemus*?',
  'multiple_choice_options': [],
  'answers': ['"At what hour shall we drink?"']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.6.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Sub ipsis moenibus*.',
  'multiple_choice_options': [],
  'answers': ['"Just beneath the walls."']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.6.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *In ipsis clara ruinis*.',
  'multiple_choice_options': [],
  'answers': ['"Beautiful even in decay."']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.6.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Odi istos mores*.',
  'multiple_choice_options': [],
  'answers': ['"I hate that character of yours."']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.6.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Quantum mutatus ab illo Hectore*.',
  'multiple_choice_options': [],

In [11]:
# do some cleanup of answer strings 
for i, dict_ in enumerate(edited_dict):
    answers = dict_['answers']
    for j, answer in enumerate(answers):
        answers[j] = answer.strip()
        answers[j] = answers[j].replace('*', '')

        # if " in the answer twice (start and end), remove both;
        # but otherwise leave them - might be a quote 
        if answer.count('"') == 2 and answer[0] == '"' and answer[-1] == '"':
            answers[j] = answer[1:-1]

    dict_['answers'] = answers

edited_dict

[{'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_4.10.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'both',
  'question_text': 'Put into Latin—"There is need (*opus*) to me of a horse."',
  'multiple_choice_options': [],
  'answers': ['Opus est mihi equo.', 'Equus est opus mihi.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_14.7.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"This is my house, such as it is."',
  'multiple_choice_options': [],
  'answers': ['Haec mea domus, quantulacumque est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_14.11.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"He is rich rather than happy."',
  'multiple_choice_options': [],
  'answers': ['Ditior quam felicior est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_15.4.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin, using adjectives—"He came without my knowledge."',
  'multiple_choice_options': [],
  'answers': ['Me inscio venit.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_15.4.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin, using adjectives—"It is easily done."',
  'multiple_choice_options': [],
  'answers': ['Facile factu est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_16.4.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Triste lupus stabulis, maturis frugibus imbres.*',
  'multiple_choice_options': [],
  'answers': ['A wolf in the folds is a sad sight; and showers on ripe crops.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_16.4.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Mors omnium rerum extremum est.*',
  'multiple_choice_options': [],
  'answers': ['Death is the end of all things.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_16.4.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Honestum praetulit utili.*',
  'multiple_choice_options': [],
  'answers': ['He preferred honour to expediency.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_17.10.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"They have one horse each."',
  'multiple_choice_options': [],
  'answers': ['Singulos equos habent.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_20.8.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"He is in my debt."',
  'multiple_choice_options': [],
  'answers': ['In meis nummis est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_20.8.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"He has much ready money."',
  'multiple_choice_options': [],
  'answers': ['In multis meis nummis est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_20.10.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Acceptum Titio ferre*.',
  'multiple_choice_options': [],
  'answers': ['I accept a loan from Titius.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_20.10.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Expensum Titio ferre*.',
  'multiple_choice_options': [],
  'answers': ['To make a loan to Titius.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.7.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "Tell me who comes."',
  'multiple_choice_options': [],
  'answers': ['Dic mihi quis veniat.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.7.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "Tell me who came."',
  'multiple_choice_options': [],
  'answers': ['Dic mihi quis venerit.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.7.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Give the Latin for "What soldier is here?"',
  'multiple_choice_options': [],
  'answers': ['Qui miles adest?', 'Quis miles adest?']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.11.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"Tell me how many sheep you have;" using quot.',
  'multiple_choice_options': [],
  'answers': ['Dic mihi quot oves habeas.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_21.11.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"I will send all the sheep I have;" using quot.',
  'multiple_choice_options': [],
  'answers': ['Mittam quot oves habeo.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "He loves his money."',
  'multiple_choice_options': [],
  'answers': ['Amat suam pecuniam.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "I have his books."',
  'multiple_choice_options': [],
  'answers': ['Ejus libros habeo.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "They hate their enemies."',
  'multiple_choice_options': [],
  'answers': ['Suos inimicos oderunt.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "We love their children."',
  'multiple_choice_options': [],
  'answers': ['Eorum liberos amamus.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.5',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "I give back their (property) to the conquered."',
  'multiple_choice_options': [],
  'answers': ['Victis sua reddo.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.6',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "He hopes to come."',
  'multiple_choice_options': [],
  'answers': ['Speret se venturum.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.7',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "We hope he will come."',
  'multiple_choice_options': [],
  'answers': ['Speramus eum venturum.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.3.8',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin: "Women deny that they are old."',
  'multiple_choice_options': [],
  'answers': ['Feminae negant se aetate provectas esse.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The money, which I have, is small."',
  'multiple_choice_options': [],
  'answers': ['Pecunia, quam habeo, parva est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The money, which is here, is great."',
  'multiple_choice_options': [],
  'answers': ['Pecunia, quae hic est, magna est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The man you speak of is here."',
  'multiple_choice_options': [],
  'answers': ['Vir, de quo loqueris, hic est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The horses we sent are young."',
  'multiple_choice_options': [],
  'answers': ['Equi, quos misimus, juvenes sunt.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.5.5',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"I am being taught by what you say."',
  'multiple_choice_options': [],
  'answers': ['Doceor rebus quas enuntias.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.8.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'latin',
  'question_text': 'Put into Latin—"The state was saved by my very (*ipse*) own aid."',
  'multiple_choice_options': [],
  'answers': ['Meo ipsius auxilio civitas servata est.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Miraturque novas frondes et non sua poma*.',
  'multiple_choice_options': [],
  'answers': ['And it wonders at the new leaves and fruits not natural to itself.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Vota suos habuere deos*.',
  'multiple_choice_options': [],
  'answers': ['The prayers found gods to listen to them.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Cessit e vita suo magis suam suorum civium tempore*.',
  'multiple_choice_options': [],
  'answers': ['He died at a time desirable for himself rather than for his fellow-countrymen.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*In disputando suus est*.',
  'multiple_choice_options': [],
  'answers': ['He is master of himself in discussion.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_22.9.5',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate—*Stat sua cuique dies*.',
  'multiple_choice_options': [],
  'answers': ['His own appointed time is fixed for every man.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.4.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Quota hora est*?',
  'multiple_choice_options': [],
  'answers': ["What is o'clock?",
   'What is the hour?',
   'What is the time?',
   'What time is it?']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.4.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Quotus quisque sapiens est*?',
  'multiple_choice_options': [],
  'answers': ['How few and far between are the wise!']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.4.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Quotā bibemus*?',
  'multiple_choice_options': [],
  'answers': ['At what hour shall we drink?']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.6.1',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Sub ipsis moenibus*.',
  'multiple_choice_options': [],
  'answers': ['Just beneath the walls.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.6.2',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *In ipsis clara ruinis*.',
  'multiple_choice_options': [],
  'answers': ['Beautiful even in decay.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.6.3',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Odi istos mores*.',
  'multiple_choice_options': [],
  'answers': ['I hate that character of yours.']},
 {'source_name': 'latin-grammar-junior-scholarship',
  'source_year': 1884,
  'question_id': 'latin-grammar-junior-scholarship_23.6.4',
  'question_format': 'short_answer',
  'question_content': 'translation',
  'difficulty': 'unknown',
  'question_language': 'english',
  'answer_language': 'english',
  'question_text': 'Translate *Quantum mutatus ab illo Hectore*.',
  'multiple_choice_options': [],
  'answers': ['How much changed from the old Hector!']},

In [12]:
# save to json
with open('../data/structured/junior_scholarship_translation_long.json', 'w') as f:
    json.dump(edited_dict, f, indent=4)