In [115]:
import re, os, json
from unidecode import unidecode
import pandas as pd

In [116]:
gold_str = "Frondibus, et null\u00e2 lucos agitante procell\u00e2,"

answer_str_1 = "Et procellā nullā lucos agitante frondibus."

In [117]:
data_dir = '../data/final_dataset'
long_ans_files = [
                  'prosody_caesura_scansion_english.json',
                  'prosody_caesura_scansion_latin.json',
                  ]
long_ans_files = [os.path.join(data_dir, f) for f in long_ans_files]

file_to_data = {}
for file in long_ans_files:
    base_name = os.path.basename(file)
    file_to_data[base_name] = []
    with open(file, 'r') as f:
        file_to_data[base_name] += json.load(f)

    print(base_name, len(file_to_data[base_name]))

prosody_caesura_scansion_english.json 41
prosody_caesura_scansion_latin.json 41

In [151]:
file_to_resp = {}
#model_name = 'llama3-turbo'
model_name = 'qwq'

model_resp_dir = f'../data/model_responses/{model_name}'

for file in file_to_data.keys():
    base_name = os.path.basename(file)
    file_to_resp[base_name] = {}
    with open(os.path.join(model_resp_dir, base_name), 'r') as f:
        file_to_resp[base_name] = json.load(f)
    print(base_name, len(file_to_resp[base_name]))

prosody_feet_questions_english.json 20
prosody_feet_questions_latin.json 20

In [119]:
def parse_resp(resp_text):
    '''get the answer from the full response. usually on the last line as Answer: answer'''

    lines = resp_text.split('\n')
    # usually in last line
    line = lines[-1]
    # look for "Answer: A"
    if 'Answer:' in line:
        answer =line.split('Answer:')[1].strip()
        return answer
    else:
        # try to look backwards in the lines
        for line in reversed(lines):
            if 'Answer:' in line:
                answer = line.split('Answer:')[1].strip()
                return answer
        print('error parsing')
        print(resp_text)
        return ''

def normalize_str(s):
    # no accents
    s = unidecode(s)
    
    s = s.lower().strip()
    s = re.sub(r'[^\w\s]', '', s)
    return s

def score(gold_str, answer_str):
    gold_str = normalize_str(gold_str)
    answer_str = normalize_str(answer_str)

    gold_words = gold_str.split()
    answer_words = answer_str.split()

    if len(gold_words) != len(answer_words):
        return 0
    
    print('gold:', gold_words)
    print('pred:', answer_words)
    
    # position of each word must be the same
    for i, word in enumerate(gold_words):
        if word != answer_words[i]:
            return 0
        
    
    
    return 1

In [120]:
# make dfs
question_dfs = []
for file in file_to_data.keys():
    questions = file_to_data[file]
    question_df = pd.DataFrame(questions)
    question_dfs.append(question_df)

In [121]:
for i, file in enumerate(file_to_data.keys()):
    question_df = question_dfs[i]
    answer_dict = file_to_resp[file]
    answer_col = []
    for (i, row) in question_df.iterrows():
        q_id = row['question_id']

        model_answer = answer_dict[q_id]
        answer_col.append(model_answer)

    question_df['raw_resp'] = answer_col

In [122]:
for i, file in enumerate(file_to_data.keys()):
    question_df = question_dfs[i]
    question_df['parsed_resp'] = question_df['raw_resp'].apply(parse_resp)
    question_dfs[i] = question_df
question_dfs[0]

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question_text,multiple_choice_options,answers,raw_resp,parsed_resp
0,exercises-in-latin-prosody,1823,prosody_III.I.9.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Ipse dei clypeus terrâ cùm tollitur imâ,]","<think>\n\nOkay, so I need to adjust the posit...","Ipse dei clypeus imâ terrâ cùm tollitur,"
1,exercises-in-latin-prosody,1823,prosody_III.I.9.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Manè rubet; terrâque rubet cùm conditur imâ.],"<think>\n\nOkay, so I need to adjust the given...","Manè rubet; terrâque rubet, cùm conditur imâ."
2,exercises-in-latin-prosody,1823,prosody_III.I.10.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[En, proles antiqua redit; concordia, virtus,]","<think>\n\nOkay, let's see. The user wants me ...","En, proles antiqua redit virtus, concordia;"
3,exercises-in-latin-prosody,1823,prosody_III.I.10.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Cumque fide pietas altâ cervice vagantur.],"<think>\n\nOkay, so the user wants me to adjus...",Cumque fide pietas altâ cervice vagantur.
4,exercises-in-latin-prosody,1823,prosody_III.I.11.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Robora nec cuneis, et olentem scindere cedrum,]","<think>\n\nOkay, let's see. The user wants me ...","Robora nec cuneis, olentem *et* scindere cedrum,"
5,exercises-in-latin-prosody,1823,prosody_III.I.11.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Nec plaustris cessant vectare gementibus ornos.],"<think>\n\nOkay, let's tackle this problem. Th...",Nec plaustris cessant vectare gementibus *ornos*.
6,exercises-in-latin-prosody,1823,prosody_III.I.12.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Sponte tuus florebit ager cessante juvenco;],"<think>\n\nOkay, so the user wants me to adjus...",Sponte tuus florebit ager cessante juvenco;
7,exercises-in-latin-prosody,1823,prosody_III.I.12.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Ditior oblatas mirabitur incola messes.],"<think>\n\nOkay, let's tackle this problem. Th...",Oblatas mirabitur incola ditior messes.
8,exercises-in-latin-prosody,1823,prosody_III.I.13.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Non propter vitam faciunt patrimonia quidam,]","<think>\n\nOkay, so the user wants me to take ...","Non propter vitam faciunt quidam patrimonia,"
9,exercises-in-latin-prosody,1823,prosody_III.I.13.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Sed, vitio cæci, propter patrimonia vivunt.]","<think>\nOkay, let's tackle this problem. The ...","Vitio cæci, propter patrimonia sed vivunt."
10,exercises-in-latin-prosody,1823,prosody_III.I.14.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Sol fugit, et removent subeuntia nubila cœlum,]","<think>\n\nOkay, let's see. The user wants me ...","Sol fugit, et removent cœlum subeuntia nubila,**"
11,exercises-in-latin-prosody,1823,prosody_III.I.14.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Et gravis, effusis, decidit imber, aquis.]","<think>\n\nOkay, let me tackle this problem. T...","Et effusis decidit imber gravis, aquis."
12,exercises-in-latin-prosody,1823,prosody_III.I.15.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Quòd si quis monitis tardas adverterit aures,]","<think>\n\nOkay, the user wants me to form a h...","Quòd si quis monitis tardas aures adverterit,**"
13,exercises-in-latin-prosody,1823,prosody_III.I.15.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Heu, referet quanto verba dolore mea!]","<think>\n\nOkay, let's tackle this. The user w...","Heu, referet quanto verba *mea* dolore !"
14,exercises-in-latin-prosody,1823,prosody_III.I.16.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Arte laboratæ vincuntur ab æquore puppes.],"<think>\n\nOkay, let's tackle this problem. Th...",Arte laboratæ puppes vincuntur æquore ab.
15,exercises-in-latin-prosody,1823,prosody_III.I.16.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Tu tua plùs remis brachia posse putes?],"<think>\n\nOkay, so the user wants me to adjus...",Tu tua plùs brachia remis posse putes ?
16,exercises-in-latin-prosody,1823,prosody_III.I.17.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Casta placent superis; purâ cum veste venite,]","<think>\n\nOkay, let me tackle this problem. T...","Casta placent superis; venite cum purā veste,"
17,exercises-in-latin-prosody,1823,prosody_III.I.17.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Et manibus puris sumite fontis aquam.],"<think>\n\nOkay, the user wants me to form the...",Et manibus puris sumite fontis aquam.
18,exercises-in-latin-prosody,1823,prosody_III.I.18.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Corpora sive rogus flammâ, seu tabe vetustas]","<think>\n\nOkay, let's see. The user wants me ...","Corpora sive flammâ, seu rogus tabe vetustas"
19,exercises-in-latin-prosody,1823,prosody_III.I.18.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Abstulerit, mala posse pati non ulla putetis.]","<think>\n\nOkay, so the user wants me to form ...","Abstulerit, posse non pati ulla mala putetis."
20,exercises-in-latin-prosody,1823,prosody_III.I.19.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Multa dies, variusque labor mutabilis ævi,]","<think>\n\nOkay, the user wants me to take the...","Multa dies, variusque ævi mutabilis labor,"
21,exercises-in-latin-prosody,1823,prosody_III.I.19.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Rettulit in melius; multos alterna revisens],"<think>\n\nOkay, so the user wants me to form ...","In melius rettulit, alterna revisens multos."
22,exercises-in-latin-prosody,1823,prosody_III.I.19.3,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Lusit, et in solido rursus fortuna locavit.]","<think>\n\nOkay, so the user wants me to adjus...","Lusit, et fortuna rursus locavit in solido."
23,exercises-in-latin-prosody,1823,prosody_III.I.20.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Alternis idem tonsas cessare novales,]","<think>\n\nOkay, the user wants me to take the...","Alternis cessare tonsas novales idem,"
24,exercises-in-latin-prosody,1823,prosody_III.I.20.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Et segnem patiêre situ durescere campum;],"<think>\nOkay, let's tackle this problem. The ...",Et patiêre situ durescere campum segnem ;
25,exercises-in-latin-prosody,1823,prosody_III.I.20.3,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Aut ibi flava seres, mutato sidere, farra.]","<think>\n\nOkay, let's see. The user wants me ...","Aut ibi seres flava, mutato sidere farra."
26,exercises-in-latin-prosody,1823,prosody_III.I.21.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Lucus erat longo nunquam violatus ab ævo,]","<think>\n\nOkay, so the user wants me to form ...",**
27,exercises-in-latin-prosody,1823,prosody_III.I.21.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Obscurum cingens connexis aera ramis,]","<think>\n\nOkay, the user wants me to adjust t...","aëra Obscurum cingens connexis ramis,"
28,exercises-in-latin-prosody,1823,prosody_III.I.21.3,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Et gelidas, altè summotis solibus, umbras.]","<think>\n\nOkay, let's tackle this problem. Th...","Et gelidas umbras, summotis altè solibus."
29,exercises-in-latin-prosody,1823,prosody_III.I.22.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Interea pax arva colat; pax candida primùm],"<think>\n\nOkay, let's tackle this. The user w...",Interea colat pax candida arva; pax primùm.
30,exercises-in-latin-prosody,1823,prosody_III.I.22.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Duxit araturos sub juga curva boves.],"<think>\n\nOkay, the user wants me to form the...",Duxit sub juga araturos boves curva.
31,exercises-in-latin-prosody,1823,prosody_III.I.22.3,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Pace bidens vomerque nitent; at tristia duri],"<think>\n\nOkay, the user wants me to adjust t...",Nitent pace bidens vomerque at; tristia duri.
32,exercises-in-latin-prosody,1823,prosody_III.I.22.4,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Militis in tenebris occupat arma situs.],"<think>\n\nOkay, so the user wants me to turn ...",Militis in tenebris situs occupat arma.
33,exercises-in-latin-prosody,1823,prosody_III.I.23.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Non domus et fundus, non æris acervus et auri]","<think>\n\nOkay, so I need to adjust the given...","Non domus et fundus, non acervus auri et aeris."
34,exercises-in-latin-prosody,1823,prosody_III.I.23.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Ægroto domini deduxit corpore febres,]","<think>\n\nOkay, so the user wants me to adjus...","Deduxit domini ægroto corpore febres,"
35,exercises-in-latin-prosody,1823,prosody_III.I.23.3,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Non animo curas. Valeat possessor oportet,]","<think>\n\nOkay, let's tackle this problem. Th...",Non animo curas oportet valeat possessor.
36,exercises-in-latin-prosody,1823,prosody_III.I.23.4,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Si comportatis rebus bene cogitat uti.],"<think>\n\nOkay, let's tackle this problem. Th...",Si uti comportatis bene rebus cogitat.
37,exercises-in-latin-prosody,1823,prosody_III.I.24.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[. Hic sedes augusta deæ, templique colendi]","<think>\n\nOkay, let me tackle this problem. T...","Hic sedes deæ augusta, colendi templique"
38,exercises-in-latin-prosody,1823,prosody_III.I.24.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Religiosa silex, densis quam pinus obumbrat]","<think>\n\nOkay, let me tackle this problem. T...","Silex religiosa, quam pinus densis obumbrat."
39,exercises-in-latin-prosody,1823,prosody_III.I.24.3,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Frondibus, et nullâ lucos agitante procellâ,]","<think>\n\nOkay, let's tackle this problem. Th...","Frondibus, et nullā procellā lucos agitante,"
40,exercises-in-latin-prosody,1823,prosody_III.I.24.4,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Stridula coniferi modulantur carmina rami.],"<think>\n\nOkay, so the user wants me to adjus...",Rami stridula modulantur coniferi carmina.

In [123]:
for i, file in enumerate(file_to_data.keys()):
    question_df = question_dfs[i]
    scores = []
    for (i, row) in question_df.iterrows():
        q_id = row['question_id']
        correct_answer = row['answers'][0]
        model_answer = row['parsed_resp']
        scores.append(score(correct_answer, model_answer)) 

    question_df['score'] = scores
question_dfs[0]

gold: ['ipse', 'dei', 'clypeus', 'terra', 'cum', 'tollitur', 'ima']
pred: ['ipse', 'dei', 'clypeus', 'ima', 'terra', 'cum', 'tollitur']
gold: ['mane', 'rubet', 'terraque', 'rubet', 'cum', 'conditur', 'ima']
pred: ['mane', 'rubet', 'terraque', 'rubet', 'cum', 'conditur', 'ima']
gold: ['en', 'proles', 'antiqua', 'redit', 'concordia', 'virtus']
pred: ['en', 'proles', 'antiqua', 'redit', 'virtus', 'concordia']
gold: ['cumque', 'fide', 'pietas', 'alta', 'cervice', 'vagantur']
pred: ['cumque', 'fide', 'pietas', 'alta', 'cervice', 'vagantur']
gold: ['robora', 'nec', 'cuneis', 'et', 'olentem', 'scindere', 'cedrum']
pred: ['robora', 'nec', 'cuneis', 'olentem', 'et', 'scindere', 'cedrum']
gold: ['nec', 'plaustris', 'cessant', 'vectare', 'gementibus', 'ornos']
pred: ['nec', 'plaustris', 'cessant', 'vectare', 'gementibus', 'ornos']
gold: ['sponte', 'tuus', 'florebit', 'ager', 'cessante', 'juvenco']
pred: ['sponte', 'tuus', 'florebit', 'ager', 'cessante', 'juvenco']
gold: ['ditior', 'oblatas', 'mirabitur', 'incola', 'messes']
pred: ['oblatas', 'mirabitur', 'incola', 'ditior', 'messes']
gold: ['non', 'propter', 'vitam', 'faciunt', 'patrimonia', 'quidam']
pred: ['non', 'propter', 'vitam', 'faciunt', 'quidam', 'patrimonia']
gold: ['sed', 'vitio', 'caeci', 'propter', 'patrimonia', 'vivunt']
pred: ['vitio', 'caeci', 'propter', 'patrimonia', 'sed', 'vivunt']
gold: ['sol', 'fugit', 'et', 'removent', 'subeuntia', 'nubila', 'coelum']
pred: ['sol', 'fugit', 'et', 'removent', 'coelum', 'subeuntia', 'nubila']
gold: ['et', 'gravis', 'effusis', 'decidit', 'imber', 'aquis']
pred: ['et', 'effusis', 'decidit', 'imber', 'gravis', 'aquis']
gold: ['quod', 'si', 'quis', 'monitis', 'tardas', 'adverterit', 'aures']
pred: ['quod', 'si', 'quis', 'monitis', 'tardas', 'aures', 'adverterit']
gold: ['heu', 'referet', 'quanto', 'verba', 'dolore', 'mea']
pred: ['heu', 'referet', 'quanto', 'verba', 'mea', 'dolore']
gold: ['arte', 'laboratae', 'vincuntur', 'ab', 'aequore', 'puppes']
pred: ['arte', 'laboratae', 'puppes', 'vincuntur', 'aequore', 'ab']
gold: ['tu', 'tua', 'plus', 'remis', 'brachia', 'posse', 'putes']
pred: ['tu', 'tua', 'plus', 'brachia', 'remis', 'posse', 'putes']
gold: ['casta', 'placent', 'superis', 'pura', 'cum', 'veste', 'venite']
pred: ['casta', 'placent', 'superis', 'venite', 'cum', 'pura', 'veste']
gold: ['et', 'manibus', 'puris', 'sumite', 'fontis', 'aquam']
pred: ['et', 'manibus', 'puris', 'sumite', 'fontis', 'aquam']
gold: ['corpora', 'sive', 'rogus', 'flamma', 'seu', 'tabe', 'vetustas']
pred: ['corpora', 'sive', 'flamma', 'seu', 'rogus', 'tabe', 'vetustas']
gold: ['abstulerit', 'mala', 'posse', 'pati', 'non', 'ulla', 'putetis']
pred: ['abstulerit', 'posse', 'non', 'pati', 'ulla', 'mala', 'putetis']
gold: ['multa', 'dies', 'variusque', 'labor', 'mutabilis', 'aevi']
pred: ['multa', 'dies', 'variusque', 'aevi', 'mutabilis', 'labor']
gold: ['rettulit', 'in', 'melius', 'multos', 'alterna', 'revisens']
pred: ['in', 'melius', 'rettulit', 'alterna', 'revisens', 'multos']
gold: ['lusit', 'et', 'in', 'solido', 'rursus', 'fortuna', 'locavit']
pred: ['lusit', 'et', 'fortuna', 'rursus', 'locavit', 'in', 'solido']
gold: ['alternis', 'idem', 'tonsas', 'cessare', 'novales']
pred: ['alternis', 'cessare', 'tonsas', 'novales', 'idem']
gold: ['et', 'segnem', 'patiere', 'situ', 'durescere', 'campum']
pred: ['et', 'patiere', 'situ', 'durescere', 'campum', 'segnem']
gold: ['aut', 'ibi', 'flava', 'seres', 'mutato', 'sidere', 'farra']
pred: ['aut', 'ibi', 'seres', 'flava', 'mutato', 'sidere', 'farra']
gold: ['obscurum', 'cingens', 'connexis', 'aera', 'ramis']
pred: ['aera', 'obscurum', 'cingens', 'connexis', 'ramis']
gold: ['et', 'gelidas', 'alte', 'summotis', 'solibus', 'umbras']
pred: ['et', 'gelidas', 'umbras', 'summotis', 'alte', 'solibus']
gold: ['interea', 'pax', 'arva', 'colat', 'pax', 'candida', 'primum']
pred: ['interea', 'colat', 'pax', 'candida', 'arva', 'pax', 'primum']
gold: ['duxit', 'araturos', 'sub', 'juga', 'curva', 'boves']
pred: ['duxit', 'sub', 'juga', 'araturos', 'boves', 'curva']
gold: ['pace', 'bidens', 'vomerque', 'nitent', 'at', 'tristia', 'duri']
pred: ['nitent', 'pace', 'bidens', 'vomerque', 'at', 'tristia', 'duri']
gold: ['militis', 'in', 'tenebris', 'occupat', 'arma', 'situs']
pred: ['militis', 'in', 'tenebris', 'situs', 'occupat', 'arma']
gold: ['non', 'domus', 'et', 'fundus', 'non', 'aeris', 'acervus', 'et', 'auri']
pred: ['non', 'domus', 'et', 'fundus', 'non', 'acervus', 'auri', 'et', 'aeris']
gold: ['aegroto', 'domini', 'deduxit', 'corpore', 'febres']
pred: ['deduxit', 'domini', 'aegroto', 'corpore', 'febres']
gold: ['non', 'animo', 'curas', 'valeat', 'possessor', 'oportet']
pred: ['non', 'animo', 'curas', 'oportet', 'valeat', 'possessor']
gold: ['si', 'comportatis', 'rebus', 'bene', 'cogitat', 'uti']
pred: ['si', 'uti', 'comportatis', 'bene', 'rebus', 'cogitat']
gold: ['hic', 'sedes', 'augusta', 'deae', 'templique', 'colendi']
pred: ['hic', 'sedes', 'deae', 'augusta', 'colendi', 'templique']
gold: ['religiosa', 'silex', 'densis', 'quam', 'pinus', 'obumbrat']
pred: ['silex', 'religiosa', 'quam', 'pinus', 'densis', 'obumbrat']
gold: ['frondibus', 'et', 'nulla', 'lucos', 'agitante', 'procella']
pred: ['frondibus', 'et', 'nulla', 'procella', 'lucos', 'agitante']
gold: ['stridula', 'coniferi', 'modulantur', 'carmina', 'rami']
pred: ['rami', 'stridula', 'modulantur', 'coniferi', 'carmina']
gold: ['ipse', 'dei', 'clypeus', 'terra', 'cum', 'tollitur', 'ima']
pred: ['ipse', 'dei', 'clypeus', 'ima', 'terra', 'cum', 'tollitur']
gold: ['mane', 'rubet', 'terraque', 'rubet', 'cum', 'conditur', 'ima']
pred: ['mane', 'rubet', 'terraque', 'rubet', 'cum', 'conditur', 'ima']
gold: ['en', 'proles', 'antiqua', 'redit', 'concordia', 'virtus']
pred: ['en', 'proles', 'antiqua', 'redit', 'concordia', 'virtus']
gold: ['cumque', 'fide', 'pietas', 'alta', 'cervice', 'vagantur']
pred: ['cumque', 'fide', 'pietas', 'cervice', 'sublimi', 'vagantur']
gold: ['robora', 'nec', 'cuneis', 'et', 'olentem', 'scindere', 'cedrum']
pred: ['robora', 'nec', 'cuneis', 'olentem', 'scindere', 'que', 'cedrum']
gold: ['nec', 'plaustris', 'cessant', 'vectare', 'gementibus', 'ornos']
pred: ['nec', 'plaustris', 'cessant', 'vectare', 'gementibus', 'ornos']
gold: ['sponte', 'tuus', 'florebit', 'ager', 'cessante', 'juvenco']
pred: ['sponte', 'aratro', 'tuus', 'florebit', 'ager', 'cessante']
gold: ['ditior', 'oblatas', 'mirabitur', 'incola', 'messes']
pred: ['oblatas', 'mirabitur', 'ditior', 'incola', 'messes']
gold: ['non', 'propter', 'vitam', 'faciunt', 'patrimonia', 'quidam']
pred: ['non', 'propter', 'vitam', 'faciunt', 'patrimonia', 'quidam']
gold: ['sed', 'vitio', 'caeci', 'propter', 'patrimonia', 'vivunt']
pred: ['vitio', 'caeci', 'propter', 'patrimonia', 'vivunt', 'sed']
gold: ['sol', 'fugit', 'et', 'removent', 'subeuntia', 'nubila', 'coelum']
pred: ['sol', 'fugit', 'et', 'removent', 'subeunt', 'coelum', 'nubila']
gold: ['et', 'gravis', 'effusis', 'decidit', 'imber', 'aquis']
pred: ['et', 'effusis', 'magnus', 'decidit', 'imber', 'aquis']
gold: ['quod', 'si', 'quis', 'monitis', 'tardas', 'adverterit', 'aures']
pred: ['quod', 'si', 'quis', 'monitis', 'tardas', 'aures', 'adverterit']
gold: ['heu', 'referet', 'quanto', 'verba', 'dolore', 'mea']
pred: ['heu', 'referet', 'quanto', 'verba', 'mea', 'dolore']
gold: ['arte', 'laboratae', 'vincuntur', 'ab', 'aequore', 'puppes']
pred: ['arte', 'laboratae', 'puppes', 'vincuntur', 'a', 'ponto']
gold: ['tu', 'tua', 'plus', 'remis', 'brachia', 'posse', 'putes']
pred: ['tu', 'tua', 'plus', 'remis', 'brachia', 'posse', 'putes']
gold: ['casta', 'placent', 'superis', 'pura', 'cum', 'veste', 'venite']
pred: ['casta', 'placent', 'superis', 'venite', 'cum', 'pura', 'veste']
gold: ['et', 'manibus', 'puris', 'sumite', 'fontis', 'aquam']
pred: ['et', 'manibus', 'puris', 'sumite', 'aquam', 'fonte']
gold: ['corpora', 'sive', 'rogus', 'flamma', 'seu', 'tabe', 'vetustas']
pred: ['corpora', 'sive', 'flamma', 'rogus', 'seu', 'tabe', 'vetus']
gold: ['multa', 'dies', 'variusque', 'labor', 'mutabilis', 'aevi']
pred: ['multa', 'mutabilis', 'dies', 'variusque', 'aevi', 'labor']
gold: ['rettulit', 'in', 'melius', 'multos', 'alterna', 'revisens']
pred: ['in', 'melius', 'rettulit', 'multa', 'alterna', 'revisens']
gold: ['lusit', 'et', 'in', 'solido', 'rursus', 'fortuna', 'locavit']
pred: ['lusit', 'et', 'in', 'solidum', 'fortuna', 'rursus', 'locavit']
gold: ['alternis', 'idem', 'tonsas', 'cessare', 'novales']
pred: ['alternis', 'cessare', 'idem', 'tonsas', 'novales']
gold: ['et', 'segnem', 'patiere', 'situ', 'durescere', 'campum']
pred: ['et', 'patiere', 'segnem', 'situ', 'duri', 'campum']
gold: ['aut', 'ibi', 'flava', 'seres', 'mutato', 'sidere', 'farra']
pred: ['aut', 'ibi', 'fulva', 'mutato', 'sidere', 'seres', 'farra']
gold: ['lucus', 'erat', 'longo', 'nunquam', 'violatus', 'ab', 'aevo']
pred: ['lucus', 'erat', 'violatus', 'nunquam', 'ab', 'longo', 'aevo']
gold: ['obscurum', 'cingens', 'connexis', 'aera', 'ramis']
pred: ['obscurum', 'aera', 'cingens', 'ramis', 'connexis']
gold: ['et', 'gelidas', 'alte', 'summotis', 'solibus', 'umbras']
pred: ['et', 'gelidas', 'umbras', 'alte', 'summotis', 'solis']
gold: ['interea', 'pax', 'arva', 'colat', 'pax', 'candida', 'primum']
pred: ['interea', 'colat', 'pax', 'arva', 'pax', 'candida', 'prima']
gold: ['duxit', 'araturos', 'sub', 'juga', 'curva', 'boves']
pred: ['duxit', 'sub', 'juga', 'curva', 'araturos', 'bos']
gold: ['pace', 'bidens', 'vomerque', 'nitent', 'at', 'tristia', 'duri']
pred: ['nitent', 'pace', 'bidentis', 'vomerque', 'at', 'tristia', 'duri']
gold: ['militis', 'in', 'tenebris', 'occupat', 'arma', 'situs']
pred: ['miles', 'situs', 'in', 'tenebris', 'occupat', 'arma']
gold: ['non', 'domus', 'et', 'fundus', 'non', 'aeris', 'acervus', 'et', 'auri']
pred: ['non', 'domus', 'et', 'fundus', 'non', 'aeris', 'acervus', 'et', 'auri']
gold: ['aegroto', 'domini', 'deduxit', 'corpore', 'febres']
pred: ['deduxit', 'domini', 'aegroto', 'corpore', 'febres']
gold: ['non', 'animo', 'curas', 'valeat', 'possessor', 'oportet']
pred: ['non', 'animo', 'curas', 'oportet', 'possessor', 'valeat']
gold: ['si', 'comportatis', 'rebus', 'bene', 'cogitat', 'uti']
pred: ['si', 'uti', 'compositis', 'rebus', 'bene', 'cogitat']
gold: ['hic', 'sedes', 'augusta', 'deae', 'templique', 'colendi']
pred: ['hic', 'sedes', 'augusta', 'deae', 'cultus', 'templique']
gold: ['religiosa', 'silex', 'densis', 'quam', 'pinus', 'obumbrat']
pred: ['silex', 'religiosa', 'quam', 'pinus', 'densis', 'obumbrat']
gold: ['frondibus', 'et', 'nulla', 'lucos', 'agitante', 'procella']
pred: ['frondibus', 'et', 'nulla', 'procella', 'lucos', 'agitante']
gold: ['stridula', 'coniferi', 'modulantur', 'carmina', 'rami']
pred: ['rami', 'stridula', 'coniferi', 'cantant', 'carmina']

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question_text,multiple_choice_options,answers,raw_resp,parsed_resp,score
0,exercises-in-latin-prosody,1823,prosody_III.I.9.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Ipse dei clypeus terrâ cùm tollitur imâ,]","<think>\n\nOkay, so I need to adjust the posit...","Ipse dei clypeus imâ terrâ cùm tollitur,",0
1,exercises-in-latin-prosody,1823,prosody_III.I.9.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Manè rubet; terrâque rubet cùm conditur imâ.],"<think>\n\nOkay, so I need to adjust the given...","Manè rubet; terrâque rubet, cùm conditur imâ.",1
2,exercises-in-latin-prosody,1823,prosody_III.I.10.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[En, proles antiqua redit; concordia, virtus,]","<think>\n\nOkay, let's see. The user wants me ...","En, proles antiqua redit virtus, concordia;",0
3,exercises-in-latin-prosody,1823,prosody_III.I.10.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Cumque fide pietas altâ cervice vagantur.],"<think>\n\nOkay, so the user wants me to adjus...",Cumque fide pietas altâ cervice vagantur.,1
4,exercises-in-latin-prosody,1823,prosody_III.I.11.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Robora nec cuneis, et olentem scindere cedrum,]","<think>\n\nOkay, let's see. The user wants me ...","Robora nec cuneis, olentem *et* scindere cedrum,",0
5,exercises-in-latin-prosody,1823,prosody_III.I.11.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Nec plaustris cessant vectare gementibus ornos.],"<think>\n\nOkay, let's tackle this problem. Th...",Nec plaustris cessant vectare gementibus *ornos*.,1
6,exercises-in-latin-prosody,1823,prosody_III.I.12.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Sponte tuus florebit ager cessante juvenco;],"<think>\n\nOkay, so the user wants me to adjus...",Sponte tuus florebit ager cessante juvenco;,1
7,exercises-in-latin-prosody,1823,prosody_III.I.12.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Ditior oblatas mirabitur incola messes.],"<think>\n\nOkay, let's tackle this problem. Th...",Oblatas mirabitur incola ditior messes.,0
8,exercises-in-latin-prosody,1823,prosody_III.I.13.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Non propter vitam faciunt patrimonia quidam,]","<think>\n\nOkay, so the user wants me to take ...","Non propter vitam faciunt quidam patrimonia,",0
9,exercises-in-latin-prosody,1823,prosody_III.I.13.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Sed, vitio cæci, propter patrimonia vivunt.]","<think>\nOkay, let's tackle this problem. The ...","Vitio cæci, propter patrimonia sed vivunt.",0
10,exercises-in-latin-prosody,1823,prosody_III.I.14.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Sol fugit, et removent subeuntia nubila cœlum,]","<think>\n\nOkay, let's see. The user wants me ...","Sol fugit, et removent cœlum subeuntia nubila,**",0
11,exercises-in-latin-prosody,1823,prosody_III.I.14.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Et gravis, effusis, decidit imber, aquis.]","<think>\n\nOkay, let me tackle this problem. T...","Et effusis decidit imber gravis, aquis.",0
12,exercises-in-latin-prosody,1823,prosody_III.I.15.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Quòd si quis monitis tardas adverterit aures,]","<think>\n\nOkay, the user wants me to form a h...","Quòd si quis monitis tardas aures adverterit,**",0
13,exercises-in-latin-prosody,1823,prosody_III.I.15.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Heu, referet quanto verba dolore mea!]","<think>\n\nOkay, let's tackle this. The user w...","Heu, referet quanto verba *mea* dolore !",0
14,exercises-in-latin-prosody,1823,prosody_III.I.16.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Arte laboratæ vincuntur ab æquore puppes.],"<think>\n\nOkay, let's tackle this problem. Th...",Arte laboratæ puppes vincuntur æquore ab.,0
15,exercises-in-latin-prosody,1823,prosody_III.I.16.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Tu tua plùs remis brachia posse putes?],"<think>\n\nOkay, so the user wants me to adjus...",Tu tua plùs brachia remis posse putes ?,0
16,exercises-in-latin-prosody,1823,prosody_III.I.17.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Casta placent superis; purâ cum veste venite,]","<think>\n\nOkay, let me tackle this problem. T...","Casta placent superis; venite cum purā veste,",0
17,exercises-in-latin-prosody,1823,prosody_III.I.17.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Et manibus puris sumite fontis aquam.],"<think>\n\nOkay, the user wants me to form the...",Et manibus puris sumite fontis aquam.,1
18,exercises-in-latin-prosody,1823,prosody_III.I.18.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Corpora sive rogus flammâ, seu tabe vetustas]","<think>\n\nOkay, let's see. The user wants me ...","Corpora sive flammâ, seu rogus tabe vetustas",0
19,exercises-in-latin-prosody,1823,prosody_III.I.18.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Abstulerit, mala posse pati non ulla putetis.]","<think>\n\nOkay, so the user wants me to form ...","Abstulerit, posse non pati ulla mala putetis.",0
20,exercises-in-latin-prosody,1823,prosody_III.I.19.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Multa dies, variusque labor mutabilis ævi,]","<think>\n\nOkay, the user wants me to take the...","Multa dies, variusque ævi mutabilis labor,",0
21,exercises-in-latin-prosody,1823,prosody_III.I.19.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Rettulit in melius; multos alterna revisens],"<think>\n\nOkay, so the user wants me to form ...","In melius rettulit, alterna revisens multos.",0
22,exercises-in-latin-prosody,1823,prosody_III.I.19.3,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Lusit, et in solido rursus fortuna locavit.]","<think>\n\nOkay, so the user wants me to adjus...","Lusit, et fortuna rursus locavit in solido.",0
23,exercises-in-latin-prosody,1823,prosody_III.I.20.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Alternis idem tonsas cessare novales,]","<think>\n\nOkay, the user wants me to take the...","Alternis cessare tonsas novales idem,",0
24,exercises-in-latin-prosody,1823,prosody_III.I.20.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Et segnem patiêre situ durescere campum;],"<think>\nOkay, let's tackle this problem. The ...",Et patiêre situ durescere campum segnem ;,0
25,exercises-in-latin-prosody,1823,prosody_III.I.20.3,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Aut ibi flava seres, mutato sidere, farra.]","<think>\n\nOkay, let's see. The user wants me ...","Aut ibi seres flava, mutato sidere farra.",0
26,exercises-in-latin-prosody,1823,prosody_III.I.21.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Lucus erat longo nunquam violatus ab ævo,]","<think>\n\nOkay, so the user wants me to form ...",**,0
27,exercises-in-latin-prosody,1823,prosody_III.I.21.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Obscurum cingens connexis aera ramis,]","<think>\n\nOkay, the user wants me to adjust t...","aëra Obscurum cingens connexis ramis,",0
28,exercises-in-latin-prosody,1823,prosody_III.I.21.3,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Et gelidas, altè summotis solibus, umbras.]","<think>\n\nOkay, let's tackle this problem. Th...","Et gelidas umbras, summotis altè solibus.",0
29,exercises-in-latin-prosody,1823,prosody_III.I.22.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Interea pax arva colat; pax candida primùm],"<think>\n\nOkay, let's tackle this. The user w...",Interea colat pax candida arva; pax primùm.,0
30,exercises-in-latin-prosody,1823,prosody_III.I.22.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Duxit araturos sub juga curva boves.],"<think>\n\nOkay, the user wants me to form the...",Duxit sub juga araturos boves curva.,0
31,exercises-in-latin-prosody,1823,prosody_III.I.22.3,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Pace bidens vomerque nitent; at tristia duri],"<think>\n\nOkay, the user wants me to adjust t...",Nitent pace bidens vomerque at; tristia duri.,0
32,exercises-in-latin-prosody,1823,prosody_III.I.22.4,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Militis in tenebris occupat arma situs.],"<think>\n\nOkay, so the user wants me to turn ...",Militis in tenebris situs occupat arma.,0
33,exercises-in-latin-prosody,1823,prosody_III.I.23.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Non domus et fundus, non æris acervus et auri]","<think>\n\nOkay, so I need to adjust the given...","Non domus et fundus, non acervus auri et aeris.",0
34,exercises-in-latin-prosody,1823,prosody_III.I.23.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Ægroto domini deduxit corpore febres,]","<think>\n\nOkay, so the user wants me to adjus...","Deduxit domini ægroto corpore febres,",0
35,exercises-in-latin-prosody,1823,prosody_III.I.23.3,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Non animo curas. Valeat possessor oportet,]","<think>\n\nOkay, let's tackle this problem. Th...",Non animo curas oportet valeat possessor.,0
36,exercises-in-latin-prosody,1823,prosody_III.I.23.4,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Si comportatis rebus bene cogitat uti.],"<think>\n\nOkay, let's tackle this problem. Th...",Si uti comportatis bene rebus cogitat.,0
37,exercises-in-latin-prosody,1823,prosody_III.I.24.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[. Hic sedes augusta deæ, templique colendi]","<think>\n\nOkay, let me tackle this problem. T...","Hic sedes deæ augusta, colendi templique",0
38,exercises-in-latin-prosody,1823,prosody_III.I.24.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Religiosa silex, densis quam pinus obumbrat]","<think>\n\nOkay, let me tackle this problem. T...","Silex religiosa, quam pinus densis obumbrat.",0
39,exercises-in-latin-prosody,1823,prosody_III.I.24.3,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Frondibus, et nullâ lucos agitante procellâ,]","<think>\n\nOkay, let's tackle this problem. Th...","Frondibus, et nullā procellā lucos agitante,",0
40,exercises-in-latin-prosody,1823,prosody_III.I.24.4,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Stridula coniferi modulantur carmina rami.],"<think>\n\nOkay, so the user wants me to adjus...",Rami stridula modulantur coniferi carmina.,0

In [124]:
# create combined df, with new columns called "source file"
for i, file in enumerate(file_to_data.keys()):
    question_df = question_dfs[i]
    question_df['source_file'] = [file] * len(question_df)
    question_dfs[i] = question_df

combined_df = pd.concat(question_dfs)
combined_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question_text,multiple_choice_options,answers,raw_resp,parsed_resp,score,source_file
0,exercises-in-latin-prosody,1823,prosody_III.I.9.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Ipse dei clypeus terrâ cùm tollitur imâ,]","<think>\n\nOkay, so I need to adjust the posit...","Ipse dei clypeus imâ terrâ cùm tollitur,",0,prosody_caesura_scansion_english.json
1,exercises-in-latin-prosody,1823,prosody_III.I.9.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Manè rubet; terrâque rubet cùm conditur imâ.],"<think>\n\nOkay, so I need to adjust the given...","Manè rubet; terrâque rubet, cùm conditur imâ.",1,prosody_caesura_scansion_english.json
2,exercises-in-latin-prosody,1823,prosody_III.I.10.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[En, proles antiqua redit; concordia, virtus,]","<think>\n\nOkay, let's see. The user wants me ...","En, proles antiqua redit virtus, concordia;",0,prosody_caesura_scansion_english.json
3,exercises-in-latin-prosody,1823,prosody_III.I.10.2,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],[Cumque fide pietas altâ cervice vagantur.],"<think>\n\nOkay, so the user wants me to adjus...",Cumque fide pietas altâ cervice vagantur.,1,prosody_caesura_scansion_english.json
4,exercises-in-latin-prosody,1823,prosody_III.I.11.1,short_answer,scansion,unknown,english,latin,Form the following line into hexameter or pent...,[],"[Robora nec cuneis, et olentem scindere cedrum,]","<think>\n\nOkay, let's see. The user wants me ...","Robora nec cuneis, olentem *et* scindere cedrum,",0,prosody_caesura_scansion_english.json
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,exercises-in-latin-prosody,1823,prosody_III.I.23.4,short_answer,scansion,unknown,latin,latin,Versum infra positum in hexametrum aut pentame...,[],[Si comportatis rebus bene cogitat uti.],"<think>\nOkay, the user wants me to turn the g...",Si uti compositis rebus bene cogitat.**,0,prosody_caesura_scansion_latin.json
37,exercises-in-latin-prosody,1823,prosody_III.I.24.1,short_answer,scansion,unknown,latin,latin,Versum infra positum in hexametrum aut pentame...,[],"[. Hic sedes augusta deæ, templique colendi]","<think>\n\nOkay, so the user wants me to turn ...","Hic sedes augusta deæ, cultus templique.**",0,prosody_caesura_scansion_latin.json
38,exercises-in-latin-prosody,1823,prosody_III.I.24.2,short_answer,scansion,unknown,latin,latin,Versum infra positum in hexametrum aut pentame...,[],"[Religiosa silex, densis quam pinus obumbrat]","<think>\n\nOkay, let's tackle this problem. Th...","Silex religiosa, quam pinus densis obumbrat.",0,prosody_caesura_scansion_latin.json
39,exercises-in-latin-prosody,1823,prosody_III.I.24.3,short_answer,scansion,unknown,latin,latin,Versum infra positum in hexametrum aut pentame...,[],"[Frondibus, et nullâ lucos agitante procellâ,]","<think>\nOkay, the user wants me to translate ...","Frondibus, et nullâ procellâ lucos agitante,",0,prosody_caesura_scansion_latin.json
40,exercises-in-latin-prosody,1823,prosody_III.I.24.4,short_answer,scansion,unknown,latin,latin,Versum infra positum in hexametrum aut pentame...,[],[Stridula coniferi modulantur carmina rami.],"<think>\n\nOkay, the user wants me to convert ...",Rami stridula coniferi cantant carmina.,0,prosody_caesura_scansion_latin.json

In [125]:
normalize_str(answer_str_1)

'et procella nulla lucos agitante frondibus'

In [126]:
score(gold_str, answer_str_1)

gold: ['frondibus', 'et', 'nulla', 'lucos', 'agitante', 'procella']
pred: ['et', 'procella', 'nulla', 'lucos', 'agitante', 'frondibus']

0

In [127]:
# save combined df
save_dir = f'../data/model_responses_parsed/{model_name}'
if not os.path.exists(save_dir):
    os.makedirs(save_dir)
# drop the columns question, multiple_choice_options, n_required, correctness_logic
save_df = combined_df.drop(columns=['question_text', 'multiple_choice_options', ])
save_dict = save_df.to_dict(orient='records')



with open(os.path.join(save_dir, 'prosody_caesura.json'), 'w') as f:
    json.dump(save_dict, f, indent=4)

In [128]:
def accuracy_by(df, group_cols):
    """
    df          : DataFrame with a single 'score' column (0/1 values)
    group_cols  : column or list of columns to group on
    """
    if isinstance(group_cols, str):
        group_cols = [group_cols]

    return (
        df
        .groupby(group_cols, dropna=False)['score']
        .agg(accuracy='mean', n_items='size')
        .reset_index()
    )

In [129]:
acc_lang_combos = accuracy_by(combined_df,
                             group_cols=["question_language", "answer_language"],
                             #score_cols=model_name+'_score'
                             )
acc_lang_combos

  question_language answer_language  accuracy  n_items
0           english           latin  0.121951       41
1             latin           latin  0.146341       41

feet questions

In [154]:
with_instr = False

In [152]:
data_dir = '../data/final_dataset'
long_ans_files = [
                  'prosody_feet_questions_english.json',
                  'prosody_feet_questions_latin.json',
                  ]
long_ans_files = [os.path.join(data_dir, f) for f in long_ans_files]

file_to_data = {}
for file in long_ans_files:
    base_name = os.path.basename(file)
    file_to_data[base_name] = []
    with open(file, 'r') as f:
        file_to_data[base_name] += json.load(f)

    print(base_name, len(file_to_data[base_name]))

prosody_feet_questions_english.json 20
prosody_feet_questions_latin.json 20

In [155]:
file_to_resp = {}

model_resp_dir = f'../data/model_responses/{model_name}'

for file in file_to_data.keys():
    base_name = os.path.basename(file)
    
    if with_instr:
        base_name = base_name.replace('.json', '_with_instr.json')
    file_to_resp[base_name] = {}
    with open(os.path.join(model_resp_dir, base_name), 'r') as f:
        file_to_resp[base_name] = json.load(f)
    print(base_name, len(file_to_resp[base_name]))

prosody_feet_questions_english.json 20
prosody_feet_questions_latin.json 20

In [156]:
# make dfs
question_dfs = []
for file in file_to_data.keys():
    questions = file_to_data[file]
    question_df = pd.DataFrame(questions)
    question_dfs.append(question_df)

In [157]:
for i, file in enumerate(file_to_data.keys()):
    question_df = question_dfs[i]
    if with_instr:
        file = file.replace('.json', '_with_instr.json')
    answer_dict = file_to_resp[file]
    answer_col = []
    for (i, row) in question_df.iterrows():
        q_id = row['question_id']

        model_answer = answer_dict[q_id]
        answer_col.append(model_answer)

    question_df['raw_resp'] = answer_col

In [158]:
for i, file in enumerate(file_to_data.keys()):
    question_df = question_dfs[i]
    question_df['parsed_resp'] = question_df['raw_resp'].apply(parse_resp)
    question_dfs[i] = question_df
question_dfs[0]

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,raw_resp,parsed_resp
0,exercises-in-latin-prosody,1823,prosody_app.I.1.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Trochee, Spondee, Dactyl, Trochee, Trochee]","<think>\n\nOkay, so the user is asking about t...","iamb, spondee, iamb, spondee, spondee, trochee**"
1,exercises-in-latin-prosody,1823,prosody_app.I.1.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Trochee, Spondee, Dactyl, Trochee, Trochee]","<think>\n\nOkay, so I need to figure out the f...","Trochee,Cretic,Dactyl,Trochee,Bacchius"
2,exercises-in-latin-prosody,1823,prosody_app.I.2.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[iambus, iambus, iambus, iambus, spondee, iambus]","<think>\n\nOkay, let's see. The user provided ...","iamb,iamb,iamb,spondee,spondee,iamb"
3,exercises-in-latin-prosody,1823,prosody_app.I.2.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[iambus, iambus, spondee, iambus]","<think>\n\nOkay, let's tackle this question. T...","Spondee,Trochee,Spondee,Spondee"
4,exercises-in-latin-prosody,1823,prosody_app.I.3.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[spondee, choriambus, iambus]","<think>\nOkay, let's tackle this question. The...","pyrrhic, cretic, spondee"
5,exercises-in-latin-prosody,1823,prosody_app.I.3.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[spondee, choriambus, choriambus, iambus]","<think>\n\nOkay, so the user is asking me to i...","spondee,trochee,iamb,iamb"
6,exercises-in-latin-prosody,1823,prosody_app.I.3.3,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[spondee, choriambus, iambus]","<think>\nOkay, let's see. The user wants me to...","Trochee,Choriamb,Iamb"
7,exercises-in-latin-prosody,1823,prosody_app.I.3.4,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[spondee, choriambus, choriambus, iambus]","<think>\n\nOkay, so the user provided a line o...","trochee, pyrrhic, trochee, pyrrhic"
8,exercises-in-latin-prosody,1823,prosody_app.I.4.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Choriamb, Amphibrac]","<think>\n\nOkay, let's see. The user provided ...","spondee, spondee, iamb"
9,exercises-in-latin-prosody,1823,prosody_app.I.4.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Second Epitrit, Choriamb, Choriamb, Amphibrac]","<think>\n\nOkay, so I need to figure out the m...","molossus, spondee, iamb, dactyl, dactyl, trochee"
10,exercises-in-latin-prosody,1823,prosody_app.I.4.3,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Second Epitrit, Amphibrac]","<think>\nOkay, so the user is asking about the...","spondee, pyrrhic, anapest"
11,exercises-in-latin-prosody,1823,prosody_app.I.4.4,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Choriamb, Choriamb, Choriamb, Amphibrac]","<think>\nOkay, let's tackle this query. The us...","spondee, trochee, trochee, cretic, dactyl, spo..."
12,exercises-in-latin-prosody,1823,prosody_app.I.5.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[dactyl, dactyl, dactyl, pyrrhic]","<think>\nOkay, let's see. The user wants me to...","dactyl, cretic, dactyl, pyrrhic"
13,exercises-in-latin-prosody,1823,prosody_app.I.5.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[dactyl, dactyl, dactyl, pyrrhic]","<think>\n\nOkay, let's tackle this question. T...","anapest, dactyl, amphibrach, trochee"
14,exercises-in-latin-prosody,1823,prosody_app.I.5.3,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[anapest, tribrac, spondee, iambus, spondee, i...","<think>\n\nOkay, so the user is asking me to i...","cretic,tribrach,trochee,trochee,spondee,trochee"
15,exercises-in-latin-prosody,1823,prosody_app.I.5.4,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[anapest, iambus, spondee, iambus, spondee, ia...","<think>\n\nOkay, so the user provided this lin...","anapest, trochee, spondee, spondee, spondee, t..."
16,exercises-in-latin-prosody,1823,prosody_app.I.6.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[small ionic, small ionic, small ionic]","<think>\n\nOkay, so the user is asking about t...","pyrrhic, spondee, pyrrhic, spondee, pyrrhic, s..."
17,exercises-in-latin-prosody,1823,prosody_app.I.6.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[small ionic, small ionic, small ionic, small ...","<think>\n\nOkay, let's tackle this question. T...","Spondee,Dactyl,Dactyl,Spondee,Dactyl,Spondee"
18,exercises-in-latin-prosody,1823,prosody_app.I.6.3,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[great ionic, great ionic, dichoree, spondee]","<think>\n\nOkay, let's see. The user is asking...","Spondee, Dactyl, Spondee, Dactyl, Spondee, Dactyl"
19,exercises-in-latin-prosody,1823,prosody_app.I.6.4,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[great ionic, great ionic, dichoree, spondee]","<think>\n\nOkay, let's see. The user provided ...","molossus,dactyl,dactyl,spondee"

In [159]:
gold_names = set()
pred_names = set()

for question_df in question_dfs:
    answers = question_df['answers'].to_list()
    answer_strs = [a[0] for  a in answers]
    for a in answer_strs:
        a = a.lower()
        names = a.split(',')
        names = [n.strip() for n in names]
        gold_names.update(names)

    parsed_resps = question_df['parsed_resp'].to_list()
    for a in parsed_resps:
        a = a.lower()
        names = a.split(',')
        names = [n.strip() for n in names]
        pred_names.update(names)

In [136]:
gold_names

{'amphibrac',
 'anapest',
 'choriamb',
 'choriambus',
 'dactyl',
 'dichoree',
 'great ionic',
 'iambus',
 'pyrrhic',
 'second epitrit',
 'small ionic',
 'spondee',
 'tribrac',
 'trochee'}

In [102]:
for g in sorted(list(gold_names)):
    print(g, end=', ')

amphibrac, anapest, choriamb, choriambus, dactyl, dichoree, great ionic, iambus, pyrrhic, second epitrit, small ionic, spondee, tribrac, trochee,

In [160]:
pred_names

{'amphibrach',
 'anapest',
 'bacchius',
 'choriamb',
 'cretic',
 'dactyl',
 'dactylus',
 'iamb',
 'iambus',
 'molossus',
 'pyrrhic',
 'spondee',
 'spondeus',
 'tetrabrach',
 'tribrach',
 'trochee',
 'trochee**',
 'trocheus'}

In [168]:
# mapping for alternate names
mapping = {
    'dactyl' : ['dactylus'],
    'dactylus': ['dactyl'],
    'iamb': ['iambus'],
    'iambus': ['iamb'],
    'spondaeus': ['spondee', 'spondeus'],
    'spondee': ['spondaeus', 'spondeus'],
    'spondeus': ['spondaeus', 'spondee'],
    'trochaeus': ['trochee', 'trocheus'],
    'trochee': ['trochaeus', 'trocheus'],
    'trocheus': ['trochaeus', 'trochee'],

    'amphibrac': ['amphibrach'],
    'amphibrach': ['amphibrac'],
    'anapest': [],
    'bacchius': [],
    'choriamb': ['choriambus'],
    'choriambus': ['choriamb'],
    'cretic': [],
    'dichoree': [],
    'great ionic': [],
    'molossus': [],
    'pyrrhic': [],
    'second epitrit': [],
    'small ionic': [],
    'tribrac': ['tribrach'],
    'tribrach': ['tribrac'],
    'tetrabrach': [],
}

In [166]:
def score_feet(gold_str, answer_str):
    gold_str = gold_str.lower()
    answer_str = answer_str.lower()

    answer_str = answer_str.replace('*', '')

    gold_words = gold_str.split(',')
    answer_words = answer_str.split(',')
    gold_words = [w.strip() for w in gold_words]
    answer_words = [w.strip() for w in answer_words]

    #if len(gold_words) != len(answer_words):
    #    return 0
    
    print('gold:', gold_words)
    print('pred:', answer_words)
    
    # position of each word must be the same
    correct = 0
    total = 0
    for (word, pred) in zip(gold_words, answer_words):
        if word == pred: correct +=1
        elif any(word==p for p in mapping[pred]): correct += 1

        total += 1
    
    if total != len(gold_words): total = len(gold_words)
    
    return correct / total if total > 0 else 0

In [106]:
question_dfs[0].iloc[0]

source_name                                       exercises-in-latin-prosody
source_year                                                             1823
question_id                                                prosody_app.I.1.1
question_format                                                 short_answer
question_content                                                    scansion
difficulty                                                           unknown
question_language                                                    english
answer_language                                                      english
question                   What is the name of each foot in the following...
multiple_choice_options                                                   []
answers                         [Trochee, Spondee, Dactyl, Trochee, Trochee]
raw_resp                   To identify the feet in the given line of poet...
parsed_resp                        trochee, trochee, dactyl, dactyl, spondee
Name: 0, dtype: object

In [163]:
gold = question_dfs[0].iloc[0]['answers'][0]
pred = question_dfs[0].iloc[0]['parsed_resp']
score_feet(gold, pred)

gold: ['trochee', 'spondee', 'dactyl', 'trochee', 'trochee']
pred: ['iamb', 'spondee', 'iamb', 'spondee', 'spondee', 'trochee']

0.2

In [169]:
for i, file in enumerate(file_to_data.keys()):
    question_df = question_dfs[i]
    scores = []
    for (i, row) in question_df.iterrows():
        q_id = row['question_id']
        correct_answer = row['answers'][0]
        model_answer = row['parsed_resp']
        answer_language = row['answer_language']
        scores.append(score_feet(correct_answer, model_answer))

    question_df['score'] = scores
question_dfs[0]

gold: ['trochee', 'spondee', 'dactyl', 'trochee', 'trochee']
pred: ['iamb', 'spondee', 'iamb', 'spondee', 'spondee', 'trochee']
gold: ['trochee', 'spondee', 'dactyl', 'trochee', 'trochee']
pred: ['trochee', 'cretic', 'dactyl', 'trochee', 'bacchius']
gold: ['iambus', 'iambus', 'iambus', 'iambus', 'spondee', 'iambus']
pred: ['iamb', 'iamb', 'iamb', 'spondee', 'spondee', 'iamb']
gold: ['iambus', 'iambus', 'spondee', 'iambus']
pred: ['spondee', 'trochee', 'spondee', 'spondee']
gold: ['spondee', 'choriambus', 'iambus']
pred: ['pyrrhic', 'cretic', 'spondee']
gold: ['spondee', 'choriambus', 'choriambus', 'iambus']
pred: ['spondee', 'trochee', 'iamb', 'iamb']
gold: ['spondee', 'choriambus', 'iambus']
pred: ['trochee', 'choriamb', 'iamb']
gold: ['spondee', 'choriambus', 'choriambus', 'iambus']
pred: ['trochee', 'pyrrhic', 'trochee', 'pyrrhic']
gold: ['choriamb', 'amphibrac']
pred: ['spondee', 'spondee', 'iamb']
gold: ['second epitrit', 'choriamb', 'choriamb', 'amphibrac']
pred: ['molossus', 'spondee', 'iamb', 'dactyl', 'dactyl', 'trochee']
gold: ['second epitrit', 'amphibrac']
pred: ['spondee', 'pyrrhic', 'anapest']
gold: ['choriamb', 'choriamb', 'choriamb', 'amphibrac']
pred: ['spondee', 'trochee', 'trochee', 'cretic', 'dactyl', 'spondee']
gold: ['dactyl', 'dactyl', 'dactyl', 'pyrrhic']
pred: ['dactyl', 'cretic', 'dactyl', 'pyrrhic']
gold: ['dactyl', 'dactyl', 'dactyl', 'pyrrhic']
pred: ['anapest', 'dactyl', 'amphibrach', 'trochee']
gold: ['anapest', 'tribrac', 'spondee', 'iambus', 'spondee', 'iambus']
pred: ['cretic', 'tribrach', 'trochee', 'trochee', 'spondee', 'trochee']
gold: ['anapest', 'iambus', 'spondee', 'iambus', 'spondee', 'iambus']
pred: ['anapest', 'trochee', 'spondee', 'spondee', 'spondee', 'trochee']
gold: ['small ionic', 'small ionic', 'small ionic']
pred: ['pyrrhic', 'spondee', 'pyrrhic', 'spondee', 'pyrrhic', 'spondee']
gold: ['small ionic', 'small ionic', 'small ionic', 'small ionic']
pred: ['spondee', 'dactyl', 'dactyl', 'spondee', 'dactyl', 'spondee']
gold: ['great ionic', 'great ionic', 'dichoree', 'spondee']
pred: ['spondee', 'dactyl', 'spondee', 'dactyl', 'spondee', 'dactyl']
gold: ['great ionic', 'great ionic', 'dichoree', 'spondee']
pred: ['molossus', 'dactyl', 'dactyl', 'spondee']
gold: ['trochee', 'spondee', 'dactyl', 'trochee', 'trochee']
pred: ['dactyl', 'spondee', 'dactyl', 'dactyl', 'spondee', 'dactyl']
gold: ['trochee', 'spondee', 'dactyl', 'trochee', 'trochee']
pred: ['trochee', 'spondee', 'dactyl', 'trochee', 'iamb']
gold: ['iambus', 'iambus', 'iambus', 'iambus', 'spondee', 'iambus']
pred: ['iambus', 'iambus', 'iambus', 'spondeus', 'spondeus', 'iambus']
gold: ['iambus', 'iambus', 'spondee', 'iambus']
pred: ['spondeus', 'iambus', 'spondeus', 'spondeus']
gold: ['spondee', 'choriambus', 'iambus']
pred: ['trocheus', 'trocheus', 'iambus', 'iambus']
gold: ['spondee', 'choriambus', 'choriambus', 'iambus']
pred: ['spondee', 'choriamb', 'cretic', 'spondee']
gold: ['spondee', 'choriambus', 'iambus']
pred: ['pyrrhic', 'pyrrhic', 'pyrrhic']
gold: ['spondee', 'choriambus', 'choriambus', 'iambus']
pred: ['spondeus', 'dactylus', 'dactylus', 'iambus']
gold: ['choriamb', 'amphibrac']
pred: ['trochee', 'iamb', 'spondee', 'molossus']
gold: ['second epitrit', 'choriamb', 'choriamb', 'amphibrac']
pred: ['dactyl', 'spondee', 'spondee', 'dactyl', 'spondee', 'spondee']
gold: ['second epitrit', 'amphibrac']
pred: ['cretic', 'spondee']
gold: ['choriamb', 'choriamb', 'choriamb', 'amphibrac']
pred: ['spondee', 'dactyl', 'spondee', 'dactyl', 'spondee', 'dactyl']
gold: ['dactyl', 'dactyl', 'dactyl', 'pyrrhic']
pred: ['cretic', 'amphibrach', 'amphibrach', 'trochee']
gold: ['dactyl', 'dactyl', 'dactyl', 'pyrrhic']
pred: ['dactyl', 'cretic', 'dactyl', 'trochee']
gold: ['anapest', 'tribrac', 'spondee', 'iambus', 'spondee', 'iambus']
pred: ['cretic', 'pyrrhic', 'spondee', 'spondee', 'spondee', 'spondee']
gold: ['anapest', 'iambus', 'spondee', 'iambus', 'spondee', 'iambus']
pred: ['trochee', 'iamb', 'spondee', 'iamb', 'spondee', 'trochee']
gold: ['small ionic', 'small ionic', 'small ionic']
pred: ['pyrrhic', 'spondee', 'pyrrhic', 'spondee', 'pyrrhic', 'spondee']
gold: ['small ionic', 'small ionic', 'small ionic', 'small ionic']
pred: ['dactyl', 'dactyl', 'dactyl', 'dactyl', 'dactyl', 'spondee']
gold: ['great ionic', 'great ionic', 'dichoree', 'spondee']
pred: ['spondee', 'dactyl', 'dactyl', 'spondee']
gold: ['great ionic', 'great ionic', 'dichoree', 'spondee']
pred: ['anapest', 'spondee', 'tetrabrach', 'trochee']

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,raw_resp,parsed_resp,score
0,exercises-in-latin-prosody,1823,prosody_app.I.1.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Trochee, Spondee, Dactyl, Trochee, Trochee]","<think>\n\nOkay, so the user is asking about t...","iamb, spondee, iamb, spondee, spondee, trochee**",0.200000
1,exercises-in-latin-prosody,1823,prosody_app.I.1.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Trochee, Spondee, Dactyl, Trochee, Trochee]","<think>\n\nOkay, so I need to figure out the f...","Trochee,Cretic,Dactyl,Trochee,Bacchius",0.600000
2,exercises-in-latin-prosody,1823,prosody_app.I.2.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[iambus, iambus, iambus, iambus, spondee, iambus]","<think>\n\nOkay, let's see. The user provided ...","iamb,iamb,iamb,spondee,spondee,iamb",0.833333
3,exercises-in-latin-prosody,1823,prosody_app.I.2.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[iambus, iambus, spondee, iambus]","<think>\n\nOkay, let's tackle this question. T...","Spondee,Trochee,Spondee,Spondee",0.250000
4,exercises-in-latin-prosody,1823,prosody_app.I.3.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[spondee, choriambus, iambus]","<think>\nOkay, let's tackle this question. The...","pyrrhic, cretic, spondee",0.000000
5,exercises-in-latin-prosody,1823,prosody_app.I.3.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[spondee, choriambus, choriambus, iambus]","<think>\n\nOkay, so the user is asking me to i...","spondee,trochee,iamb,iamb",0.500000
6,exercises-in-latin-prosody,1823,prosody_app.I.3.3,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[spondee, choriambus, iambus]","<think>\nOkay, let's see. The user wants me to...","Trochee,Choriamb,Iamb",0.666667
7,exercises-in-latin-prosody,1823,prosody_app.I.3.4,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[spondee, choriambus, choriambus, iambus]","<think>\n\nOkay, so the user provided a line o...","trochee, pyrrhic, trochee, pyrrhic",0.000000
8,exercises-in-latin-prosody,1823,prosody_app.I.4.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Choriamb, Amphibrac]","<think>\n\nOkay, let's see. The user provided ...","spondee, spondee, iamb",0.000000
9,exercises-in-latin-prosody,1823,prosody_app.I.4.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Second Epitrit, Choriamb, Choriamb, Amphibrac]","<think>\n\nOkay, so I need to figure out the m...","molossus, spondee, iamb, dactyl, dactyl, trochee",0.000000
10,exercises-in-latin-prosody,1823,prosody_app.I.4.3,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Second Epitrit, Amphibrac]","<think>\nOkay, so the user is asking about the...","spondee, pyrrhic, anapest",0.000000
11,exercises-in-latin-prosody,1823,prosody_app.I.4.4,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Choriamb, Choriamb, Choriamb, Amphibrac]","<think>\nOkay, let's tackle this query. The us...","spondee, trochee, trochee, cretic, dactyl, spo...",0.000000
12,exercises-in-latin-prosody,1823,prosody_app.I.5.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[dactyl, dactyl, dactyl, pyrrhic]","<think>\nOkay, let's see. The user wants me to...","dactyl, cretic, dactyl, pyrrhic",0.750000
13,exercises-in-latin-prosody,1823,prosody_app.I.5.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[dactyl, dactyl, dactyl, pyrrhic]","<think>\n\nOkay, let's tackle this question. T...","anapest, dactyl, amphibrach, trochee",0.250000
14,exercises-in-latin-prosody,1823,prosody_app.I.5.3,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[anapest, tribrac, spondee, iambus, spondee, i...","<think>\n\nOkay, so the user is asking me to i...","cretic,tribrach,trochee,trochee,spondee,trochee",0.333333
15,exercises-in-latin-prosody,1823,prosody_app.I.5.4,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[anapest, iambus, spondee, iambus, spondee, ia...","<think>\n\nOkay, so the user provided this lin...","anapest, trochee, spondee, spondee, spondee, t...",0.500000
16,exercises-in-latin-prosody,1823,prosody_app.I.6.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[small ionic, small ionic, small ionic]","<think>\n\nOkay, so the user is asking about t...","pyrrhic, spondee, pyrrhic, spondee, pyrrhic, s...",0.000000
17,exercises-in-latin-prosody,1823,prosody_app.I.6.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[small ionic, small ionic, small ionic, small ...","<think>\n\nOkay, let's tackle this question. T...","Spondee,Dactyl,Dactyl,Spondee,Dactyl,Spondee",0.000000
18,exercises-in-latin-prosody,1823,prosody_app.I.6.3,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[great ionic, great ionic, dichoree, spondee]","<think>\n\nOkay, let's see. The user is asking...","Spondee, Dactyl, Spondee, Dactyl, Spondee, Dactyl",0.000000
19,exercises-in-latin-prosody,1823,prosody_app.I.6.4,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[great ionic, great ionic, dichoree, spondee]","<think>\n\nOkay, let's see. The user provided ...","molossus,dactyl,dactyl,spondee",0.250000

In [170]:
# create combined df, with new columns called "source file"
for i, file in enumerate(file_to_data.keys()):
    question_df = question_dfs[i]
    if with_instr:
        file = file.replace('.json', '_with_instr.json')
    question_df['source_file'] = [file] * len(question_df)
    question_dfs[i] = question_df

combined_df = pd.concat(question_dfs)
combined_df

,source_name,source_year,question_id,question_format,question_content,difficulty,question_language,answer_language,question,multiple_choice_options,answers,raw_resp,parsed_resp,score,source_file
0,exercises-in-latin-prosody,1823,prosody_app.I.1.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Trochee, Spondee, Dactyl, Trochee, Trochee]","<think>\n\nOkay, so the user is asking about t...","iamb, spondee, iamb, spondee, spondee, trochee**",0.200000,prosody_feet_questions_english.json
1,exercises-in-latin-prosody,1823,prosody_app.I.1.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Trochee, Spondee, Dactyl, Trochee, Trochee]","<think>\n\nOkay, so I need to figure out the f...","Trochee,Cretic,Dactyl,Trochee,Bacchius",0.600000,prosody_feet_questions_english.json
2,exercises-in-latin-prosody,1823,prosody_app.I.2.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[iambus, iambus, iambus, iambus, spondee, iambus]","<think>\n\nOkay, let's see. The user provided ...","iamb,iamb,iamb,spondee,spondee,iamb",0.833333,prosody_feet_questions_english.json
3,exercises-in-latin-prosody,1823,prosody_app.I.2.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[iambus, iambus, spondee, iambus]","<think>\n\nOkay, let's tackle this question. T...","Spondee,Trochee,Spondee,Spondee",0.250000,prosody_feet_questions_english.json
4,exercises-in-latin-prosody,1823,prosody_app.I.3.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[spondee, choriambus, iambus]","<think>\nOkay, let's tackle this question. The...","pyrrhic, cretic, spondee",0.000000,prosody_feet_questions_english.json
5,exercises-in-latin-prosody,1823,prosody_app.I.3.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[spondee, choriambus, choriambus, iambus]","<think>\n\nOkay, so the user is asking me to i...","spondee,trochee,iamb,iamb",0.500000,prosody_feet_questions_english.json
6,exercises-in-latin-prosody,1823,prosody_app.I.3.3,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[spondee, choriambus, iambus]","<think>\nOkay, let's see. The user wants me to...","Trochee,Choriamb,Iamb",0.666667,prosody_feet_questions_english.json
7,exercises-in-latin-prosody,1823,prosody_app.I.3.4,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[spondee, choriambus, choriambus, iambus]","<think>\n\nOkay, so the user provided a line o...","trochee, pyrrhic, trochee, pyrrhic",0.000000,prosody_feet_questions_english.json
8,exercises-in-latin-prosody,1823,prosody_app.I.4.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Choriamb, Amphibrac]","<think>\n\nOkay, let's see. The user provided ...","spondee, spondee, iamb",0.000000,prosody_feet_questions_english.json
9,exercises-in-latin-prosody,1823,prosody_app.I.4.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Second Epitrit, Choriamb, Choriamb, Amphibrac]","<think>\n\nOkay, so I need to figure out the m...","molossus, spondee, iamb, dactyl, dactyl, trochee",0.000000,prosody_feet_questions_english.json
10,exercises-in-latin-prosody,1823,prosody_app.I.4.3,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Second Epitrit, Amphibrac]","<think>\nOkay, so the user is asking about the...","spondee, pyrrhic, anapest",0.000000,prosody_feet_questions_english.json
11,exercises-in-latin-prosody,1823,prosody_app.I.4.4,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[Choriamb, Choriamb, Choriamb, Amphibrac]","<think>\nOkay, let's tackle this query. The us...","spondee, trochee, trochee, cretic, dactyl, spo...",0.000000,prosody_feet_questions_english.json
12,exercises-in-latin-prosody,1823,prosody_app.I.5.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[dactyl, dactyl, dactyl, pyrrhic]","<think>\nOkay, let's see. The user wants me to...","dactyl, cretic, dactyl, pyrrhic",0.750000,prosody_feet_questions_english.json
13,exercises-in-latin-prosody,1823,prosody_app.I.5.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[dactyl, dactyl, dactyl, pyrrhic]","<think>\n\nOkay, let's tackle this question. T...","anapest, dactyl, amphibrach, trochee",0.250000,prosody_feet_questions_english.json
14,exercises-in-latin-prosody,1823,prosody_app.I.5.3,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[anapest, tribrac, spondee, iambus, spondee, i...","<think>\n\nOkay, so the user is asking me to i...","cretic,tribrach,trochee,trochee,spondee,trochee",0.333333,prosody_feet_questions_english.json
15,exercises-in-latin-prosody,1823,prosody_app.I.5.4,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[anapest, iambus, spondee, iambus, spondee, ia...","<think>\n\nOkay, so the user provided this lin...","anapest, trochee, spondee, spondee, spondee, t...",0.500000,prosody_feet_questions_english.json
16,exercises-in-latin-prosody,1823,prosody_app.I.6.1,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[small ionic, small ionic, small ionic]","<think>\n\nOkay, so the user is asking about t...","pyrrhic, spondee, pyrrhic, spondee, pyrrhic, s...",0.000000,prosody_feet_questions_english.json
17,exercises-in-latin-prosody,1823,prosody_app.I.6.2,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[small ionic, small ionic, small ionic, small ...","<think>\n\nOkay, let's tackle this question. T...","Spondee,Dactyl,Dactyl,Spondee,Dactyl,Spondee",0.000000,prosody_feet_questions_english.json
18,exercises-in-latin-prosody,1823,prosody_app.I.6.3,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[great ionic, great ionic, dichoree, spondee]","<think>\n\nOkay, let's see. The user is asking...","Spondee, Dactyl, Spondee, Dactyl, Spondee, Dactyl",0.000000,prosody_feet_questions_english.json
19,exercises-in-latin-prosody,1823,prosody_app.I.6.4,short_answer,scansion,unknown,english,english,What is the name of each foot in the following...,[],"[great ionic, great ionic, dichoree, spondee]","<think>\n\nOkay, let's see. The user provided ...","molossus,dactyl,dactyl,spondee",0.250000,prosody_feet_questions_english.json
0,exercises-in-latin-prosody,1823,prosody_app.I.1.1,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[Trochee, Spondee, Dactyl, Trochee, Trochee]","<think>\n\nOkay, the user is asking for the na...","dactyl,spondee,dactyl,dactyl,spondee,dactyl",0.400000,prosody_feet_questions_latin.json
1,exercises-in-latin-prosody,1823,prosody_app.I.1.2,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[Trochee, Spondee, Dactyl, Trochee, Trochee]","<think>\n\nAlright, the user is asking about t...","trochee, spondee, dactyl, trochee, iamb",0.800000,prosody_feet_questions_latin.json
2,exercises-in-latin-prosody,1823,prosody_app.I.2.1,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[iambus, iambus, iambus, iambus, spondee, iambus]","<think>\n\nOkay, let's see. The user is asking...","iambus, iambus, iambus, spondeus, spondeus, ia...",0.833333,prosody_feet_questions_latin.json
3,exercises-in-latin-prosody,1823,prosody_app.I.2.2,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[iambus, iambus, spondee, iambus]","<think>\n\nOkay, let's tackle this question. T...","Spondeus, Iambus, Spondeus, Spondeus",0.500000,prosody_feet_questions_latin.json
4,exercises-in-latin-prosody,1823,prosody_app.I.3.1,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[spondee, choriambus, iambus]","<think>\n\nOkay, the user is asking for the na...","Trocheus, Trocheus, Iambus, Iambus",0.333333,prosody_feet_questions_latin.json
5,exercises-in-latin-prosody,1823,prosody_app.I.3.2,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[spondee, choriambus, choriambus, iambus]","<think>\n\nOkay, the user is asking about the ...","spondee, choriamb, cretic, spondee",0.500000,prosody_feet_questions_latin.json
6,exercises-in-latin-prosody,1823,prosody_app.I.3.3,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[spondee, choriambus, iambus]","<think>\n\nOkay, so the user is asking about t...","pyrrhic, pyrrhic, pyrrhic",0.000000,prosody_feet_questions_latin.json
7,exercises-in-latin-prosody,1823,prosody_app.I.3.4,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[spondee, choriambus, choriambus, iambus]","<think>\n\nOkay, let's tackle this question. T...","spondeus, dactylus, dactylus, iambus",0.500000,prosody_feet_questions_latin.json
8,exercises-in-latin-prosody,1823,prosody_app.I.4.1,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[Choriamb, Amphibrac]","<think>\n\nOkay, so the user is asking about t...","Trochee, Iamb, Spondee, Molossus",0.000000,prosody_feet_questions_latin.json
9,exercises-in-latin-prosody,1823,prosody_app.I.4.2,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[Second Epitrit, Choriamb, Choriamb, Amphibrac]","<think>\n\nOkay, let's tackle this question. T...","Dactyl,Spondee,Spondee,Dactyl,Spondee,Spondee",0.000000,prosody_feet_questions_latin.json
10,exercises-in-latin-prosody,1823,prosody_app.I.4.3,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[Second Epitrit, Amphibrac]","<think>\n\nOkay, the user is asking for the na...","cretic, spondee",0.000000,prosody_feet_questions_latin.json
11,exercises-in-latin-prosody,1823,prosody_app.I.4.4,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[Choriamb, Choriamb, Choriamb, Amphibrac]","<think>\n\nOkay, let's tackle this question. T...","spondee, dactyl, spondee, dactyl, spondee, dactyl",0.000000,prosody_feet_questions_latin.json
12,exercises-in-latin-prosody,1823,prosody_app.I.5.1,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[dactyl, dactyl, dactyl, pyrrhic]","<think>\n\nOkay, the user is asking for the na...","cretic, amphibrach, amphibrach, trochee",0.000000,prosody_feet_questions_latin.json
13,exercises-in-latin-prosody,1823,prosody_app.I.5.2,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[dactyl, dactyl, dactyl, pyrrhic]","<think>\n\nOkay, the user is asking about the ...","dactyl, cretic, dactyl, trochee",0.500000,prosody_feet_questions_latin.json
14,exercises-in-latin-prosody,1823,prosody_app.I.5.3,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[anapest, tribrac, spondee, iambus, spondee, i...","<think>\n\nOkay, so the user is asking for the...","cretic, pyrrhic, spondee, spondee, spondee, sp...",0.333333,prosody_feet_questions_latin.json
15,exercises-in-latin-prosody,1823,prosody_app.I.5.4,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[anapest, iambus, spondee, iambus, spondee, ia...","<think>\n\nOkay, let's see. The user is asking...","trochee,iamb,spondee,iamb,spondee,trochee",0.666667,prosody_feet_questions_latin.json
16,exercises-in-latin-prosody,1823,prosody_app.I.6.1,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[small ionic, small ionic, small ionic]","<think>\n\nOkay, the user is asking for the na...","pyrrhic, spondee, pyrrhic, spondee, pyrrhic, s...",0.000000,prosody_feet_questions_latin.json
17,exercises-in-latin-prosody,1823,prosody_app.I.6.2,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[small ionic, small ionic, small ionic, small ...","<think>\n\nOkay, let's tackle this question. T...","dactyl, dactyl, dactyl, dactyl, dactyl, spondee",0.000000,prosody_feet_questions_latin.json
18,exercises-in-latin-prosody,1823,prosody_app.I.6.3,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[great ionic, great ionic, dichoree, spondee]","<think>\n\nOkay, let's tackle this question. T...","spondee, dactyl, dactyl, spondee",0.250000,prosody_feet_questions_latin.json
19,exercises-in-latin-prosody,1823,prosody_app.I.6.4,short_answer,scansion,unknown,latin,english,Quod est nomen unicuique pedi in hoc versu poe...,[],"[great ionic, great ionic, dichoree, spondee]","<think>\n\nOkay, let's tackle this question. T...","anapest, spondee, tetrabrach, trochee",0.000000,prosody_feet_questions_latin.json

In [171]:
# save combined df
save_dir = f'../data/model_responses_parsed/{model_name}'
if not os.path.exists(save_dir):
    os.makedirs(save_dir)
# drop the columns question, multiple_choice_options, n_required, correctness_logic
save_df = combined_df.drop(columns=['question', 'multiple_choice_options', ])
save_dict = save_df.to_dict(orient='records')


save_name = 'prosody_feet.json'
if with_instr: save_name = save_name.replace('.json', '_with_instr.json')
with open(os.path.join(save_dir, save_name), 'w') as f:
    json.dump(save_dict, f, indent=4)

In [172]:
acc_lang_combos = accuracy_by(combined_df,
                             group_cols=["question_language", "answer_language"],
                             #score_cols=model_name+'_score'
                             )
acc_lang_combos

  question_language answer_language  accuracy  n_items
0           english         english  0.256667       20
1             latin         english  0.280833       20